package net.lemursaucepacket.fixes.mixin.distanthorizons;

import net.minecraft.core.Holder;
import net.minecraft.core.QuartPos;
import net.minecraft.server.level.WorldGenRegion;
import net.minecraft.world.level.biome.Biome;
import net.minecraft.world.level.chunk.ChunkAccess;
import net.minecraft.world.level.chunk.status.ChunkStatus;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Unique;

/**
 * Distant Horizons (3.3.3) builds its distant land with Minecraft's own generator, a few chunks at a time, in a
 * stand-in world region that holds only those chunks. Building a chunk's surface reads the biomes one step (four
 * blocks) past the chunk's edge (ModernFix gathers them all up front), and past the edge of Distant Horizons' group
 * there is no chunk to read them from: Minecraft then works each one out from scratch, the full climate calculation.
 * With this pack's terrain (Terralith, Tectonic) that was about 40% of all the time spent building distant land.
 *
 * <p>For a spot outside the chunks the region holds, this answers with the biome one step in, which it does hold. It
 * only changes which biome the surface rules see in the last few blocks at the edge of a group, in land that exists
 * only as distant scenery; real chunks are generated by Minecraft as usual.
 */
@Mixin(targets = "com.seibel.distanthorizons.common.wrappers.worldGeneration.mimicObject.DhLitWorldGenRegion_neoforge", remap = false)
public abstract class GenRegionBiomeMixin extends WorldGenRegion {
    /** The eight steps to a neighbouring spot, straight ones first. */
    @Unique
    private static final int[][] lsp_fixes$STEPS = {{1, 0}, {-1, 0}, {0, 1}, {0, -1}, {1, 1}, {1, -1}, {-1, 1}, {-1, -1}};

    private GenRegionBiomeMixin() {
        super(null, null, null, null);
    }

    @Override
    public Holder<Biome> getNoiseBiome(int quartX, int quartY, int quartZ) {
        ChunkAccess chunk = this.getChunk(QuartPos.toSection(quartX), QuartPos.toSection(quartZ), ChunkStatus.BIOMES, false);
        if (chunk != null) return chunk.getNoiseBiome(quartX, quartY, quartZ);
        for (int[] step : lsp_fixes$STEPS) {
            int x = quartX + step[0], z = quartZ + step[1];
            ChunkAccess near = this.getChunk(QuartPos.toSection(x), QuartPos.toSection(z), ChunkStatus.BIOMES, false);
            if (near != null) return near.getNoiseBiome(x, quartY, z);
        }
        return this.getUncachedNoiseBiome(quartX, quartY, quartZ);
    }
}
