// GENERATED by enchanting/build.mjs from enchanting/enchanting.mjs. Hardness tomes: enchanted books, tier I at
// the crafting table (nothing that needs iron), the rest by mechanical crafting; applied to a pickaxe in an
// anvil (startup_scripts/enchanting.js checks the Mining level).

ServerEvents.recipes((event) => {
  event.shaped(Item.of('minecraft:enchanted_book[minecraft:stored_enchantments={levels:{"lemursaucepacket:hardness":1}}]'), ["ACA","CBC","ACA"], {"A":"minecraft:andesite","C":"minecraft:copper_ingot","B":"minecraft:book"}).id('lemursaucepacket:enchanting/hardness_tome_1')
  event.recipes.create.mechanical_crafting(Item.of('minecraft:enchanted_book[minecraft:stored_enchantments={levels:{"lemursaucepacket:hardness":2}}]'), ["ILI","LBL","ILI"], {"I":"create:iron_sheet","L":"minecraft:lapis_lazuli","B":"minecraft:book"}).id('lemursaucepacket:enchanting/hardness_tome_2')
  event.recipes.create.mechanical_crafting(Item.of('minecraft:enchanted_book[minecraft:stored_enchantments={levels:{"lemursaucepacket:hardness":3}}]'), ["GRG","RBR","GRG"], {"G":"create:golden_sheet","R":"minecraft:redstone","B":"minecraft:book"}).id('lemursaucepacket:enchanting/hardness_tome_3')
  event.recipes.create.mechanical_crafting(Item.of('minecraft:enchanted_book[minecraft:stored_enchantments={levels:{"lemursaucepacket:hardness":4}}]'), ["DPD","SBS","DPD"], {"D":"minecraft:diamond","P":"create:precision_mechanism","S":"create:iron_sheet","B":"minecraft:book"}).id('lemursaucepacket:enchanting/hardness_tome_4')
  event.recipes.create.mechanical_crafting(Item.of('minecraft:enchanted_book[minecraft:stored_enchantments={levels:{"lemursaucepacket:hardness":5}}]'), ["SDS","DBD","SDS"], {"S":"create:sturdy_sheet","D":"minecraft:diamond","B":"minecraft:book"}).id('lemursaucepacket:enchanting/hardness_tome_5')
})
