// GENERATED by gear/build.mjs. Loot-only gear in chests, and the Prospector's Pickaxe smelting what it mines.

LootJS.modifiers((event) => {
  event.addTableModifier('minecraft:chests/nether_bridge').randomChance(0.12).addLoot('lemursaucepacket:ember_crown')
  event.addTableModifier('minecraft:chests/bastion_treasure').randomChance(0.12).addLoot('lemursaucepacket:ember_crown')
  event.addTableModifier('minecraft:chests/pillager_outpost').randomChance(0.06).addLoot('lemursaucepacket:stormcallers_sabre')
  event.addTableModifier(/^dungeons_arise:chests\/.*/).randomChance(0.06).addLoot('lemursaucepacket:stormcallers_sabre')
  event.addTableModifier(/^dungeons_arise:chests\/.*/).randomChance(0.25).addLoot(Item.of('lemursaucepacket:duelists_pattern', 1))
  event.addTableModifier('minecraft:chests/stronghold_library').randomChance(0.25).addLoot(Item.of('lemursaucepacket:duelists_pattern', 1))
  event.addTableModifier('minecraft:chests/ancient_city').randomChance(0.25).addLoot(Item.of('lemursaucepacket:duelists_pattern', 1))
  event.addBlockModifier(['#c:ores', 'minecraft:ancient_debris']).matchMainHand('lemursaucepacket:prospectors_pickaxe')
    .replaceLoot('minecraft:raw_iron', 'minecraft:iron_ingot')
    .replaceLoot('minecraft:raw_copper', 'minecraft:copper_ingot')
    .replaceLoot('minecraft:raw_gold', 'minecraft:gold_ingot')
    .replaceLoot('create:raw_zinc', 'create:zinc_ingot')
    .replaceLoot('minecraft:ancient_debris', 'minecraft:netherite_scrap')
})
