// LemurSaucePacket: the parts of the RuneScape-style skills that Project MMO has no setting for.
// The skills themselves (levels, XP, perks, item requirements) are generated by skills/build.mjs, and the
// critical-hit system (Strength/Ranged crit chance, plus gear bonuses) lives in gear.js.
//
// Project MMO ships a "builtin/default" datapack with requirements for its own skills (e.g. combat 60 for
// diamond swords). This pack uses its own skills instead, so that datapack is switched off, once per world.

ServerEvents.loaded((event) => {
  if (event.server.getPackRepository().getSelectedIds().contains('builtin/default')) {
    console.info('[LemurSaucePacket] switching off Project MMO\'s builtin/default datapack')
    event.server.runCommandSilent('datapack disable "builtin/default"')
  }
})
