// LemurSaucePacket: the parts of the RuneScape-style skills that Project MMO has no setting for.
// The skills themselves (levels, XP, perks, item requirements) are generated by skills/build.mjs.
//
// - Strength is the chance of a melee critical hit, Ranged the chance of a ranged one: 0.3% per level
//   (15% at 50, about 30% at 99), each for 1.5x damage.
// - Project MMO ships a "builtin/default" datapack with requirements for its own skills (e.g. combat 60 for
//   diamond swords). This pack uses its own skills instead, so that datapack is switched off, once per world.

const PMMO = Java.loadClass('harmonised.pmmo.api.APIUtils')
const Projectile = Java.loadClass('net.minecraft.world.entity.projectile.Projectile')
const CRIT_CHANCE_PER_LEVEL = 0.003
const CRIT_MULTIPLIER = 1.5

ServerEvents.loaded((event) => {
  if (event.server.getPackRepository().getSelectedIds().contains('builtin/default')) {
    console.info('[LemurSaucePacket] switching off Project MMO\'s builtin/default datapack')
    event.server.runCommandSilent('datapack disable "builtin/default"')
  }
})

// KubeJS names DamageSource's getEntity/getDirectEntity/getMsgId getActual/getImmediate/getType, and adds
// getPlayer (the player behind the damage, or null). This runs for every hit in the world, so a failure is
// logged once instead of on every hit.
let critErrorLogged = false
EntityEvents.beforeHurt((event) => {
  try {
    let source = event.getSource()
    let player = source.getPlayer()
    if (player == null) return
    let skill = null
    if (String(source.getType()) === 'player') skill = 'strength' // a melee hit
    else if (source.getImmediate() instanceof Projectile) skill = 'ranged' // arrows, tridents, rockets...
    if (skill == null) return
    if (Math.random() >= PMMO.getLevel(skill, player) * CRIT_CHANCE_PER_LEVEL) return
    event.setDamage(event.getDamage() * CRIT_MULTIPLIER)
    let target = event.getEntity()
    let x = target.getX()
    let y = target.getY() + target.getBbHeight() * 0.6
    let z = target.getZ()
    event.server.runCommandSilent(`particle minecraft:crit ${x} ${y} ${z} 0.3 0.3 0.3 0.4 18 force`)
    event.server.runCommandSilent(`playsound minecraft:entity.player.attack.crit player @a ${x} ${y} ${z} 1 1.1`)
  } catch (e) {
    if (!critErrorLogged) console.error(`[LemurSaucePacket] skill crit error (later ones not logged): ${e}`)
    critErrorLogged = true
  }
})
