// The wiki atlas's words (wiki/render.mjs uses them with wiki/atlas.json): nicer names for mods and structures, how
// structures with many variants fold into one card, the biome pages' titles, and short notes on biomes and creatures.
// The data (climate, what grows, what spawns, what generates) always comes from the game; these only add what the data
// can't say. Keep notes short and true: if unsure, leave a biome out and its card shows the data alone.

/** Mods whose metadata has no good display name. */
export const MOD_NAMES = {
  minecraft: 'Vanilla',
  nova_structures: 'Dungeons and Taverns',
  towns_and_towers: 'Towns and Towers',
  create_ltab: 'Create: Let The Adventure Begin',
  friendsandfoes: 'Friends & Foes',
  iceandfire: 'Ice and Fire',
  totw_modded: 'Towers of the Wild',
  regions_unexplored: 'Regions Unexplored',
  structory_towers: 'Structory: Towers',
  create_structures_arise: 'Create: Structures Arise'
}

/** The Overworld's biome pages: one per category (wiki/atlas.mjs sorts every biome into one). */
export const CATEGORY_PAGES = {
  forests: { title: 'Forests and taigas', short: 'Forests', file: 'biomes-forests.md' },
  plains: { title: 'Plains, meadows and fields', short: 'Plains', file: 'biomes-plains.md' },
  snowy: { title: 'Snowy and frozen lands', short: 'Snowy lands', file: 'biomes-snowy.md' },
  mountains: { title: 'Mountains, peaks and highlands', short: 'Mountains', file: 'biomes-mountains.md' },
  deserts: { title: 'Deserts, badlands and canyons', short: 'Deserts', file: 'biomes-deserts.md' },
  jungles: { title: 'Jungles and rainforests', short: 'Jungles', file: 'biomes-jungles.md' },
  savannas: { title: 'Savannas, steppes and shrublands', short: 'Savannas', file: 'biomes-savannas.md' },
  wetlands: { title: 'Swamps and wetlands', short: 'Wetlands', file: 'biomes-wetlands.md' },
  oceans: { title: 'Oceans, rivers and coasts', short: 'Coasts', file: 'biomes-oceans.md' },
  caves: { title: 'Caves and the deep', short: 'Caves', file: 'biomes-caves.md' }
}

/** Structures that come in many variants: one card each, listing its kinds. Regexes match the id's path. */
export const STRUCTURE_GROUPS = {
  minecraft: {
    village: { name: 'Villages', match: /^village_/ },
    ruined_portal: { name: 'Ruined portals', match: /^ruined_portal/ },
    ocean_ruin: { name: 'Ocean ruins', match: /^ocean_ruin_/ },
    shipwreck: { name: 'Shipwrecks', match: /^shipwreck/ },
    mineshaft: { name: 'Mineshafts', match: /^mineshaft/ }
  },
  towns_and_towers: {
    village: { name: 'Villages (Towns and Towers)', match: /(^|\/)village_|wandering_trader_camp/ },
    pillager_outpost: { name: 'Pillager outposts (Towns and Towers)', match: /(^|\/)pillager_outpost_/ }
  },
  bettermineshafts: { mineshaft: { name: 'Better mineshafts', match: /^mineshaft_/ } },
  betterdungeons: { dungeon: { name: 'Better dungeons', match: /^(skeleton|small|spider|zombie)_dungeon$/ } },
  betterwitchhuts: { witch: { name: 'Witch huts', match: /^witch_/ } },
  nova_structures: {
    firewatch: { name: 'Firewatch towers', match: /^firewatch_tower_/ },
    skeleton_tower: { name: 'Nether skeleton towers', match: /^nether_skeleton_tower_/ },
    skeleton_camp: { name: 'Nether skeleton camps', match: /^skeleton_camp_/ },
    remnant: { name: 'Remnants (ruined settlements)', match: /^remnant_/ },
    shrine: { name: 'Combat shrines', match: /^shrine_combat_tier_/ },
    tavern: { name: 'Taverns', match: /^tavern_/ }
  },
  terralith: {
    mage_tower: { name: 'Mage towers', match: /^mage_tower/ },
    rubble: { name: 'Rubble', match: /^rubble_/ }
  },
  totw_modded: { tower: { name: 'Towers of the Wild', match: /^(badlands|derelict|derelict_grass|desert|ice|jungle|ocean|ocean_warm|regular)$/ } },
  iceandfire: {
    cave: { name: 'Dragon caves', match: /_dragon_cave$/ },
    roost: { name: 'Dragon roosts', match: /_dragon_roost$/ }
  },
  piglinproliferation: { camp: { name: 'Piglin traveller camps', match: /^traveler_/ } },
  create_ltab: { dungeon: { name: 'Dungeons (Let The Adventure Begin)', match: /^dungeon_/ } },
  dungeons_arise: { heavenly: { name: 'Heavenly sky fortresses', match: /^heavenly_/ } },
  structory: {
    outcast: { name: 'Outcast villagers', match: /^outcast_villager_/ },
    taiga_ruin: { name: 'Taiga ruins', match: /^taiga_ruin_/ }
  }
}

/** Structure ids that make poor names. */
export const STRUCTURE_NAMES = {
  'totw_modded:nether': 'Nether tower',
  'totw_modded:end': 'End tower',
  'create_structures_arise:createairdrop': 'Air drop',
  'create_structures_arise:createcontainer': 'Shipping container',
  'create_structures_arise:createcushercrane': 'Crusher crane',
  'create_structures_arise:createfluidtank': 'Fluid tank',
  'create_structures_arise:createhouse': 'Create house',
  'create_structures_arise:createlittleman': 'Little man',
  'create_structures_arise:createlosttrainstation': 'Lost train station',
  'create_structures_arise:createminiskyvillage': 'Mini sky village',
  'create_structures_arise:createmonsterroom': 'Monster room',
  'create_structures_arise:createoldruine': 'Old ruin',
  'create_structures_arise:createpickaxestatue': 'Pickaxe statue',
  'create_structures_arise:create_copper_statue': 'Copper statue',
  'create_structures_arise:create_dungeon_base': 'Dungeon base',
  'create_structures_arise:create_ruined_castle': 'Ruined castle',
  'create_structures_arise:create_bastion': 'Brass bastion',
  'create_structures_arise:darkcastle': 'Dark castle',
  'create_structures_arise:deadlordshouse': "Dead lord's house",
  'create_structures_arise:minetrain': 'Mine train',
  'create_structures_arise:obsidiantemple': 'Obsidian temple',
  'create_structures_arise:pillagersteampunkairship': 'Pillager airship',
  'create_structures_arise:towerofochrum': 'Tower of Ochrum',
  'create_ltab:not__junos_house': "Juno's house",
  'nullscape:rift': 'The Rift',
  'minecraft:mansion': 'Woodland mansion',
  'minecraft:monument': 'Ocean monument',
  'minecraft:fortress': 'Nether fortress',
  'minecraft:bastion_remnant': 'Bastion remnant',
  'minecraft:desert_pyramid': 'Desert pyramid',
  'minecraft:jungle_pyramid': 'Jungle temple',
  'minecraft:swamp_hut': 'Swamp hut'
}

/**
 * One line about a biome, shown on its card. Vanilla biomes as players know them, and the modded ones whose look is
 * well known. A biome without a note shows its data alone.
 */
export const BIOME_NOTES = {
  // ---- vanilla
  'minecraft:plains': 'Open grass with scattered oaks and flowers: easy building land, villages and horses.',
  'minecraft:sunflower_plains': 'Plains full of sunflowers, which always face east: a compass in flower form.',
  'minecraft:meadow': 'High grassy slopes below the peaks, bright with flowers and bee nests.',
  'minecraft:forest': 'Mixed oak and birch woods: wood, apples and wolves close to hand.',
  'minecraft:flower_forest': 'A forest carpeted in every flower, the best place to farm dyes and honey.',
  'minecraft:birch_forest': 'Pale birch woods, light enough to see through.',
  'minecraft:old_growth_birch_forest': 'Birches two or three times their usual height.',
  'minecraft:dark_forest': 'A thick dark-oak canopy that keeps the floor dark enough for monsters at noon. Woodland mansions hide here.',
  'minecraft:taiga': 'Spruce woods with ferns and sweet berry bushes; wolves and foxes.',
  'minecraft:old_growth_pine_taiga': 'Giant spruces, mossy boulders and podzol: the wood is big here.',
  'minecraft:old_growth_spruce_taiga': 'Huge spruce trunks two blocks across.',
  'minecraft:snowy_taiga': 'Snowed-in spruce woods; foxes are white here.',
  'minecraft:cherry_grove': 'Pink cherry blossom on the mountainsides.',
  'minecraft:grove': 'Snowy spruce slopes below the peaks; powder snow lies in drifts.',
  'minecraft:snowy_plains': 'Flat snow with a few spruces: igloos and strays.',
  'minecraft:ice_spikes': 'Towers of packed ice standing out of the snow.',
  'minecraft:snowy_slopes': 'Steep snow and powder snow on the way up to the peaks.',
  'minecraft:frozen_peaks': 'Ice and packed ice at the top of the world.',
  'minecraft:jagged_peaks': 'Sharp snowy summits, the highest ground there is.',
  'minecraft:stony_peaks': 'Bare stone and calcite peaks, warm enough for no snow.',
  'minecraft:windswept_hills': 'Steep grassy hills and cliffs, with emerald ore in the stone.',
  'minecraft:windswept_gravelly_hills': 'Windswept hills stripped down to gravel.',
  'minecraft:windswept_forest': 'Windswept hills under spruce and oak.',
  'minecraft:windswept_savanna': 'Savanna thrown into cliffs and spires.',
  'minecraft:desert': 'Sand, cacti and dead bushes; desert temples, wells and villages. No rain.',
  'minecraft:badlands': 'Banded terracotta mesas; gold ore runs high here.',
  'minecraft:eroded_badlands': 'Terracotta worn into hoodoo spires.',
  'minecraft:wooded_badlands': 'Badlands plateaus topped with oak groves.',
  'minecraft:savanna': 'Dry grass under flat-topped acacias; horses, llamas and villages.',
  'minecraft:savanna_plateau': 'Raised savanna tablelands.',
  'minecraft:jungle': 'Towering jungle trees, vines, cocoa and melons; parrots, ocelots and jungle temples.',
  'minecraft:sparse_jungle': 'The jungle thinned out at its edges.',
  'minecraft:bamboo_jungle': 'Bamboo thickets where pandas live.',
  'minecraft:swamp': 'Shallow murky water, lily pads and vine-hung oaks; slimes come out at night and witches have huts here.',
  'minecraft:mangrove_swamp': 'Mangrove roots over mud and water; frogs live here.',
  'minecraft:mushroom_fields': 'Mycelium and giant mushrooms; mooshrooms, and no hostile mobs spawn on the surface.',
  'minecraft:beach': 'Sand between land and sea; turtles nest here.',
  'minecraft:snowy_beach': 'A beach under snow.',
  'minecraft:stony_shore': 'Stone where the cliffs meet the sea.',
  'minecraft:river': 'Water running between biomes: squid and salmon.',
  'minecraft:frozen_river': 'A river frozen over.',
  'minecraft:ocean': 'Open sea with shipwrecks and ruins.',
  'minecraft:deep_ocean': 'Deep water: ocean monuments and drowned.',
  'minecraft:warm_ocean': 'Shallow warm sea over sand, with coral reefs, tropical fish and pufferfish.',
  'minecraft:lukewarm_ocean': 'Warm water with kelp and tropical fish.',
  'minecraft:cold_ocean': 'Cold water over gravel; salmon swim here.',
  'minecraft:frozen_ocean': 'Pack ice and icebergs; polar bears on the floes.',
  'minecraft:deep_frozen_ocean': 'Deep icy water under the bergs.',
  'minecraft:deep_lukewarm_ocean': 'Deep warm water.',
  'minecraft:deep_cold_ocean': 'Deep cold water.',
  'minecraft:lush_caves': 'Moss, azaleas, glow berries and axolotls, under azalea trees on the surface.',
  'minecraft:dripstone_caves': 'Stalactites and stalagmites of dripstone; copper ore is plentiful.',
  'minecraft:deep_dark': 'Sculk-covered caves deep down. Quiet: the Warden hears everything, and ancient cities wait here.',
  'minecraft:nether_wastes': 'Netherrack, lava seas and glowstone: the Nether as it always was.',
  'minecraft:crimson_forest': 'Red fungus trees and weeping vines; hoglins and piglins.',
  'minecraft:warped_forest': 'Blue-green fungus trees; endermen, and nothing much else hostile.',
  'minecraft:soul_sand_valley': 'Soul sand and fossils; skeletons and ghasts, and blue soul fire.',
  'minecraft:basalt_deltas': 'Basalt pillars, blackstone and magma cubes: hard going.',
  'minecraft:the_end': 'The dragon’s island.',
  'minecraft:end_highlands': 'The outer islands’ high ground: end cities and chorus trees.',
  'minecraft:end_midlands': 'The outer islands’ slopes.',
  'minecraft:end_barrens': 'The outer islands’ edges.',
  'minecraft:small_end_islands': 'Little floating islands between the big ones.',

  // ---- Terralith
  'terralith:bryce_canyon': 'Red sandstone hoodoos and canyons, like the real Bryce Canyon.',
  'terralith:painted_mountains': 'Mountains striped in coloured terracotta.',
  'terralith:yellowstone': 'Hot springs and geysers among big spruces, like the real Yellowstone.',
  'terralith:yosemite_cliffs': 'Sheer granite walls above the valley floor.',
  'terralith:yosemite_lowlands': 'The valley floor below granite cliffs, with tall spruces.',
  'terralith:sakura_grove': 'Cherry blossom woods with bamboo and boulders.',
  'terralith:sakura_valley': 'A valley of cherry blossom.',
  'terralith:lavender_forest': 'Purple-leaved woods over fields of lavender.',
  'terralith:lavender_valley': 'Lavender meadows in a sheltered valley.',
  'terralith:moonlight_grove': 'Blue flowers and amethyst under the trees.',
  'terralith:moonlight_valley': 'A valley of blue flowers.',
  'terralith:skylands_spring': 'Islands floating in the sky, in spring colours.',
  'terralith:skylands_summer': 'Islands floating in the sky, in summer green.',
  'terralith:skylands_autumn': 'Islands floating in the sky, in autumn colours.',
  'terralith:skylands_winter': 'Snowy islands floating in the sky.',
  'terralith:desert_oasis': 'Water and greenery in the middle of the desert.',
  'terralith:red_oasis': 'An oasis among red sands.',
  'terralith:desert_spires': 'Tall sandstone spires over the dunes.',
  'terralith:desert_canyon': 'Canyons cut deep into the desert.',
  'terralith:lush_desert': 'A desert with a surprising amount growing in it.',
  'terralith:caldera': 'A volcano’s crater, flooded into a lake.',
  'terralith:volcanic_crater': 'A volcano’s mouth, with lava inside.',
  'terralith:volcanic_peaks': 'Basalt and blackstone peaks with lava at the top.',
  'terralith:basalt_cliffs': 'Dark basalt cliffs by the sea.',
  'terralith:granite_cliffs': 'Pink granite cliffs by the sea.',
  'terralith:white_cliffs': 'White calcite cliffs with moss and small trees.',
  'terralith:glacial_chasm': 'A deep chasm of snow, blue ice and icicles.',
  'terralith:ice_marsh': 'A marsh frozen solid.',
  'terralith:orchid_swamp': 'A swamp bright with blue orchids.',
  'terralith:amethyst_canyon': 'A canyon with amethyst crystals in its walls.',
  'terralith:amethyst_rainforest': 'A rainforest where amethyst grows out of the ground.',
  'terralith:cloud_forest': 'Misty high-altitude woods.',
  'terralith:tropical_jungle': 'Dense tropical jungle.',
  'terralith:jungle_mountains': 'Jungle climbing up mountainsides.',
  'terralith:rocky_jungle': 'Jungle broken up by rocky outcrops.',
  'terralith:siberian_taiga': 'Cold spruce taiga that goes on for miles.',
  'terralith:siberian_grove': 'Snowy spruce groves of the far north.',
  'terralith:shield': 'Rocky woods and lakes on old bedrock, like the Canadian Shield.',
  'terralith:shield_clearing': 'A clearing in the shield woods.',
  'terralith:snowy_shield': 'The shield under snow.',
  'terralith:birch_taiga': 'Taiga mixed with birch.',
  'terralith:snowy_maple_forest': 'Maple woods under snow.',
  'terralith:snowy_cherry_grove': 'Cherry blossom under snow.',
  'terralith:wintry_forest': 'Snowbound woods.',
  'terralith:wintry_lowlands': 'Snowy lowlands between the forests.',
  'terralith:alpine_highlands': 'High alpine grass below the peaks.',
  'terralith:alpine_grove': 'Spruce groves high in the mountains.',
  'terralith:emerald_peaks': 'Snowy peaks with emerald geodes in the rock.',
  'terralith:rocky_mountains': 'Big rocky mountains with scattered spruces.',
  'terralith:scarlet_mountains': 'Snowy mountains streaked with crimson red.',
  'terralith:haze_mountain': 'A misty mountain of tuff, small lakes and emerald ore.',
  'terralith:stony_spires': 'Stone spires standing out of the land.',
  'terralith:windswept_spires': 'Tall spires scoured by the wind.',
  'terralith:frozen_cliffs': 'Icy cliffs over frozen water.',
  'terralith:forested_highlands': 'Highlands under forest.',
  'terralith:highlands': 'Rolling high ground.',
  'terralith:temperate_highlands': 'Mild, green highlands.',
  'terralith:arid_highlands': 'Dry, sparse highlands.',
  'terralith:blooming_plateau': 'A plateau covered in flowers.',
  'terralith:blooming_valley': 'A valley covered in flowers.',
  'terralith:valley_clearing': 'Open grass in a valley between woods.',
  'terralith:lush_valley': 'A green, well-watered valley.',
  'terralith:steppe': 'Dry grassland as far as the eye can see.',
  'terralith:mountain_steppe': 'Steppe grass climbing into the hills.',
  'terralith:shrubland': 'Low bushes over grass.',
  'terralith:hot_shrubland': 'Dry, warm shrubland.',
  'terralith:cold_shrubland': 'Shrubs in the cold.',
  'terralith:rocky_shrubland': 'Shrubs among rocks.',
  'terralith:brushland': 'Dry brush and grass.',
  'terralith:ashen_savanna': 'Grey savanna with baobabs and cone-shaped trees.',
  'terralith:fractured_savanna': 'Savanna split by cliffs and ravines.',
  'terralith:savanna_badlands': 'Where the savanna turns into badlands.',
  'terralith:savanna_slopes': 'Savanna on the hillsides.',
  'terralith:white_mesa': 'Mesas of white terracotta.',
  'terralith:warped_mesa': 'Mesas striped in blue, green and purple terracotta.',
  'terralith:snowy_badlands': 'Badlands terracotta under snow.',
  'terralith:sandstone_valley': 'A valley walled in sandstone.',
  'terralith:gravel_desert': 'A desert of gravel instead of sand.',
  'terralith:gravel_beach': 'A beach of gravel.',
  'terralith:warm_river': 'A warm-water river.',
  'terralith:mirage_isles': 'Islands of enchanted trees and giant mushrooms.',
  'terralith:cave/fungal_caves': 'Giant mushrooms underground.',
  'terralith:cave/frostfire_caves': 'Ice and magma side by side underground.',
  'terralith:cave/thermal_caves': 'Hot caves of basalt and magma.',
  'terralith:cave/underground_jungle': 'Jungle plants growing underground.',
  'terralith:cave/infested_caves': 'Caves of infested stone: silverfish everywhere.',
  'terralith:cave/ice_caves': 'Caves of ice.',
  'terralith:cave/desert_caves': 'Sandstone caves under the desert.',
  'terralith:cave/mantle_caves': 'The deepest caves, near the bottom of the world.',
  'terralith:cave/deep_caves': 'Deep, open caves.',
  'terralith:cave/andesite_caves': 'Caves of andesite.',
  'terralith:cave/diorite_caves': 'Caves of diorite.',
  'terralith:cave/granite_caves': 'Caves of granite.',
  'terralith:cave/tuff_caves': 'Caves of tuff.',

  // ---- Regions Unexplored
  'regions_unexplored:redwoods': 'Towering redwood trees over ferns and salmonberry bushes.',
  'regions_unexplored:sparse_redwoods': 'Redwoods spread thinly over open ground.',
  'regions_unexplored:baobab_savanna': 'Savanna with huge baobab trees.',
  'regions_unexplored:bayou': 'Swampy water under cypress trees.',
  'regions_unexplored:eucalyptus_forest': 'Pale-trunked eucalyptus woods.',
  'regions_unexplored:willow_forest': 'Willows hanging over the water.',
  'regions_unexplored:maple_forest': 'Maple woods in autumn red.',
  'regions_unexplored:autumnal_maple_forest': 'Maple woods in full autumn colour.',
  'regions_unexplored:joshua_desert': 'A desert of Joshua trees.',
  'regions_unexplored:saguaro_desert': 'A desert of tall saguaro cacti.',
  'regions_unexplored:outback': 'Red, dry land under a big sky.',
  'regions_unexplored:poppy_fields': 'Fields red with poppies.',
  'regions_unexplored:flower_fields': 'Fields of every flower.',
  'regions_unexplored:pumpkin_fields': 'Fields of pumpkins.',
  'regions_unexplored:barley_fields': 'Golden barley fields.',
  'regions_unexplored:clover_plains': 'Plains covered in clover.',
  'regions_unexplored:orchard': 'Fruit trees in rows.',
  'regions_unexplored:prairie': 'Tall grass prairie.',
  'regions_unexplored:silver_birch_forest': 'Silver birch woods.',
  'regions_unexplored:alpha_grove': 'Trees and grass the way Minecraft looked in its alpha days.',
  'regions_unexplored:chalk_cliffs': 'White chalk cliffs over the sea.',
  'regions_unexplored:fen': 'Boggy grassland.',
  'regions_unexplored:marsh': 'Reeds and shallow water.',
  'regions_unexplored:bamboo_forest': 'A forest of bamboo.',
  'regions_unexplored:rainforest': 'Tall, wet rainforest.',
  'regions_unexplored:prismachasm': 'A cave of prismoss and hanging prismarite crystals.',
  'regions_unexplored:redstone_caves': 'Caves of redstone ore, redstone stalactites and glowing redstone buds.',
  'regions_unexplored:bioshroom_caves': 'Caves of glowing bioshroom trees.',
  'regions_unexplored:scorching_caves': 'Hot caves full of magma.',
  'regions_unexplored:glistering_meadow': 'A Nether meadow of glowing glister plants.',
  'regions_unexplored:infernal_holt': 'A burning Nether woodland of brimwood.',
  'regions_unexplored:mycotoxic_undergrowth': 'Poisonous Nether fungus thickets.',
  'regions_unexplored:redstone_abyss': 'Redstone-lit depths in the Nether.',
  'regions_unexplored:blackstone_basin': 'A basin of blackstone in the Nether.',

  // ---- Nullscape (the End)
  'nullscape:void_barrens': 'Bare, broken islands over the void.',
  'nullscape:crystal_peaks': 'Spires of purpur crystal out in the End.',
  'nullscape:shadowlands': 'Dark, jagged End islands.'
}

/** One line about a creature, shown on its card. */
export const CREATURE_NOTES = {
  'naturalist:bear': 'Neutral until you get close to its cubs. Loves honey and sweet berries.',
  'naturalist:black_bear': 'A smaller bear of the woods; neutral, but protective.',
  'naturalist:deer': 'Skittish: it bolts when you come near.',
  'naturalist:elephant': 'Huge and peaceful, unless you attack it.',
  'naturalist:giraffe': 'Tall and peaceful.',
  'naturalist:lion': 'Hunts in prides; it will hunt you too.',
  'naturalist:zebra': 'Can be tamed and ridden like a horse.',
  'naturalist:rhino': 'Charges if provoked.',
  'naturalist:hippo': 'Lives in rivers and lakes; dangerous if you get too close.',
  'naturalist:alligator': 'Lurks in swamp water and bites.',
  'naturalist:boar': 'Charges if provoked.',
  'naturalist:snake': 'A grass snake: keep your distance.',
  'naturalist:rattlesnake': 'Rattles a warning first.',
  'naturalist:coral_snake': 'Brightly banded and venomous.',
  'naturalist:butterfly': 'Pollinates crops. Catch one in a bottle.',
  'naturalist:firefly': 'Glows at night over grass and water.',
  'naturalist:snail': 'Slow. Leaves a slime trail.',
  'naturalist:shark': 'Hunts in deep water.',
  'naturalist:whale': 'Huge and gentle, out at sea.',
  'friendsandfoes:glare': 'Lives in lush caves and floats toward dark spots, where monsters could spawn.',
  'friendsandfoes:mauler': 'A desert predator that hides in the sand.',
  'friendsandfoes:rascal': 'Plays hide-and-seek in mineshafts. Find it three times for a prize.',
  'friendsandfoes:moobloom': 'A flowery cow: shear it for buttercups.',
  'friendsandfoes:crab': 'Waves its claws on the beach. Its claw gives a longer reach.',
  'friendsandfoes:iceologer': 'An illager that drops chunks of ice on you.',
  'friendsandfoes:illusioner': 'An illager that blinds you and splits into copies.',
  'minecraft:warden': 'Blind, but it hears and smells everything. Best avoided.',
  'minecraft:axolotl': 'Fights fish and drowned for you; plays dead to heal.',
  'minecraft:panda': 'Lives in bamboo jungles. Each has a personality.',
  'minecraft:sniffer': 'Hatches from an egg found in warm ocean ruins; sniffs out ancient seeds.',
  'minecraft:camel': 'Rideable by two, and tall enough to keep you out of a zombie’s reach.',
  'minecraft:armadillo': 'Rolls up when scared; brush it for scutes to make wolf armour.'
}
