/**
 * Skill gates for the pack's modded items and blocks (2026-10-08): everything with real gameplay value gets the skill
 * and level its usefulness calls for, beside the vanilla anchors in unlocks.mjs (iron gear Smithing 15, diamond gear
 * Crafting 30, ender chests Crafting 50, netherite Smithing 50, shulker boxes Crafting 65, beacons Crafting 75...).
 * Decoration, building blocks, plain materials, ingots and everyday food stay free; creative and technical items too.
 *
 * kind: what the level is for, and what enforces it (skills/build.mjs and unlocks.mjs read this list):
 *   craft  making it (crafting grid, smithing table, cooking pot, Create's blueprint): joins CRAFT, enforced by lsp_fixes.
 *          machine: true = a Create-style machine milestone (listed with the Create machines).
 *   chop   breaking its logs: joins CHOP (Project MMO BREAK).
 *   brew   using it as a brewing ingredient: joins BREW.
 *   hold   hitting with it: Project MMO WEAPON, and Weakness while held without the level.
 *   use    mining or right-clicking with it: Project MMO TOOL / USE.
 *   wear   wearing it (armour, curios, a held totem): Project MMO WEAR with Slowness; relics and totems are also stopped
 *          from working by lsp_fixes (SkillGates.wear), as the Climbing Boots are.
 *   place  placing the block: Project MMO PLACE.
 * Things only Create's mechanical crafters make get a use, hold or place gate instead of a craft gate (a making gate
 * would lock them for everyone, since no player is there to check).
 */
export const MODDED = [
  // Create
  { mod: 'create', kind: 'craft', skill: 'crafting', level: 20, what: 'Item vaults',
    items: ['create:item_vault'],
    why: 'A vault block holds 20 stacks and vaults join into one big inventory (up to 3x3 across): far past a chest. The shipping containers of Create Deco and the item silo of Create Connected are the same storage from their own recipes, so they share this gate.' },

  // Create: Connected
  { mod: 'create_connected', kind: 'craft', skill: 'crafting', level: 20, what: 'Item silos (a vertical item vault)',
    items: ['create_connected:item_silo'],
    why: 'Same storage as the item vault from its own recipe (iron sheet and barrel): it would skip the vault gate otherwise.' },

  // Create Deco
  { mod: 'createdeco', kind: 'craft', skill: 'crafting', level: 20, what: 'Shipping containers (dyed item vaults)',
    items: ['createdeco:black_shipping_container', 'createdeco:blue_shipping_container', 'createdeco:brown_shipping_container', 'createdeco:cyan_shipping_container', 'createdeco:gray_shipping_container', 'createdeco:green_shipping_container', 'createdeco:light_blue_shipping_container', 'createdeco:light_gray_shipping_container', 'createdeco:lime_shipping_container', 'createdeco:magenta_shipping_container', 'createdeco:orange_shipping_container', 'createdeco:pink_shipping_container', 'createdeco:purple_shipping_container', 'createdeco:red_shipping_container', 'createdeco:white_shipping_container', 'createdeco:yellow_shipping_container'],
    why: 'Create Deco makes these from a barrel, dye and an iron sheet, no vault needed, so they would skip the vault gate.' },

  // Create
  { mod: 'create', kind: 'craft', skill: 'crafting', level: 25, what: 'Mechanical arms',
    items: ['create:mechanical_arm'],
    why: 'Moves items between many inventories with no belts: the core of brass-age automation. Between the crossbow (20) and the mechanical crafter (30).' },
  { mod: 'create', kind: 'craft', skill: 'agility', level: 25, machine: true, what: 'Elevator pulleys',
    items: ['create:elevator_pulley'],
    why: 'A call-anywhere lift for players. Travel sits on Agility (elytra 30, train stations 35).' },
  { mod: 'create', kind: 'craft', skill: 'crafting', level: 45, what: 'Stock tickers, redstone requesters and factory gauges',
    items: ['create:stock_ticker', 'create:redstone_requester', 'create:factory_gauge'],
    why: 'Create 6\'s stock keeping: order anything in a vault network from one counter and let gauges keep production topped up. The pack\'s answer to AE2, so it comes after the enchanting table (40). Packagers, frogports and postboxes stay open.' },
  { mod: 'create', kind: 'use', skill: 'construction', level: 40, what: 'The wand of symmetry',
    items: ['create:wand_of_symmetry'],
    why: 'Mirrors every block you place across up to three planes. Made only by mechanical crafters, so the gate is on using it (a Project MMO USE rule, like the Builder\'s Wand).' },
  { mod: 'create', kind: 'hold', skill: 'attack', level: 40, what: 'The extendo grip',
    items: ['create:extendo_grip'],
    why: 'Greatly increases reach for whatever is in the main hand, swords included: a PvP edge. Made only by mechanical crafters, so it is a held-item rule (Project MMO WEAR with Weakness, as swords have). Attack 40 matches the Brass Duelist set.' },
  { mod: 'create', kind: 'craft', skill: 'crafting', level: 15, what: 'Toolboxes',
    items: ['create:black_toolbox', 'create:blue_toolbox', 'create:brown_toolbox', 'create:cyan_toolbox', 'create:gray_toolbox', 'create:green_toolbox', 'create:light_blue_toolbox', 'create:light_gray_toolbox', 'create:lime_toolbox', 'create:magenta_toolbox', 'create:orange_toolbox', 'create:pink_toolbox', 'create:purple_toolbox', 'create:red_toolbox', 'create:white_toolbox', 'create:yellow_toolbox'],
    why: 'A carried store that also hands tools to players nearby: an early convenience, gated like the shield (15).' },

  // Create Crafts & Additions
  { mod: 'createaddition', kind: 'craft', skill: 'crafting', level: 35, what: 'Capacitors (and so electric motors, tesla coils and accumulators)',
    items: ['createaddition:capacitor'],
    why: 'Electricity is a second power network: electric motors turn stored power back into rotation anywhere and tesla coils charge gear and shock mobs. Motors and coils come only from mechanical crafters, so the crafting-table capacitor every one of them needs carries the gate, the way the gear sets\' hand-made parts do. After the mechanical crafter (30), with the steam engine (Smithing 35).' },
  { mod: 'createaddition', kind: 'craft', skill: 'construction', level: 25, what: 'Barbed wire',
    items: ['createaddition:barbed_wire'],
    why: 'Hurts anything that walks through it: base defence on a PvP server with no land claims.' },

  // Create: Enchantment Industry
  { mod: 'create_enchantment_industry', kind: 'craft', skill: 'enchanting', level: 20, machine: true, what: 'Mechanical grindstones',
    items: ['create_enchantment_industry:mechanical_grindstone'],
    why: 'Automated disenchanting into liquid experience, the fuel for blaze enchanters, printers and new Hearts.' },
  { mod: 'create_enchantment_industry', kind: 'craft', skill: 'enchanting', level: 25, what: 'Experience lanterns',
    items: ['create_enchantment_industry:experience_lantern'],
    why: 'Absorbs experience from orbs and from players standing near it (on contraptions too): an XP bank and the end of an XP farm.' },
  { mod: 'create_enchantment_industry', kind: 'craft', skill: 'enchanting', level: 55, machine: true, what: 'Blaze forgers',
    items: ['create_enchantment_industry:blaze_forger'],
    why: 'An anvil with no repair cost that also applies and strips enchanting templates; fed Cake o\' Enchanting it super-enchants, merging conflicting enchantments and passing the vanilla caps. Past the printer (50). The pack\'s super_enchanting data map should hold the level caps; check it does here too.' },

  // Create Ore Excavation
  { mod: 'createoreexcavation', kind: 'craft', skill: 'mining', level: 35, what: 'Ore vein finders and the vein atlas',
    items: ['createoreexcavation:vein_finder', 'createoreexcavation:vein_atlas'],
    why: 'Prospecting for infinite veins. Drilling them already waits for Mining 50 (the drill head), so scouting comes a little earlier.' },

  // Create Slice & Dice
  { mod: 'sliceanddice', kind: 'craft', skill: 'cooking', level: 25, machine: true, what: 'Slicers',
    items: ['sliceanddice:slicer'],
    why: 'Automates the cutting board (slicing, butchery, bark) for Create kitchens: the next Cooking machine after the encased fan (20).' },
  { mod: 'sliceanddice', kind: 'craft', skill: 'farming', level: 30, machine: true, what: 'Sprinklers',
    items: ['sliceanddice:sprinkler', 'sliceanddice:floor_sprinkler'],
    why: 'Waters and fertilises an area so crops grow faster: the next Farming machine after the harvester and plough (15).' },

  // Offroad
  { mod: 'offroad', kind: 'craft', skill: 'mining', level: 40, machine: true, what: 'Borehead bearings and rock-cutting wheels',
    items: ['offroad:borehead_bearing', 'offroad:rockcutting_wheel'],
    why: 'A tunnel-boring head that cuts a wide face as it turns: the step past the drill (Mining 15). Like every machine it still only breaks up to Hardness II.' },

  // Create Aeronautics
  { mod: 'aeronautics', kind: 'place', skill: 'ranged', level: 30, what: 'Mounted potato cannons',
    items: ['aeronautics:mounted_potato_cannon'],
    why: 'A cannon on an airship. The handheld potato cannon needs Ranged 20; this one is mechanical-crafted, so the gate is on placing it (a Project MMO PLACE rule). The rest of Aeronautics stays open, as decided in 1.13.0.' },

  // Create Backpack Upgrades
  { mod: 'createbackpackupgrades', kind: 'craft', skill: 'crafting', level: 30, what: 'Pressing upgrades',
    items: ['createbackpackupgrades:pressing_upgrade'],
    why: 'A press in the backpack with no rotation. The owner asked for this mod by name, so confirm before gating it.' },
  { mod: 'createbackpackupgrades', kind: 'craft', skill: 'crafting', level: 35, what: 'Mixing upgrades',
    items: ['createbackpackupgrades:mixing_upgrade'],
    why: 'A mixer in the backpack with no rotation or basin. The owner asked for this mod by name, so confirm before gating it.' },

  // Sophisticated Backpacks
  { mod: 'sophisticatedbackpacks', kind: 'craft', skill: 'crafting', level: 10, what: 'Copper backpacks',
    items: ['sophisticatedbackpacks:copper_backpack'],
    why: 'The backpack ladder (leather stays free): each tier adds rows and upgrade slots.' },
  { mod: 'sophisticatedbackpacks', kind: 'craft', skill: 'crafting', level: 20, what: 'Iron backpacks',
    items: ['sophisticatedbackpacks:iron_backpack'],
    why: 'Backpack ladder, Andesite age.' },
  { mod: 'sophisticatedbackpacks', kind: 'craft', skill: 'crafting', level: 35, what: 'Gold backpacks',
    items: ['sophisticatedbackpacks:gold_backpack'],
    why: 'Backpack ladder, Brass age (brass casings in the recipe).' },
  { mod: 'sophisticatedbackpacks', kind: 'craft', skill: 'crafting', level: 50, what: 'Diamond backpacks',
    items: ['sophisticatedbackpacks:diamond_backpack'],
    why: 'Backpack ladder: with the ender chest (50).' },
  { mod: 'sophisticatedbackpacks', kind: 'craft', skill: 'smithing', level: 55, what: 'Netherite backpacks (smithing table)',
    items: ['sophisticatedbackpacks:netherite_backpack'],
    why: 'Backpack ladder: a netherite upgrade at the smithing table, after netherite gear (50).' },
  { mod: 'sophisticatedbackpacks', kind: 'craft', skill: 'crafting', level: 5, what: 'Pickup and filter upgrades',
    items: ['sophisticatedbackpacks:pickup_upgrade', 'sophisticatedbackpacks:filter_upgrade'],
    why: 'The first upgrades: small conveniences.' },
  { mod: 'sophisticatedbackpacks', kind: 'craft', skill: 'crafting', level: 15, what: 'Crafting upgrade and the starter stack upgrade',
    items: ['sophisticatedbackpacks:crafting_upgrade', 'sophisticatedbackpacks:stack_upgrade_starter_tier'],
    why: 'A crafting grid on your back (its results still obey the making gates) and the first stack bonus.' },
  { mod: 'sophisticatedbackpacks', kind: 'craft', skill: 'crafting', level: 20, what: 'Restock, deposit and refill upgrades',
    items: ['sophisticatedbackpacks:restock_upgrade', 'sophisticatedbackpacks:deposit_upgrade', 'sophisticatedbackpacks:refill_upgrade'],
    why: 'Empty into or fill from any container with a sneak-click, and keep a hotbar stack topped up.' },
  { mod: 'sophisticatedbackpacks', kind: 'craft', skill: 'crafting', level: 25, what: 'Void, tool swapper, tank and stack tier 1 upgrades',
    items: ['sophisticatedbackpacks:void_upgrade', 'sophisticatedbackpacks:tool_swapper_upgrade', 'sophisticatedbackpacks:tank_upgrade', 'sophisticatedbackpacks:stack_upgrade_tier_1', 'sophisticatedbackpacks:stack_upgrade_starter_tier_to_tier_1_conversion'],
    why: 'Mid-tier conveniences: delete junk, pick the right tool by itself, carry fluids, 2x stacks.' },
  { mod: 'sophisticatedbackpacks', kind: 'craft', skill: 'crafting', level: 30, what: 'Magnet, compacting and advanced pickup/filter upgrades',
    items: ['sophisticatedbackpacks:magnet_upgrade', 'sophisticatedbackpacks:compacting_upgrade', 'sophisticatedbackpacks:advanced_pickup_upgrade', 'sophisticatedbackpacks:advanced_filter_upgrade'],
    why: 'Pulls in drops from a distance and packs ores and crops into blocks as you go: big quality-of-life, Brass age.' },
  { mod: 'sophisticatedbackpacks', kind: 'craft', skill: 'crafting', level: 40, what: 'Advanced restock, deposit, refill, void and tool swapper upgrades, and stack tier 2',
    items: ['sophisticatedbackpacks:advanced_restock_upgrade', 'sophisticatedbackpacks:advanced_deposit_upgrade', 'sophisticatedbackpacks:advanced_refill_upgrade', 'sophisticatedbackpacks:advanced_void_upgrade', 'sophisticatedbackpacks:advanced_tool_swapper_upgrade', 'sophisticatedbackpacks:stack_upgrade_tier_2', 'sophisticatedbackpacks:stack_upgrade_starter_tier_to_tier_2_conversion', 'sophisticatedbackpacks:stack_upgrade_tier_1_to_tier_2_conversion'],
    why: 'The advanced versions add filters and remote picking; stack tier 2 (4x, the pack\'s cap) already needs brass casings.' },
  { mod: 'sophisticatedbackpacks', kind: 'craft', skill: 'crafting', level: 45, what: 'Advanced magnet and advanced compacting upgrades',
    items: ['sophisticatedbackpacks:advanced_magnet_upgrade', 'sophisticatedbackpacks:advanced_compacting_upgrade'],
    why: 'Wider pull with filters, and 3x3 compacting: the strongest everyday upgrades.' },
  { mod: 'sophisticatedbackpacks', kind: 'craft', skill: 'construction', level: 10, what: 'Stonecutter upgrade',
    items: ['sophisticatedbackpacks:stonecutter_upgrade'],
    why: 'A stonecutter on your back for builders.' },
  { mod: 'sophisticatedbackpacks', kind: 'craft', skill: 'smithing', level: 15, what: 'Smelting upgrade',
    items: ['sophisticatedbackpacks:smelting_upgrade'],
    why: 'A furnace on your back, with iron (15).' },
  { mod: 'sophisticatedbackpacks', kind: 'craft', skill: 'smithing', level: 25, what: 'Blasting and anvil upgrades',
    items: ['sophisticatedbackpacks:blasting_upgrade', 'sophisticatedbackpacks:anvil_upgrade'],
    why: 'A blast furnace and an anvil on your back; the anvil block itself is Smithing 20.' },
  { mod: 'sophisticatedbackpacks', kind: 'craft', skill: 'smithing', level: 40, what: 'Auto-smelting upgrade',
    items: ['sophisticatedbackpacks:auto_smelting_upgrade'],
    why: 'Smelts what you pick up with no menu at all. Note: with a pickup upgrade it can turn raw ores into free ingots past the Hardness use-gate (see the skips list).' },
  { mod: 'sophisticatedbackpacks', kind: 'craft', skill: 'smithing', level: 45, what: 'Auto-blasting upgrade',
    items: ['sophisticatedbackpacks:auto_blasting_upgrade'],
    why: 'The faster ore version of auto-smelting.' },
  { mod: 'sophisticatedbackpacks', kind: 'craft', skill: 'smithing', level: 50, what: 'Smithing upgrade',
    items: ['sophisticatedbackpacks:smithing_upgrade'],
    why: 'A smithing table on your back, for netherite upgrades in the field (netherite gear is Smithing 50). Check its result slot obeys the smithing gate.' },
  { mod: 'sophisticatedbackpacks', kind: 'craft', skill: 'cooking', level: 15, what: 'Smoking upgrade',
    items: ['sophisticatedbackpacks:smoking_upgrade'],
    why: 'A smoker on your back.' },
  { mod: 'sophisticatedbackpacks', kind: 'craft', skill: 'cooking', level: 25, what: 'Feeding upgrade',
    items: ['sophisticatedbackpacks:feeding_upgrade'],
    why: 'Eats for you from the backpack.' },
  { mod: 'sophisticatedbackpacks', kind: 'craft', skill: 'cooking', level: 40, what: 'Auto-smoking and advanced feeding upgrades',
    items: ['sophisticatedbackpacks:auto_smoking_upgrade', 'sophisticatedbackpacks:advanced_feeding_upgrade'],
    why: 'Cooks what you pick up; eats by your own rules.' },
  { mod: 'sophisticatedbackpacks', kind: 'craft', skill: 'brewing', level: 45, what: 'Alchemy upgrade',
    items: ['sophisticatedbackpacks:alchemy_upgrade'],
    why: 'Drinks potions and effect foods for you, the moment they help: strong in PvP.' },
  { mod: 'sophisticatedbackpacks', kind: 'craft', skill: 'brewing', level: 60, what: 'Advanced alchemy upgrade',
    items: ['sophisticatedbackpacks:advanced_alchemy_upgrade'],
    why: 'Alchemy with effect filters: with the stronger (glowstone) potions at Brewing 60.' },

  // Sophisticated Core
  { mod: 'sophisticatedcore', kind: 'craft', skill: 'crafting', level: 50, what: 'Ender linkers',
    items: ['sophisticatedcore:ender_linker'],
    why: 'Links storages into one shared group, ender-chest style: with the ender chest (50).' },

  // Waystones
  { mod: 'waystones', kind: 'place', skill: 'agility', level: 45, what: 'Waystones (all ten styles)',
    items: ['waystones:blackstone_waystone', 'waystones:deepslate_waystone', 'waystones:end_stone_waystone', 'waystones:mossy_waystone', 'waystones:mud_bricks_waystone', 'waystones:prismarine_waystone', 'waystones:purpur_waystone', 'waystones:red_nether_bricks_waystone', 'waystones:sandy_waystone', 'waystones:waystone'],
    why: 'Your own fast-travel point. They come only from mechanical crafters (and found ones are taken home), so the gate is on placing one; the city\'s global waystone stays usable for everyone.' },
  { mod: 'waystones', kind: 'place', skill: 'agility', level: 55, what: 'Sharestones',
    items: ['waystones:black_sharestone', 'waystones:blue_sharestone', 'waystones:brown_sharestone', 'waystones:cyan_sharestone', 'waystones:gray_sharestone', 'waystones:green_sharestone', 'waystones:light_blue_sharestone', 'waystones:light_gray_sharestone', 'waystones:lime_sharestone', 'waystones:magenta_sharestone', 'waystones:orange_sharestone', 'waystones:pink_sharestone', 'waystones:purple_sharestone', 'waystones:red_sharestone', 'waystones:yellow_sharestone'],
    why: 'Every sharestone of a colour links for everyone: a public network.' },
  { mod: 'waystones', kind: 'place', skill: 'agility', level: 35, what: 'Portstones',
    items: ['waystones:black_portstone', 'waystones:blue_portstone', 'waystones:brown_portstone', 'waystones:cyan_portstone', 'waystones:gray_portstone', 'waystones:green_portstone', 'waystones:light_blue_portstone', 'waystones:light_gray_portstone', 'waystones:lime_portstone', 'waystones:magenta_portstone', 'waystones:orange_portstone', 'waystones:pink_portstone', 'waystones:purple_portstone', 'waystones:red_portstone', 'waystones:white_portstone', 'waystones:yellow_portstone'],
    why: 'Send-only stones (nothing can warp to them): cheaper and weaker than a waystone.' },
  { mod: 'waystones', kind: 'place', skill: 'agility', level: 40, what: 'Warp plates',
    items: ['waystones:warp_plate'],
    why: 'Paired teleport pads.' },
  { mod: 'waystones', kind: 'use', skill: 'agility', level: 50, what: 'The warp stone',
    items: ['waystones:warp_stone'],
    why: 'A reusable teleport to any waystone you have found, from anywhere: the strongest travel item.' },
  { mod: 'waystones', kind: 'craft', skill: 'agility', level: 20, what: 'Return scrolls',
    items: ['waystones:return_scroll'],
    why: 'One-use teleports, made at a crafting table.' },
  { mod: 'waystones', kind: 'craft', skill: 'agility', level: 30, what: 'Warp scrolls',
    items: ['waystones:warp_scroll'],
    why: 'A one-use teleport to any waystone you have found.' },
  { mod: 'waystones', kind: 'craft', skill: 'agility', level: 40, what: 'Portal scrolls',
    items: ['waystones:portal_scroll'],
    why: 'The costliest scroll (an ender eye in the recipe).' },

  // Relics
  { mod: 'relics', kind: 'wear', skill: 'agility', level: 20, what: 'Springy Boot',
    items: ['relics:springy_boot'],
    why: 'Bounces you on landing and launches a crouch-jump.' },
  { mod: 'relics', kind: 'use', skill: 'agility', level: 25, what: 'Rider Flute',
    items: ['relics:rider_flute'],
    why: 'Stores a tamed mount and calls it back anywhere.' },
  { mod: 'relics', kind: 'wear', skill: 'agility', level: 30, what: 'Cut Glass Boot',
    items: ['relics:cut_glass_boot'],
    why: 'Walks on liquids and carries fluids like a bucket.' },
  { mod: 'relics', kind: 'wear', skill: 'agility', level: 35, what: 'Roller Skate',
    items: ['relics:roller_skate'],
    why: 'Builds up speed while you run.' },
  { mod: 'relics', kind: 'wear', skill: 'agility', level: 45, what: 'Kinetic Belt',
    items: ['relics:kinetic_belt'],
    why: 'Glides and keeps momentum (the Aeronaut set synergy, whose set needs Agility 40).' },
  { mod: 'relics', kind: 'use', skill: 'agility', level: 55, what: 'Chorus Staff',
    items: ['relics:chorus_staff'],
    why: 'Blink-teleports you forward on use: a PvP chase and escape tool.' },
  { mod: 'relics', kind: 'use', skill: 'agility', level: 60, what: 'Clot of Time',
    items: ['relics:clot_of_time'],
    why: 'Rewinds you along your recent path: an escape button (and the Prospector set synergy).' },
  { mod: 'relics', kind: 'wear', skill: 'agility', level: 65, what: 'Glitchy Mantle',
    items: ['relics:glitchy_mantle'],
    why: 'Attacks sometimes miss you, it leaves decoys, and you can walk on air.' },
  { mod: 'relics', kind: 'wear', skill: 'cooking', level: 20, what: 'Chef\'s Hat',
    items: ['relics:chef_hat'],
    why: 'Kills drop meatballs.' },
  { mod: 'relics', kind: 'wear', skill: 'enchanting', level: 25, what: 'Experience Disperser',
    items: ['relics:experience_disperser'],
    why: 'Shares relic experience between your relics.' },
  { mod: 'relics', kind: 'wear', skill: 'defence', level: 25, what: 'Piglin Mask',
    items: ['relics:piglin_mask'],
    why: 'Piglins leave you alone and barter more generously.' },
  { mod: 'relics', kind: 'wear', skill: 'defence', level: 45, what: 'Reflective Necklace',
    items: ['relics:reflective_necklace'],
    why: 'Stores part of the damage you take and throws it back.' },
  { mod: 'relics', kind: 'use', skill: 'defence', level: 50, what: 'Shield of Retaliation',
    items: ['relics:shield_of_retaliation'],
    why: 'A timed parry that blocks a hit outright.' },
  { mod: 'relics', kind: 'wear', skill: 'hitpoints', level: 35, what: 'Jellyfish Necklace',
    items: ['relics:jellyfish_necklace'],
    why: 'More max health and regeneration in water or rain, plus a shock.' },
  { mod: 'relics', kind: 'use', skill: 'hitpoints', level: 45, what: 'Sphere of Self-Sacrifice',
    items: ['relics:sphere_of_self_sacrifice'],
    why: 'Spend a third of your health to heal twice that back.' },
  { mod: 'relics', kind: 'wear', skill: 'hitpoints', level: 70, what: 'Ghostly Mantle',
    items: ['relics:ghostly_mantle'],
    why: 'Every so often it cancels a killing blow and makes you immortal for a few seconds: a free death save on a lifesteal server.' },
  { mod: 'relics', kind: 'wear', skill: 'strength', level: 30, what: 'Hunting Belt',
    items: ['relics:hunting_belt'],
    why: 'Your pets hit harder, and it adds charm slots. (Strength unlocks nothing yet.)' },
  { mod: 'relics', kind: 'wear', skill: 'strength', level: 55, what: 'Ring of the Seven Deadly Sins',
    items: ['relics:ring_of_the_seven_deadly_sins'],
    why: 'Big damage modifiers (height, wrath, envy) plus luck (the Brass Duelist synergy).' },
  { mod: 'relics', kind: 'wear', skill: 'strength', level: 60, what: 'Midnight Mantle',
    items: ['relics:midnight_mantle'],
    why: 'Moon-phase damage and attack speed, invisibility in the dark, falling stars.' },
  { mod: 'relics', kind: 'wear', skill: 'woodcutting', level: 50, what: 'Leafy Mantle',
    items: ['relics:leafy_mantle'],
    why: 'Walk through leaves, heal among them, and cheat death with nearby foliage: a forester\'s relic.' },

  // Ice and Fire CE
  { mod: 'iceandfire', kind: 'craft', skill: 'smithing', level: 20, what: 'Silver tools, weapons and armour',
    items: ['iceandfire:silver_sword', 'iceandfire:silver_pickaxe', 'iceandfire:silver_axe', 'iceandfire:silver_shovel', 'iceandfire:silver_hoe', 'iceandfire:armor_silver_metal_helmet', 'iceandfire:armor_silver_metal_chestplate', 'iceandfire:armor_silver_metal_leggings', 'iceandfire:armor_silver_metal_boots'],
    why: 'Silver is iron-plus (bonus against undead) and only comes from ice dragon dens: one step past iron (15).' },
  { mod: 'iceandfire', kind: 'hold', skill: 'attack', level: 20, what: 'Silver sword and axe (to hit with)',
    items: ['iceandfire:silver_sword', 'iceandfire:silver_axe'],
    why: 'Weapon tier between iron (15) and diamond (30), as vanilla tiers do (Project MMO WEAPON).' },
  { mod: 'iceandfire', kind: 'use', skill: 'mining', level: 20, what: 'Silver pickaxe and shovel',
    items: ['iceandfire:silver_pickaxe', 'iceandfire:silver_shovel'],
    why: 'Tool tier like the vanilla ones (Project MMO TOOL).' },
  { mod: 'iceandfire', kind: 'use', skill: 'woodcutting', level: 20, what: 'Silver axe (to chop with)',
    items: ['iceandfire:silver_axe'],
    why: 'Tool tier like the vanilla ones.' },
  { mod: 'iceandfire', kind: 'use', skill: 'farming', level: 20, what: 'Silver hoe',
    items: ['iceandfire:silver_hoe'],
    why: 'Tool tier like the vanilla ones.' },
  { mod: 'iceandfire', kind: 'wear', skill: 'defence', level: 20, what: 'Silver armour',
    items: ['iceandfire:armor_silver_metal_helmet', 'iceandfire:armor_silver_metal_chestplate', 'iceandfire:armor_silver_metal_leggings', 'iceandfire:armor_silver_metal_boots'],
    why: 'Armour tier between iron (15) and diamond (30).' },
  { mod: 'iceandfire', kind: 'hold', skill: 'attack', level: 5, what: 'Copper sword and axe (to hit with)',
    items: ['iceandfire:copper_sword', 'iceandfire:copper_axe'],
    why: 'Stone-tier weapons: the stone tier is 5.' },
  { mod: 'iceandfire', kind: 'use', skill: 'mining', level: 5, what: 'Copper pickaxe and shovel',
    items: ['iceandfire:copper_pickaxe', 'iceandfire:copper_shovel'],
    why: 'Stone-tier tools.' },
  { mod: 'iceandfire', kind: 'use', skill: 'woodcutting', level: 5, what: 'Copper axe (to chop with)',
    items: ['iceandfire:copper_axe'],
    why: 'Stone-tier tools.' },
  { mod: 'iceandfire', kind: 'use', skill: 'farming', level: 5, what: 'Copper hoe',
    items: ['iceandfire:copper_hoe'],
    why: 'Stone-tier tools.' },
  { mod: 'iceandfire', kind: 'wear', skill: 'defence', level: 5, what: 'Copper armour',
    items: ['iceandfire:armor_copper_metal_helmet', 'iceandfire:armor_copper_metal_chestplate', 'iceandfire:armor_copper_metal_leggings', 'iceandfire:armor_copper_metal_boots'],
    why: 'Between leather and chainmail, like Create\'s copper diving gear (Defence 5).' },
  { mod: 'iceandfire', kind: 'craft', skill: 'crafting', level: 55, what: 'Dragonbone tools, sword and bow',
    items: ['iceandfire:dragonbone_sword', 'iceandfire:dragonbone_pickaxe', 'iceandfire:dragonbone_axe', 'iceandfire:dragonbone_shovel', 'iceandfire:dragonbone_hoe', 'iceandfire:dragonbone_bow'],
    why: 'Dragon bones and wither bones: past diamond, before netherite-plus.' },
  { mod: 'iceandfire', kind: 'hold', skill: 'attack', level: 55, what: 'Dragonbone sword and axe (to hit with)',
    items: ['iceandfire:dragonbone_sword', 'iceandfire:dragonbone_axe'],
    why: 'Between netherite (50) and the elemental swords (60).' },
  { mod: 'iceandfire', kind: 'use', skill: 'mining', level: 55, what: 'Dragonbone pickaxe and shovel',
    items: ['iceandfire:dragonbone_pickaxe', 'iceandfire:dragonbone_shovel'],
    why: 'Past netherite (50).' },
  { mod: 'iceandfire', kind: 'use', skill: 'woodcutting', level: 55, what: 'Dragonbone axe (to chop with)',
    items: ['iceandfire:dragonbone_axe'],
    why: 'Past netherite (50).' },
  { mod: 'iceandfire', kind: 'use', skill: 'farming', level: 55, what: 'Dragonbone hoe',
    items: ['iceandfire:dragonbone_hoe'],
    why: 'Past netherite (50).' },
  { mod: 'iceandfire', kind: 'use', skill: 'ranged', level: 55, what: 'Dragonbone bow',
    items: ['iceandfire:dragonbone_bow'],
    why: 'A bow of dragon bone: past the trident (40).' },
  { mod: 'iceandfire', kind: 'craft', skill: 'crafting', level: 60, what: 'Flamed, iced and lightning dragonbone swords',
    items: ['iceandfire:dragonbone_sword_fire', 'iceandfire:dragonbone_sword_ice', 'iceandfire:dragonbone_sword_lightning'],
    why: 'A dragonbone sword soaked in dragon blood: burns, freezes or shocks on hit.' },
  { mod: 'iceandfire', kind: 'hold', skill: 'attack', level: 60, what: 'Elemental dragonbone swords (to hit with)',
    items: ['iceandfire:dragonbone_sword_fire', 'iceandfire:dragonbone_sword_ice', 'iceandfire:dragonbone_sword_lightning'],
    why: 'Elemental damage on top of dragonbone.' },
  { mod: 'iceandfire', kind: 'craft', skill: 'smithing', level: 80, what: 'Dragonsteel tools, weapons and armour',
    items: ['iceandfire:dragonsteel_fire_sword', 'iceandfire:dragonsteel_ice_sword', 'iceandfire:dragonsteel_lightning_sword', 'iceandfire:dragonsteel_fire_pickaxe', 'iceandfire:dragonsteel_ice_pickaxe', 'iceandfire:dragonsteel_lightning_pickaxe', 'iceandfire:dragonsteel_fire_axe', 'iceandfire:dragonsteel_ice_axe', 'iceandfire:dragonsteel_lightning_axe', 'iceandfire:dragonsteel_fire_shovel', 'iceandfire:dragonsteel_ice_shovel', 'iceandfire:dragonsteel_lightning_shovel', 'iceandfire:dragonsteel_fire_hoe', 'iceandfire:dragonsteel_ice_hoe', 'iceandfire:dragonsteel_lightning_hoe', 'iceandfire:dragonsteel_fire_helmet', 'iceandfire:dragonsteel_fire_chestplate', 'iceandfire:dragonsteel_fire_leggings', 'iceandfire:dragonsteel_fire_boots', 'iceandfire:dragonsteel_ice_helmet', 'iceandfire:dragonsteel_ice_chestplate', 'iceandfire:dragonsteel_ice_leggings', 'iceandfire:dragonsteel_ice_boots', 'iceandfire:dragonsteel_lightning_helmet', 'iceandfire:dragonsteel_lightning_chestplate', 'iceandfire:dragonsteel_lightning_leggings', 'iceandfire:dragonsteel_lightning_boots'],
    why: 'The best gear in the pack, from ingots forged in a dragon\'s breath. Ingots stay free (the rule for ingots); making the gear is master smithing, past the mace (70).' },
  { mod: 'iceandfire', kind: 'hold', skill: 'attack', level: 75, what: 'Dragonsteel swords and axes (to hit with)',
    items: ['iceandfire:dragonsteel_fire_sword', 'iceandfire:dragonsteel_ice_sword', 'iceandfire:dragonsteel_lightning_sword', 'iceandfire:dragonsteel_fire_axe', 'iceandfire:dragonsteel_ice_axe', 'iceandfire:dragonsteel_lightning_axe'],
    why: 'Stronger than netherite (50) and the Stormcaller\'s Sabre (50): only armour is quest-gated today, so the weapons have no gate at all.' },
  { mod: 'iceandfire', kind: 'use', skill: 'mining', level: 75, what: 'Dragonsteel pickaxes and shovels',
    items: ['iceandfire:dragonsteel_fire_pickaxe', 'iceandfire:dragonsteel_ice_pickaxe', 'iceandfire:dragonsteel_lightning_pickaxe', 'iceandfire:dragonsteel_fire_shovel', 'iceandfire:dragonsteel_ice_shovel', 'iceandfire:dragonsteel_lightning_shovel'],
    why: 'The fastest picks in the pack.' },
  { mod: 'iceandfire', kind: 'use', skill: 'woodcutting', level: 75, what: 'Dragonsteel axes (to chop with)',
    items: ['iceandfire:dragonsteel_fire_axe', 'iceandfire:dragonsteel_ice_axe', 'iceandfire:dragonsteel_lightning_axe'],
    why: 'The fastest axes in the pack.' },
  { mod: 'iceandfire', kind: 'use', skill: 'farming', level: 75, what: 'Dragonsteel hoes',
    items: ['iceandfire:dragonsteel_fire_hoe', 'iceandfire:dragonsteel_ice_hoe', 'iceandfire:dragonsteel_lightning_hoe'],
    why: 'The best hoes in the pack.' },
  { mod: 'iceandfire', kind: 'craft', skill: 'crafting', level: 60, what: 'Dragonscale armour (all twelve colours)',
    items: ['iceandfire:armor_amethyst_boots', 'iceandfire:armor_amethyst_chestplate', 'iceandfire:armor_amethyst_helmet', 'iceandfire:armor_amethyst_leggings', 'iceandfire:armor_black_boots', 'iceandfire:armor_black_chestplate', 'iceandfire:armor_black_helmet', 'iceandfire:armor_black_leggings', 'iceandfire:armor_blue_boots', 'iceandfire:armor_blue_chestplate', 'iceandfire:armor_blue_helmet', 'iceandfire:armor_blue_leggings', 'iceandfire:armor_bronze_boots', 'iceandfire:armor_bronze_chestplate', 'iceandfire:armor_bronze_helmet', 'iceandfire:armor_bronze_leggings', 'iceandfire:armor_copper_boots', 'iceandfire:armor_copper_chestplate', 'iceandfire:armor_copper_helmet', 'iceandfire:armor_copper_leggings', 'iceandfire:armor_electric_boots', 'iceandfire:armor_electric_chestplate', 'iceandfire:armor_electric_helmet', 'iceandfire:armor_electric_leggings', 'iceandfire:armor_gray_boots', 'iceandfire:armor_gray_chestplate', 'iceandfire:armor_gray_helmet', 'iceandfire:armor_gray_leggings', 'iceandfire:armor_green_boots', 'iceandfire:armor_green_chestplate', 'iceandfire:armor_green_helmet', 'iceandfire:armor_green_leggings', 'iceandfire:armor_red_boots', 'iceandfire:armor_red_chestplate', 'iceandfire:armor_red_helmet', 'iceandfire:armor_red_leggings', 'iceandfire:armor_sapphire_boots', 'iceandfire:armor_sapphire_chestplate', 'iceandfire:armor_sapphire_helmet', 'iceandfire:armor_sapphire_leggings', 'iceandfire:armor_silver_boots', 'iceandfire:armor_silver_chestplate', 'iceandfire:armor_silver_helmet', 'iceandfire:armor_silver_leggings', 'iceandfire:armor_white_boots', 'iceandfire:armor_white_chestplate', 'iceandfire:armor_white_helmet', 'iceandfire:armor_white_leggings'],
    why: 'Wearing it already needs Dragon Slayer I; making it from scales becomes a Crafting feat, with the end crystal (60). (Optional, not proposed: a Defence 60 wear level on top of the quest gate.)' },
  { mod: 'iceandfire', kind: 'craft', skill: 'smithing', level: 70, machine: true, what: 'Dragonforge cores',
    items: ['iceandfire:dragonforge_fire_core_disabled', 'iceandfire:dragonforge_ice_core_disabled', 'iceandfire:dragonforge_lightning_core_disabled'],
    why: 'The forge that turns iron into dragonsteel with a dragon\'s breath. It runs with no player (dragonsteel is an ingot), so the gate is on building it, as with Create\'s machines.' },
  { mod: 'iceandfire', kind: 'use', skill: 'farming', level: 70, what: 'Dragon eggs (placing one to hatch it)',
    items: ['iceandfire:dragonegg_amethyst', 'iceandfire:dragonegg_black', 'iceandfire:dragonegg_blue', 'iceandfire:dragonegg_bronze', 'iceandfire:dragonegg_copper', 'iceandfire:dragonegg_electric', 'iceandfire:dragonegg_gray', 'iceandfire:dragonegg_green', 'iceandfire:dragonegg_red', 'iceandfire:dragonegg_sapphire', 'iceandfire:dragonegg_silver', 'iceandfire:dragonegg_white'],
    why: 'A dragon is the strongest mount, pet and forge fuel in the pack. Raising one is master husbandry; the egg can still be carried, traded and kept (a Project MMO USE rule on placing it).' },
  { mod: 'iceandfire', kind: 'craft', skill: 'crafting', level: 65, what: 'Summoning crystals',
    items: ['iceandfire:summoning_crystal_fire', 'iceandfire:summoning_crystal_ice', 'iceandfire:summoning_crystal_lightning'],
    why: 'Store your dragon and call it to you anywhere.' },
  { mod: 'iceandfire', kind: 'craft', skill: 'crafting', level: 45, what: 'Dragon horns',
    items: ['iceandfire:dragon_horn'],
    why: 'Carries a tamed dragon as an item.' },
  { mod: 'iceandfire', kind: 'craft', skill: 'crafting', level: 45, what: 'Dragon seekers',
    items: ['iceandfire:dragon_seeker'],
    why: 'Points at the nearest dragon: hunting roosts for scales and bones.' },
  { mod: 'iceandfire', kind: 'craft', skill: 'smithing', level: 55, what: 'Epic dragon seekers (smithing, a nether star)',
    items: ['iceandfire:epic_dragon_seeker'],
    why: 'Longer range seeker.' },
  { mod: 'iceandfire', kind: 'craft', skill: 'smithing', level: 70, what: 'Legendary dragon seekers (dragonsteel)',
    items: ['iceandfire:legendary_dragon_seeker'],
    why: 'The best seeker.' },
  { mod: 'iceandfire', kind: 'craft', skill: 'cooking', level: 60, what: 'Rice with dragon meat (cooking pot)',
    items: ['iceandfire:cooked_rice_with_fire_dragon_meat', 'iceandfire:cooked_rice_with_ice_dragon_meat', 'iceandfire:cooked_rice_with_lightning_dragon_meat'],
    why: 'Exotic dishes from dragon flesh, past the feasts (50).' },

  // Farmer's Delight
  { mod: 'farmersdelight', kind: 'craft', skill: 'smithing', level: 10, what: 'Golden knives',
    items: ['farmersdelight:golden_knife'],
    why: 'The vanilla gold tier (Smithing 10).' },
  { mod: 'farmersdelight', kind: 'craft', skill: 'smithing', level: 15, what: 'Iron knives and the skillet',
    items: ['farmersdelight:iron_knife', 'farmersdelight:skillet'],
    why: 'The vanilla iron tier (Smithing 15).' },
  { mod: 'farmersdelight', kind: 'craft', skill: 'crafting', level: 30, what: 'Diamond knives',
    items: ['farmersdelight:diamond_knife'],
    why: 'The vanilla diamond tier (Crafting 30).' },
  { mod: 'farmersdelight', kind: 'craft', skill: 'smithing', level: 50, what: 'Netherite knives (smithing table)',
    items: ['farmersdelight:netherite_knife'],
    why: 'The vanilla netherite tier (Smithing 50).' },
  { mod: 'farmersdelight', kind: 'hold', skill: 'attack', level: 5, what: 'Flint knives (to hit with)',
    items: ['farmersdelight:flint_knife'],
    why: 'The stone tier (5).' },
  { mod: 'farmersdelight', kind: 'hold', skill: 'attack', level: 10, what: 'Golden knives (to hit with)',
    items: ['farmersdelight:golden_knife'],
    why: 'Knives are fast weapons with Backstabbing: same tiers as swords.' },
  { mod: 'farmersdelight', kind: 'hold', skill: 'attack', level: 15, what: 'Iron knives and the skillet (to hit with)',
    items: ['farmersdelight:iron_knife', 'farmersdelight:skillet'],
    why: 'Iron-tier weapons.' },
  { mod: 'farmersdelight', kind: 'hold', skill: 'attack', level: 30, what: 'Diamond knives (to hit with)',
    items: ['farmersdelight:diamond_knife'],
    why: 'Diamond-tier weapon.' },
  { mod: 'farmersdelight', kind: 'hold', skill: 'attack', level: 50, what: 'Netherite knives (to hit with)',
    items: ['farmersdelight:netherite_knife'],
    why: 'Netherite-tier weapon.' },
  { mod: 'farmersdelight', kind: 'craft', skill: 'cooking', level: 15, what: 'Melon juice',
    items: ['farmersdelight:melon_juice'],
    why: 'A drink with minor instant health.' },
  { mod: 'farmersdelight', kind: 'craft', skill: 'cooking', level: 25, what: 'Hot cocoa (cooking pot)',
    items: ['farmersdelight:hot_cocoa'],
    why: 'Clears a harmful effect: a cure in a mug.' },
  { mod: 'farmersdelight', kind: 'craft', skill: 'cooking', level: 50, what: 'Gleaming salad (a feast)',
    items: ['farmersdelight:gleaming_salad_block'],
    why: 'Farmer\'s Delight\'s newest feast, missing from the feasts gate (Cooking 50).' },
  { mod: 'farmersdelight', kind: 'craft', skill: 'farming', level: 20, what: 'Organic compost',
    items: ['farmersdelight:organic_compost'],
    why: 'Turns into rich soil, which speeds every crop planted on it.' },

  // Friends & Foes
  { mod: 'friendsandfoes', kind: 'wear', skill: 'defence', level: 40, what: 'the Totem of Freezing (held or in the charm slot)',
    items: ['friendsandfoes:totem_of_freezing'],
    why: 'Freezes everything near you when you drop below half health (works from the charm slot). Consider the vanilla Totem of Undying at Hitpoints 50 too.' },
  { mod: 'friendsandfoes', kind: 'wear', skill: 'agility', level: 45, what: 'the Totem of Illusion (held or in the charm slot)',
    items: ['friendsandfoes:totem_of_illusion'],
    why: 'Turns you invisible and leaves decoys when you drop below half health: an escape.' },
  { mod: 'friendsandfoes', kind: 'wear', skill: 'defence', level: 45, what: 'the Wildfire Crown',
    items: ['friendsandfoes:wildfire_crown'],
    why: 'The Nether citadel boss\'s helmet: with the loot-only Ember Crown (40).' },
  { mod: 'friendsandfoes', kind: 'brew', skill: 'brewing', level: 45, what: 'Potion of Reaching (crab claw)',
    items: ['friendsandfoes:crab_claw'],
    why: 'Longer block reach. With Weakness, Harming and Invisibility (45).' },

  // Illager Invasion
  { mod: 'illagerinvasion', kind: 'craft', skill: 'enchanting', level: 65, what: 'Imbuing tables',
    items: ['illagerinvasion:imbuing_table'],
    why: 'Pushes an enchantment one level past its maximum: the only way past the caps besides the skill. Check it respects the Enchanting caps.' },
  { mod: 'illagerinvasion', kind: 'craft', skill: 'smithing', level: 45, what: 'Platinum sheets (trim material)',
    items: ['illagerinvasion:platinum_sheet'],
    why: 'Platinum trims carry effects (agility, endurance, featherweight, insight), so trimming becomes more than cosmetic; trim copying is Smithing 40.' },
  { mod: 'illagerinvasion', kind: 'craft', skill: 'crafting', level: 45, what: 'Horns of Sight',
    items: ['illagerinvasion:horn_of_sight'],
    why: 'Reveals the creatures around you: scouting.' },
  { mod: 'illagerinvasion', kind: 'use', skill: 'mining', level: 40, what: 'the Lost Candle',
    items: ['illagerinvasion:lost_candle'],
    why: 'Tells you which ores are nearby: prospecting. Loot-only, so the gate is on using it.' },
  { mod: 'illagerinvasion', kind: 'hold', skill: 'strength', level: 40, what: 'the Platinum Infused Hatchet',
    items: ['illagerinvasion:platinum_infused_hatchet'],
    why: 'A heavy illager weapon. (Strength unlocks nothing yet.)' },
  { mod: 'illagerinvasion', kind: 'brew', skill: 'brewing', level: 40, what: 'Potion of Berserking (goat horn)',
    items: ['minecraft:goat_horn'],
    why: 'Illager Invasion\'s potion, brewed from an awkward potion and a goat horn; with Regeneration (40).' },

  // Piglin Proliferation
  { mod: 'piglinproliferation', kind: 'hold', skill: 'defence', level: 45, what: 'Bucklers',
    items: ['piglinproliferation:buckler'],
    why: 'A shield with a charge: bash through, explode, and a guaranteed critical after.' },
  { mod: 'piglinproliferation', kind: 'craft', skill: 'brewing', level: 40, what: 'Alchemical fire pits (fire rings)',
    items: ['piglinproliferation:blackstone_fire_ring', 'piglinproliferation:blackstone_soul_fire_ring', 'piglinproliferation:deepslate_fire_ring', 'piglinproliferation:deepslate_soul_fire_ring', 'piglinproliferation:end_stone_fire_ring', 'piglinproliferation:end_stone_soul_fire_ring', 'piglinproliferation:netherrack_fire_ring', 'piglinproliferation:netherrack_soul_fire_ring', 'piglinproliferation:stone_fire_ring', 'piglinproliferation:stone_soul_fire_ring'],
    why: 'A campfire you infuse with a potion so it gives the effect to everyone nearby.' },

  // Vanilla Backport
  { mod: 'vanillabackport', kind: 'craft', skill: 'agility', level: 40, what: 'Harnesses (to ride a happy ghast)',
    items: ['minecraft:black_harness', 'minecraft:blue_harness', 'minecraft:brown_harness', 'minecraft:cyan_harness', 'minecraft:gray_harness', 'minecraft:green_harness', 'minecraft:light_blue_harness', 'minecraft:light_gray_harness', 'minecraft:lime_harness', 'minecraft:magenta_harness', 'minecraft:orange_harness', 'minecraft:pink_harness', 'minecraft:purple_harness', 'minecraft:red_harness', 'minecraft:white_harness', 'minecraft:yellow_harness'],
    why: 'A happy ghast is a flying mount for four, reachable in the Nether before the elytra (Agility 30 to wear); the harness is what lets you ride it.' },
  { mod: 'vanillabackport', kind: 'craft', skill: 'crafting', level: 10, what: 'Bundles',
    items: ['minecraft:black_bundle', 'minecraft:blue_bundle', 'minecraft:brown_bundle', 'minecraft:bundle', 'minecraft:cyan_bundle', 'minecraft:gray_bundle', 'minecraft:green_bundle', 'minecraft:light_blue_bundle', 'minecraft:light_gray_bundle', 'minecraft:lime_bundle', 'minecraft:magenta_bundle', 'minecraft:orange_bundle', 'minecraft:pink_bundle', 'minecraft:purple_bundle', 'minecraft:red_bundle', 'minecraft:white_bundle', 'minecraft:yellow_bundle'],
    why: 'Many kinds of item in one slot; Vanilla Backport turns their recipe on.' },
  { mod: 'vanillabackport', kind: 'chop', skill: 'woodcutting', level: 40, what: 'Pale oaks',
    items: ['minecraft:pale_oak_log', 'minecraft:pale_oak_wood', 'minecraft:stripped_pale_oak_log', 'minecraft:stripped_pale_oak_wood'],
    why: 'The creaking\'s eerie forest: with the dark oaks (35) of the CHOP ladder.' },

  // Regions Unexplored
  { mod: 'regions_unexplored', kind: 'chop', skill: 'woodcutting', level: 10, what: 'Pine trees',
    items: ['regions_unexplored:pine_log', 'regions_unexplored:pine_wood', 'regions_unexplored:stripped_pine_log', 'regions_unexplored:stripped_pine_wood'],
    why: 'Common taiga trees: a first step.' },
  { mod: 'regions_unexplored', kind: 'chop', skill: 'woodcutting', level: 15, what: 'Palms and giant bamboo',
    items: ['regions_unexplored:palm_log', 'regions_unexplored:palm_wood', 'regions_unexplored:stripped_palm_log', 'regions_unexplored:stripped_palm_wood', 'regions_unexplored:bamboo_log', 'regions_unexplored:stripped_bamboo_log'],
    why: 'Tropical trees, with jungle trees (15).' },
  { mod: 'regions_unexplored', kind: 'chop', skill: 'woodcutting', level: 20, what: 'Joshua trees and larches',
    items: ['regions_unexplored:joshua_log', 'regions_unexplored:joshua_wood', 'regions_unexplored:stripped_joshua_log', 'regions_unexplored:stripped_joshua_wood', 'regions_unexplored:larch_log', 'regions_unexplored:larch_wood', 'regions_unexplored:stripped_larch_log', 'regions_unexplored:stripped_larch_wood'],
    why: 'Desert and golden-taiga trees.' },
  { mod: 'regions_unexplored', kind: 'chop', skill: 'woodcutting', level: 25, what: 'Cypresses, ashen trees and bioshroom stems',
    items: ['regions_unexplored:cypress_log', 'regions_unexplored:cypress_wood', 'regions_unexplored:stripped_cypress_log', 'regions_unexplored:stripped_cypress_wood', 'regions_unexplored:ashen_log', 'regions_unexplored:ashen_wood', 'regions_unexplored:blue_bioshroom_stem', 'regions_unexplored:blue_bioshroom_hyphae', 'regions_unexplored:stripped_blue_bioshroom_stem', 'regions_unexplored:stripped_blue_bioshroom_hyphae', 'regions_unexplored:green_bioshroom_stem', 'regions_unexplored:green_bioshroom_hyphae', 'regions_unexplored:stripped_green_bioshroom_stem', 'regions_unexplored:stripped_green_bioshroom_hyphae', 'regions_unexplored:pink_bioshroom_stem', 'regions_unexplored:pink_bioshroom_hyphae', 'regions_unexplored:stripped_pink_bioshroom_stem', 'regions_unexplored:stripped_pink_bioshroom_hyphae', 'regions_unexplored:yellow_bioshroom_stem', 'regions_unexplored:yellow_bioshroom_hyphae', 'regions_unexplored:stripped_yellow_bioshroom_stem', 'regions_unexplored:stripped_yellow_bioshroom_hyphae'],
    why: 'Bayou, burnt-forest and cave trees.' },
  { mod: 'regions_unexplored', kind: 'chop', skill: 'woodcutting', level: 30, what: 'Willows',
    items: ['regions_unexplored:willow_log', 'regions_unexplored:willow_wood', 'regions_unexplored:stripped_willow_log', 'regions_unexplored:stripped_willow_wood'],
    why: 'RuneScape\'s willow is level 30.' },
  { mod: 'regions_unexplored', kind: 'chop', skill: 'woodcutting', level: 35, what: 'Eucalyptus',
    items: ['regions_unexplored:eucalyptus_log', 'regions_unexplored:eucalyptus_wood', 'regions_unexplored:stripped_eucalyptus_log', 'regions_unexplored:stripped_eucalyptus_wood'],
    why: 'With dark oak (35), like RuneScape\'s teak.' },
  { mod: 'regions_unexplored', kind: 'chop', skill: 'woodcutting', level: 40, what: 'Magnolias, wisterias and baobabs',
    items: ['regions_unexplored:magnolia_log', 'regions_unexplored:magnolia_wood', 'regions_unexplored:stripped_magnolia_log', 'regions_unexplored:stripped_magnolia_wood', 'regions_unexplored:wisteria_log', 'regions_unexplored:wisteria_wood', 'regions_unexplored:stripped_wisteria_log', 'regions_unexplored:stripped_wisteria_wood', 'regions_unexplored:baobab_log', 'regions_unexplored:baobab_wood', 'regions_unexplored:stripped_baobab_log', 'regions_unexplored:stripped_baobab_wood'],
    why: 'Flowering and savanna giants.' },
  { mod: 'regions_unexplored', kind: 'chop', skill: 'woodcutting', level: 45, what: 'Maples',
    items: ['regions_unexplored:maple_log', 'regions_unexplored:maple_wood', 'regions_unexplored:stripped_maple_log', 'regions_unexplored:stripped_maple_wood'],
    why: 'RuneScape\'s maple is level 45.' },
  { mod: 'regions_unexplored', kind: 'chop', skill: 'woodcutting', level: 50, what: 'Kapoks',
    items: ['regions_unexplored:kapok_log', 'regions_unexplored:kapok_wood', 'regions_unexplored:stripped_kapok_log', 'regions_unexplored:stripped_kapok_wood'],
    why: 'Rainforest giants, like RuneScape\'s mahogany (50).' },
  { mod: 'regions_unexplored', kind: 'chop', skill: 'woodcutting', level: 55, what: 'Socotras and blackwoods',
    items: ['regions_unexplored:socotra_log', 'regions_unexplored:socotra_wood', 'regions_unexplored:stripped_socotra_log', 'regions_unexplored:stripped_socotra_wood', 'regions_unexplored:blackwood_log', 'regions_unexplored:blackwood_wood', 'regions_unexplored:stripped_blackwood_log', 'regions_unexplored:stripped_blackwood_wood'],
    why: 'Rare dragon-blood trees and the dark blackwood taiga.' },
  { mod: 'regions_unexplored', kind: 'chop', skill: 'woodcutting', level: 65, what: 'Brimwood and cobalt (Nether)',
    items: ['regions_unexplored:brimwood_log', 'regions_unexplored:brimwood_wood', 'regions_unexplored:stripped_brimwood_log', 'regions_unexplored:stripped_brimwood_wood', 'regions_unexplored:cobalt_log', 'regions_unexplored:cobalt_wood', 'regions_unexplored:stripped_cobalt_log', 'regions_unexplored:stripped_cobalt_wood', 'regions_unexplored:brimwood_log_magma'],
    why: 'Nether trees past crimson and warped stems (60).' },
  { mod: 'regions_unexplored', kind: 'chop', skill: 'woodcutting', level: 70, what: 'Redwoods',
    items: ['regions_unexplored:redwood_log', 'regions_unexplored:redwood_wood', 'regions_unexplored:stripped_redwood_log', 'regions_unexplored:stripped_redwood_wood'],
    why: 'RuneScape\'s redwood is the top tree (90 there); these giants drop the most logs per tree.' },

  // Vanilla
  { mod: 'minecraft', kind: 'wear', skill: 'hitpoints', level: 50, what: 'Totems of undying (to be saved by one)',
    items: ['minecraft:totem_of_undying'],
    why: 'A second life on a PvP server with lifesteal: with the survival relics, Hitpoints 50. Holding one without the level slows you (Project MMO); lsp_fixes stops it saving you.' },
]
