// Writes the hiscores' definitions (hiscores/hiscores.mjs) for the server and the website:
//   pack/config/lemursaucepacket/hiscores.json   lsp_fixes' hiscores package: what to record, rank and upload
//   website/assets/hiscores-defs.json           play.limas.ca/hiscores: names, icons and order
//
//   node hiscores/build.mjs            (publish/publish.mjs runs it)

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { ACTIVITIES, BOSSES, COLLECTIONS, QUEST_POINTS, RECORD_EVERY, SKILLS, UPLOAD_EVERY, UPLOAD_URL } from './hiscores.mjs'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const write = (rel, value) => {
  const file = path.join(root, rel)
  mkdirSync(path.dirname(file), { recursive: true })
  writeFileSync(file, JSON.stringify(value, null, 2) + '\n')
}
const title = (id) => id.charAt(0).toUpperCase() + id.slice(1)

write('pack/config/lemursaucepacket/hiscores.json', {
  skills: SKILLS,
  questPoints: QUEST_POINTS.map(({ tag, points }) => ({ tag, points })),
  activities: ACTIVITIES.map(({ id, name, stat, divide }) => ({ id, name, ...(stat ? { stat } : {}), ...(divide ? { divide } : {}) })),
  bosses: BOSSES.map(({ id, name, counter, kills }) => ({ id, name, ...(counter ? { counter: true } : { kills }) })),
  collections: COLLECTIONS.map(({ id, name, match }) => ({ id, name, match })),
  recordEvery: RECORD_EVERY,
  uploadEvery: UPLOAD_EVERY,
  uploadUrl: UPLOAD_URL
})

// What the page draws: the skill icons are the in-game ones (website/assets/skills, from art/process.mjs).
write('website/assets/hiscores-defs.json', {
  overall: { id: 'overall', name: 'Overall', icon: '/assets/skills/total_level.webp' },
  skills: SKILLS.map((id) => ({ id, name: title(id), icon: `/assets/skills/${id}.webp` })),
  combat: { id: 'combat', name: 'Combat level', icon: '/assets/skills/attack.webp' },
  activities: ACTIVITIES.map(({ id, name }) => ({ id, name })),
  bosses: BOSSES.map(({ id, name, note }) => ({ id, name, ...(note ? { note } : {}) })),
  collections: COLLECTIONS.map(({ id, name }) => ({ id, name })),
  questPoints: QUEST_POINTS.reduce((sum, q) => sum + q.points, 0)
})

// The wiki's list of what's ranked (docs/hiscores.md, between its markers).
{
  const file = path.join(root, 'docs', 'hiscores.md')
  const START = '<!-- hiscores: generated by hiscores/build.mjs from hiscores/hiscores.mjs -->'
  const END = '<!-- /hiscores -->'
  const text = readFileSync(file, 'utf8')
  const a = text.indexOf(START)
  const b = text.indexOf(END)
  if (a < 0 || b < a) throw new Error('docs/hiscores.md has no hiscores markers')
  const totalPoints = QUEST_POINTS.reduce((sum, q) => sum + q.points, 0)
  const lines = [START, '']
  lines.push('### Skills', '', `Overall, each of the ${SKILLS.length} skills (${SKILLS.map(title).join(', ')}) and combat level.`, '')
  lines.push('### Activities', '', '| Table | What counts |', '|---|---|', ...ACTIVITIES.map((x) => `| ${x.name} | ${x.what}${x.id === 'quest_points' ? ` (${totalPoints} in all: ${QUEST_POINTS.map((q) => `${q.quest} ${q.points}`).join(', ')})` : ''} |`), '')
  lines.push('### Bosses', '', '| Table | What counts |', '|---|---|', ...BOSSES.map((x) => `| ${x.name} | ${x.what ?? 'Kills'} |`), '')
  lines.push('### Collections', '', 'Each counts the kinds you have had, out of how many there are.', '', '| Table | What counts |', '|---|---|', ...COLLECTIONS.map((x) => `| ${x.name} | ${x.what} |`), '')
  lines.push(END)
  writeFileSync(file, text.slice(0, a) + lines.join(String.fromCharCode(10)) + text.slice(b + END.length))
}

console.log(`hiscores: ${SKILLS.length} skills, ${ACTIVITIES.length} activities, ${BOSSES.length} bosses, ${COLLECTIONS.length} collections, ${QUEST_POINTS.reduce((s, q) => s + q.points, 0)} quest points`)
