// Types shared by the main process, preload bridge and renderer.

export type LoaderId = 'vanilla' | 'neoforge' | 'forge' | 'fabric' | 'quilt'

export interface NewsItem {
  title: string
  date?: string
  body: string
  url?: string
}

export interface FeedLink {
  label: string
  url: string
}

/**
 * launcher.json — the one file the launcher polls before every launch.
 * Generated by publish/publish.mjs and hosted next to the .mrpack.
 */
export interface LauncherFeed {
  schema: 1
  name: string
  description?: string
  server: { name?: string; address: string; port?: number }
  pack: {
    version: string
    /** Absolute URL, or relative to launcher.json. */
    url: string
    sha1: string
    size?: number
    minecraft?: string
    loader?: LoaderId
    loaderVersion?: string
    modCount?: number
  }
  /** Move jars that aren't part of the pack out of mods/ (default true). */
  strictMods?: boolean
  /** Optional mods (by Modrinth project id) that start switched off until a player turns them on. */
  optionalDefaultOff?: string[]
  /** The shader picker. Iris is always installed with shaders off; each preset is a shader pack it can switch to. */
  shaderPresets?: ShaderFeed
  recommendedMemoryMB?: number
  /** Extra JVM args the admin wants every client to use. */
  jvmArgs?: string[]
  /** Players on an older launcher are told to update. */
  minLauncherVersion?: string
  links?: FeedLink[]
  news?: NewsItem[]
}

export interface ShaderPreset {
  id: string
  name: string
  description: string
  /** The zip in shaderpacks/. */
  file: string
}

export interface ShaderFeed {
  /** The pack Iris has ready while shaders are off, so K in game turns this one on. */
  defaultPreset: string
  presets: ShaderPreset[]
}

/** What the game is set to use, from Iris's config (or the player's pick, until it is applied on Play). */
export interface ShaderState {
  /** A preset id, 'off', or null for a pack picked in game that isn't one of the presets. */
  active: string | null
  /** The shader pack file Iris has selected, if any. */
  pack: string | null
  /** The player picked this in the launcher; it is written into the game on the next Play. */
  pending: boolean
}

export type AfterLaunch = 'minimize' | 'close' | 'keep'

export interface Settings {
  memoryMB: number
  width: number
  height: number
  fullscreen: boolean
  afterLaunch: AfterLaunch
  autoJoin: boolean
  /** Empty string means "use the Java runtime the launcher manages". */
  javaPath: string
  jvmArgs: string
  /** The player's on/off choices for optional mods, keyed by Modrinth project id (or file path). */
  optionalChoices: Record<string, boolean>
  /** The shader preset last picked in Settings (a feed id or 'off'; '' = never picked). */
  shaderPreset: string
  /** The pick last written into the game's Iris config ('' = not yet). A pick is written once, so K and O in game
   *  keep working; picking again in the launcher writes again. */
  appliedShaderPreset: string
}

export interface AccountInfo {
  name: string
  uuid: string
  type: 'msa' | 'offline'
}

export type ProgressStage = 'auth' | 'feed' | 'pack' | 'mods' | 'minecraft' | 'java' | 'loader' | 'launch'

export interface ProgressInfo {
  stage: ProgressStage
  label: string
  detail?: string
  current?: number
  total?: number
  unit?: 'bytes' | 'files'
}

export type GameStatus =
  | { state: 'idle' }
  | { state: 'preparing' }
  | { state: 'running'; since: number }
  | { state: 'crashed'; code: number | null; crashReport?: string; tail: string[] }

export interface ServerStatus {
  online: boolean
  players?: { online: number; max: number; sample: string[] }
  motd?: string
  version?: string
  latencyMs?: number
  favicon?: string
  error?: string
  /** True when this PC runs the server itself, so the launcher joins it at localhost. */
  local?: boolean
}

export interface ModEntry {
  /** Stable id for optional-mod choices: Modrinth project id, or the file path for other sources. */
  key: string
  path: string
  fileName: string
  sha1: string
  size: number
  side: 'both' | 'client' | 'server'
  optional: boolean
  /** Whether an optional mod starts switched on (before the player chooses). */
  defaultEnabled: boolean
  enabled: boolean
  title?: string
  description?: string
  iconUrl?: string
  slug?: string
  versionNumber?: string
}

export interface PackSummary {
  name: string
  version: string
  minecraft: string
  loader: LoaderId
  loaderVersion?: string
  modCount: number
}

export interface BrandInfo {
  name: string
  shortName: string
  version: string
  dev: boolean
}

/** A Microsoft device code the player approves at microsoft.com/link during sign-in. */
export interface LoginCode {
  userCode: string
  /** The sign-in page with the code already filled in. */
  url: string
  expiresAt: number
}

export interface InitialState {
  brand: BrandInfo
  settings: Settings
  account: AccountInfo | null
  systemMemoryMB: number
  installed: PackSummary | null
  dataDir: string
}

export interface UpdateStatus {
  state: 'idle' | 'checking' | 'available' | 'downloading' | 'ready' | 'error' | 'disabled'
  version?: string
  percent?: number
  error?: string
}

export interface ToastMessage {
  kind: 'info' | 'warn' | 'error'
  text: string
}

export type FolderKind = 'game' | 'mods' | 'logs' | 'crash-reports' | 'screenshots' | 'data'

export interface LauncherApi {
  getInitialState(): Promise<InitialState>
  getFeed(force?: boolean): Promise<LauncherFeed | null>
  getServerStatus(): Promise<ServerStatus>
  getMods(): Promise<ModEntry[]>
  setOptionalMod(key: string, enabled: boolean): Promise<Settings>
  /** A shader preset id from the feed, or 'off'; written into the game on the next Play. */
  setShaderPreset(id: string): Promise<Settings>
  getShaderState(): Promise<ShaderState>
  updateSettings(patch: Partial<Settings>): Promise<Settings>
  login(): Promise<AccountInfo>
  cancelLogin(): Promise<void>
  loginOffline(name: string): Promise<AccountInfo>
  logout(): Promise<void>
  play(options?: { repair?: boolean }): Promise<void>
  cancel(): Promise<void>
  stopGame(): Promise<void>
  openFolder(kind: FolderKind): Promise<void>
  openExternal(url: string): Promise<void>
  installUpdate(): Promise<void>
  onProgress(cb: (p: ProgressInfo | null) => void): () => void
  onGameStatus(cb: (s: GameStatus) => void): () => void
  onUpdateStatus(cb: (s: UpdateStatus) => void): () => void
  onToast(cb: (t: ToastMessage) => void): () => void
  onAccount(cb: (a: AccountInfo | null) => void): () => void
  onLoginCode(cb: (c: LoginCode | null) => void): () => void
}
