// slug -> [group, short role] for the final mod list.
export const ROLES = {
  '3dskinlayers': ['Visuals', 'skins drawn in 3D'],
  'aeronautics-replay': ['Recording', 'ReForgedPlay support for Aeronautics ships'],
  ambientsounds: ['Visuals & sound', 'ambient biome sounds'],
  appleskin: ['Info', 'hunger/saturation on the HUD and food tooltips'],
  'architectury-api': ['Library', 'library'],
  autowalker: ['Controls', "auto walk on the ` key"],
  badoptimizations: ['Performance', 'client optimisations'],
  balm: ['Library', 'library'],
  'better-advanced-tooltips': ['Info', 'tags and components in F3+H tooltips'],
  'better-block-entities': ['Performance', 'faster block-entity rendering'],
  blueprint: ['Library', 'library (Woodworks)'],
  'bookshelf-lib': ['Library', 'library'],
  'chat-heads': ['Chat', 'player heads next to chat lines'],
  chunky: ['Server', 'world pre-generation (admin)'],
  'cloth-config': ['Library', 'config screens'],
  clumps: ['Performance', 'XP orbs clump together'],
  controlify: ['Controls', 'controller support (optional, off by default)'],
  controlling: ['Controls', 'search box and conflict view in Key Binds'],
  copycats: ['Create add-on', 'copycat blocks in many shapes'],
  'crash-assistant': ['Support', 'crash screen that reads the logs'],
  'create-aeronautics': ['Create add-on', 'airships, cars and planes (bundles Aeronautics, Simulated, Offroad)'],
  'create-backpack-upgrades': ['Create add-on', 'pressing and mixing backpack upgrades'],
  'create-brassworks-missions': ['Create add-on', 'weekly missions paying Coin Pouches'],
  'create-central-kitchen': ['Create add-on', "automates Farmer's Delight cooking"],
  'create-connected': ['Create add-on', 'extra kinetic, logistics and redstone parts'],
  'create-cyber-goggles': ['Create add-on', 'extra goggle info and controls (client)'],
  'create-deco': ['Create add-on', 'industrial decoration'],
  'create-dragons-plus': ['Create add-on', 'fluid hatch, dyeing and other conveniences'],
  'create-enchantment-industry': ['Create add-on', 'liquid XP, automated enchanting and book printing'],
  'create-jei-compat': ['Info', 'long sequenced-assembly recipes paged in JEI'],
  'create-let-the-adventure-begin': ['Structures', 'Create-themed structures'],
  'create-nowheel': ['Performance', 'Create rendering optimisation'],
  'create-ore-excavation': ['Create add-on', 'infinite ore veins drilled by machines'],
  'create-railways-navigator': ['Create add-on', 'train route planner and better displays'],
  'create-rustic-structures': ['Structures', 'Create-built structures'],
  'create-structures-arise': ['Structures', '28 Create structures'],
  create: ['Create', 'rotational machines, logistics, trains, contraptions'],
  createaddition: ['Create add-on', 'electricity (Crafts & Additions)'],
  creativecore: ['Library', 'library'],
  'creeper-overhaul': ['Mobs', 'a creeper per biome'],
  'cristel-lib': ['Library', 'library'],
  curios: ['Inventory', 'accessory slots (back, cape, relics)'],
  distanthorizons: ['Video', 'distant land beyond render distance'],
  dragonlib: ['Library', 'library (Railways Navigator)'],
  'drippy-loading-screen': ['Look', 'custom loading screen'],
  'dungeons-and-taverns': ['Structures', 'taverns, shrines, castles'],
  'dynamic-fps': ['Performance', 'lower FPS when unfocused'],
  'easy-npc-config-ui': ['NPCs', 'NPC editor (admins)'],
  'easy-npc-core': ['NPCs', 'the townsfolk and vendors'],
  'enchantment-descriptions': ['Info', 'what each enchantment does, on books'],
  'entity-model-features': ['Visuals', 'custom entity models (Fresh Animations)'],
  entityculling: ['Performance', 'skips hidden entities'],
  entitytexturefeatures: ['Visuals', 'entity textures (Fresh Animations)'],
  'every-compat': ['Building', 'every wood for furniture, Woodworks, cabinets'],
  fallingleavesforge: ['Visuals', 'falling leaf particles'],
  fallingtree: ['Tools', 'tree felling (the Lumber Axe only)'],
  'fancy-entity-renderer': ['Look', 'player model in menus'],
  fancymenu: ['Look', 'the title screen and ESC hub'],
  'farmers-delight': ['Food', 'cooking, crops, knives'],
  'ferrite-core': ['Performance', 'memory savings'],
  'first-person-model': ['Visuals', 'your body in first person (optional, off by default)'],
  'friends-and-foes-forge': ['Mobs', 'mob-vote mobs (copper golem, glare, moobloom...)'],
  'ftb-library-forge': ['Library', 'library (FTB)'],
  'ftb-quests-forge': ['Quests', 'the quest book'],
  'ftb-teams-forge': ['Social', 'teams sharing quest progress'],
  'fzzy-config': ['Library', 'library'],
  geckolib: ['Library', 'animation library'],
  'gravestone-mod': ['Death', 'graves (need Grave Essence here)'],
  'guard-villagers': ['Mobs', 'village guards'],
  'iceandfire-ce': ['Mobs', 'dragons only (no griefing)'],
  iceberg: ['Library', 'library'],
  'illager-invasion': ['Mobs', 'new illagers, items and structures'],
  immediatelyfast: ['Performance', 'faster HUD/text rendering'],
  'inventory-essentials': ['Inventory', 'ctrl-click and shift-drop tweaks'],
  'inventory-profiles-next': ['Inventory', 'sorting, move-all, auto refill'],
  iris: ['Video', 'shaders (off by default)'],
  ixeris: ['Performance', 'smoother input handling'],
  'jade-addons-forge': ['Info', 'more Jade info for mods'],
  jade: ['Info', 'what you look at: block, mob, machine'],
  'jei-worldgen': ['Info', 'ore heights and biomes in JEI'],
  jei: ['Info', 'recipes and uses'],
  jupiter: ['Library', 'config library'],
  'just-enough-effect-descriptions-jeed': ['Info', 'status effects in JEI'],
  'just-enough-professions-jep': ['Info', 'villager workstations in JEI'],
  'just-zoom': ['Controls', 'zoom (Z) and spyglass tweaks'],
  justenoughbreeding: ['Info', 'breeding foods in JEI'],
  konkrete: ['Library', 'library (FancyMenu)'],
  'kotlin-for-forge': ['Library', 'library'],
  'kubejs-create': ['Library', 'KubeJS Create recipes'],
  kubejs: ['Pack scripts', "runs the pack's scripts"],
  lambdynamiclights: ['Visuals', 'held and dropped light sources light the area'],
  'legendary-tooltips': ['Look', 'tooltip borders'],
  libipn: ['Library', 'library (Inventory Profiles Next)'],
  lithium: ['Performance', 'game logic optimisation'],
  lithostitched: ['Library', 'worldgen library'],
  lootjs: ['Pack scripts', 'loot tables from scripts'],
  lootr: ['Loot', 'per-player loot chests'],
  'lukis-grand-capitals': ['Structures', 'grand capitals (Lemurton)'],
  'macaws-bridges': ['Building', 'bridges'],
  'macaws-doors': ['Building', 'doors'],
  'macaws-fences-and-walls': ['Building', 'fences, walls, gates'],
  'macaws-furniture': ['Building', 'furniture with storage and seats'],
  'macaws-lights-and-lamps': ['Building', 'lamps and lights'],
  'macaws-paths-and-pavings': ['Building', 'paths and pavings'],
  'macaws-roofs': ['Building', 'roofs'],
  'macaws-stairs': ['Building', 'stairs, handrails, balconies'],
  'macaws-trapdoors': ['Building', 'trapdoors'],
  'macaws-windows': ['Building', 'windows, shutters, curtains, blinds'],
  melody: ['Library', 'music library (FancyMenu)'],
  modernfix: ['Performance', 'load time and memory'],
  moonlight: ['Library', 'library (Every Compat)'],
  moreculling: ['Performance', 'more block culling'],
  'mouse-tweaks': ['Inventory', 'drag and scroll item moving'],
  naturalist: ['Mobs', 'real-world animals, bug net'],
  netherportalfix: ['Travel', 'portals lead back where you came from'],
  'not-enough-animations': ['Visuals', 'first-person animations in third person'],
  nullscape: ['Worldgen', 'End terrain'],
  'packet-fixer': ['Performance', 'packet size fixes'],
  'particle-rain': ['Visuals', 'weather particles'],
  patchouli: ['Info', 'the in-game guide book'],
  'piglin-proliferation': ['Mobs', 'piglin variants, fire rings'],
  platform: ['Library', 'library'],
  prickle: ['Library', 'library'],
  'prism-lib': ['Library', 'library'],
  'project-mmo': ['Skills', 'the skills (Project MMO)'],
  'puzzles-lib': ['Library', 'library'],
  'reeses-sodium-options': ['Video', 'video settings screen'],
  'reforgedplay-mod': ['Recording', 'Replay Mod (recording off by default)'],
  'regions-unexplored': ['Worldgen', 'biomes and woods'],
  'relics-mod': ['Gear', 'relics with abilities'],
  'resourceful-config': ['Library', 'library'],
  'resourceful-lib': ['Library', 'library'],
  rhino: ['Library', 'JavaScript engine (KubeJS)'],
  rinku: ['Look', 'in-game browser (the Guide button)'],
  'sable-assembly-fix': ['Fix', 'closes an airship duplication bug'],
  'sable-reforgedplay-compat': ['Recording', 'records Sable sub-levels'],
  sable: ['Create add-on', 'physics for moving structures (Aeronautics)'],
  searchables: ['Library', 'search helpers (Controlling)'],
  'shatterbyte-lib': ['Library', 'library (Relics)'],
  'shoulder-surfing-reloaded': ['Controls', 'over-the-shoulder camera on F5'],
  shulkerboxtooltip: ['Inventory', 'shulker box contents in tooltips'],
  'simple-voice-chat': ['Chat', 'proximity voice chat'],
  'slice-and-dice': ['Create add-on', "Farmer's Delight cutting and cooking with Create"],
  'sodium-extra': ['Video', 'extra video toggles (FPS counter, fog, particles)'],
  'sodium-shadowy-path-blocks': ['Visuals', 'path-block lighting fix'],
  sodium: ['Performance', 'rendering engine'],
  'sophisticated-backpacks-create-integration': ['Inventory', 'backpacks on Create contraptions'],
  'sophisticated-backpacks': ['Inventory', 'backpacks with upgrades'],
  'sophisticated-core': ['Library', 'library (Sophisticated Backpacks)'],
  spark: ['Server', 'profiler (admin)'],
  sparsestructures: ['Worldgen', 'spreads structures out'],
  'structory-towers': ['Structures', 'biome towers'],
  structory: ['Structures', 'ruins, camps, manors'],
  'structure-layout-optimizer': ['Performance', 'faster structure generation'],
  'subtle-effects': ['Visuals', 'small particle details'],
  tectonic: ['Worldgen', 'terrain shape'],
  terralith: ['Worldgen', 'about 100 biomes'],
  'totw-modded': ['Structures', 'tall towers with a waystone on top'],
  'towns-and-towers': ['Structures', 'villages and outposts'],
  uranus: ['Library', 'library (Ice and Fire)'],
  vanillabackport: ['Vanilla+', 'newer vanilla features (happy ghast, pale garden...)'],
  'variants-and-ventures': ['Mobs', 'mob variants'],
  'vb-compat': ['Vanilla+', 'Vanilla Backport in modded biomes'],
  'visuality-forge': ['Visuals', 'small particles'],
  'wavey-capes': ['Visuals', 'capes that move'],
  'waystones-sable': ['Travel', 'waystones on airships'],
  waystones: ['Travel', 'waystones and warp items'],
  'when-dungeons-arise': ['Structures', 'big dungeons'],
  woodworks: ['Building', 'wood variants, sawmill'],
  'xaeros-minimap': ['Maps', 'minimap and waypoints (fair play)'],
  'xaeros-world-map': ['Maps', 'world map'],
  yacl: ['Library', 'config library'],
  'yungs-api': ['Library', "library (YUNG's)"],
  'yungs-better-desert-temples': ['Structures', 'desert temples'],
  'yungs-better-dungeons': ['Structures', 'dungeons'],
  'yungs-better-end-island': ['Structures', 'the dragon island'],
  'yungs-better-jungle-temples': ['Structures', 'jungle temples'],
  'yungs-better-mineshafts': ['Structures', 'mineshafts'],
  'yungs-better-nether-fortresses': ['Structures', 'nether fortresses'],
  'yungs-better-ocean-monuments': ['Structures', 'ocean monuments'],
  'yungs-better-strongholds': ['Structures', 'strongholds'],
  'yungs-better-witch-huts': ['Structures', 'witch huts'],
  'yungs-bridges': ['Structures', 'bridges over rivers'],
  'yungs-extras': ['Structures', 'small structures and wells']
}
