// The proposed gates, as data. `items` are ids or /regex/ strings matched against the pack's item list.
// kind: craft (making it: crafting grid, smithing table, cooking pot, blueprint), wear, hold, use, place,
//       chop (Project MMO BREAK on logs, the CHOP list), brew (a brewing ingredient, the BREW list).
// machine: true marks a Create-style machine milestone (the CRAFT list's `machine: true`).
// impact: 1-5, how much the gate changes play (used for the summary's top 20).

const colors = ['white', 'orange', 'magenta', 'light_blue', 'yellow', 'lime', 'pink', 'gray', 'light_gray', 'cyan', 'purple', 'blue', 'brown', 'green', 'red', 'black']
const ruWood = (...kinds) => kinds.flatMap((k) => [`regions_unexplored:${k}_log`, `regions_unexplored:${k}_wood`, `regions_unexplored:stripped_${k}_log`, `regions_unexplored:stripped_${k}_wood`])
const ruStem = (...kinds) => kinds.flatMap((k) => [`regions_unexplored:${k}_bioshroom_stem`, `regions_unexplored:${k}_bioshroom_hyphae`, `regions_unexplored:stripped_${k}_bioshroom_stem`, `regions_unexplored:stripped_${k}_bioshroom_hyphae`])
const iaf = (...ids) => ids.map((i) => `iceandfire:${i}`)
const sb = (...ids) => ids.map((i) => `sophisticatedbackpacks:${i}`)
const dsTools = (slot) => ['fire', 'ice', 'lightning'].map((e) => `iceandfire:dragonsteel_${e}_${slot}`)

export const PROPOSALS = [
  // ------------------------------------------------------------------ Create
  { mod: 'create', items: ['create:item_vault'], skill: 'crafting', level: 20, kind: 'craft', impact: 4, what: 'Item vaults', why: 'A vault block holds 20 stacks and vaults join into one big inventory (up to 3x3 across): far past a chest. The shipping containers of Create Deco and the item silo of Create Connected are the same storage from their own recipes, so they share this gate.' },
  { mod: 'create_connected', items: ['create_connected:item_silo'], skill: 'crafting', level: 20, kind: 'craft', impact: 2, what: 'Item silos (a vertical item vault)', why: 'Same storage as the item vault from its own recipe (iron sheet and barrel): it would skip the vault gate otherwise.' },
  { mod: 'createdeco', items: ['/^createdeco:.*_shipping_container$/'], skill: 'crafting', level: 20, kind: 'craft', impact: 2, what: 'Shipping containers (dyed item vaults)', why: 'Create Deco makes these from a barrel, dye and an iron sheet, no vault needed, so they would skip the vault gate.' },
  { mod: 'create', items: ['create:mechanical_arm'], skill: 'crafting', level: 25, kind: 'craft', impact: 3, what: 'Mechanical arms', why: 'Moves items between many inventories with no belts: the core of brass-age automation. Between the crossbow (20) and the mechanical crafter (30).' },
  { mod: 'create', items: ['create:elevator_pulley'], skill: 'agility', level: 25, kind: 'craft', machine: true, impact: 2, what: 'Elevator pulleys', why: 'A call-anywhere lift for players. Travel sits on Agility (elytra 30, train stations 35).' },
  { mod: 'create', items: ['create:stock_ticker', 'create:redstone_requester', 'create:factory_gauge'], skill: 'crafting', level: 45, kind: 'craft', impact: 4, what: 'Stock tickers, redstone requesters and factory gauges', why: "Create 6's stock keeping: order anything in a vault network from one counter and let gauges keep production topped up. The pack's answer to AE2, so it comes after the enchanting table (40). Packagers, frogports and postboxes stay open." },
  { mod: 'create', items: ['create:wand_of_symmetry'], skill: 'construction', level: 40, kind: 'use', impact: 2, what: 'The wand of symmetry', why: 'Mirrors every block you place across up to three planes. Made only by mechanical crafters, so the gate is on using it (a Project MMO USE rule, like the Builder\'s Wand).' },
  { mod: 'create', items: ['create:extendo_grip'], skill: 'attack', level: 40, kind: 'hold', impact: 3, what: 'The extendo grip', why: 'Greatly increases reach for whatever is in the main hand, swords included: a PvP edge. Made only by mechanical crafters, so it is a held-item rule (Project MMO WEAR with Weakness, as swords have). Attack 40 matches the Brass Duelist set.' },
  { mod: 'create', items: ['/^create:[a-z_]+_toolbox$/'], skill: 'crafting', level: 15, kind: 'craft', impact: 1, what: 'Toolboxes', why: 'A carried store that also hands tools to players nearby: an early convenience, gated like the shield (15).' },

  // ------------------------------------------------------------------ Create add-ons
  { mod: 'createaddition', items: ['createaddition:capacitor'], skill: 'crafting', level: 35, kind: 'craft', impact: 3, what: 'Capacitors (and so electric motors, tesla coils and accumulators)', why: 'Electricity is a second power network: electric motors turn stored power back into rotation anywhere and tesla coils charge gear and shock mobs. Motors and coils come only from mechanical crafters, so the crafting-table capacitor every one of them needs carries the gate, the way the gear sets\' hand-made parts do. After the mechanical crafter (30), with the steam engine (Smithing 35).' },
  { mod: 'createaddition', items: ['createaddition:barbed_wire'], skill: 'construction', level: 25, kind: 'craft', impact: 2, what: 'Barbed wire', why: 'Hurts anything that walks through it: base defence on a PvP server with no land claims.' },
  { mod: 'create_enchantment_industry', items: ['create_enchantment_industry:mechanical_grindstone'], skill: 'enchanting', level: 20, kind: 'craft', machine: true, impact: 2, what: 'Mechanical grindstones', why: 'Automated disenchanting into liquid experience, the fuel for blaze enchanters, printers and new Hearts.' },
  { mod: 'create_enchantment_industry', items: ['create_enchantment_industry:experience_lantern'], skill: 'enchanting', level: 25, kind: 'craft', impact: 1, what: 'Experience lanterns', why: 'Absorbs experience from orbs and from players standing near it (on contraptions too): an XP bank and the end of an XP farm.' },
  { mod: 'create_enchantment_industry', items: ['create_enchantment_industry:blaze_forger'], skill: 'enchanting', level: 55, kind: 'craft', machine: true, impact: 4, what: 'Blaze forgers', why: "An anvil with no repair cost that also applies and strips enchanting templates; fed Cake o' Enchanting it super-enchants, merging conflicting enchantments and passing the vanilla caps. Past the printer (50). The pack's super_enchanting data map should hold the level caps; check it does here too." },
  { mod: 'createoreexcavation', items: ['createoreexcavation:vein_finder', 'createoreexcavation:vein_atlas'], skill: 'mining', level: 35, kind: 'craft', impact: 2, what: 'Ore vein finders and the vein atlas', why: 'Prospecting for infinite veins. Drilling them already waits for Mining 50 (the drill head), so scouting comes a little earlier.' },
  { mod: 'sliceanddice', items: ['sliceanddice:slicer'], skill: 'cooking', level: 25, kind: 'craft', machine: true, impact: 2, what: 'Slicers', why: "Automates the cutting board (slicing, butchery, bark) for Create kitchens: the next Cooking machine after the encased fan (20)." },
  { mod: 'sliceanddice', items: ['sliceanddice:sprinkler', 'sliceanddice:floor_sprinkler'], skill: 'farming', level: 30, kind: 'craft', machine: true, impact: 2, what: 'Sprinklers', why: 'Waters and fertilises an area so crops grow faster: the next Farming machine after the harvester and plough (15).' },
  { mod: 'offroad', items: ['offroad:borehead_bearing', 'offroad:rockcutting_wheel'], skill: 'mining', level: 40, kind: 'craft', machine: true, impact: 2, what: 'Borehead bearings and rock-cutting wheels', why: 'A tunnel-boring head that cuts a wide face as it turns: the step past the drill (Mining 15). Like every machine it still only breaks up to Hardness II.' },
  { mod: 'aeronautics', items: ['aeronautics:mounted_potato_cannon'], skill: 'ranged', level: 30, kind: 'place', impact: 2, what: 'Mounted potato cannons', why: 'A cannon on an airship. The handheld potato cannon needs Ranged 20; this one is mechanical-crafted, so the gate is on placing it (a Project MMO PLACE rule). The rest of Aeronautics stays open, as decided in 1.13.0.' },
  { mod: 'createbackpackupgrades', items: ['createbackpackupgrades:pressing_upgrade'], skill: 'crafting', level: 30, kind: 'craft', impact: 2, what: 'Pressing upgrades', why: 'A press in the backpack with no rotation. The owner asked for this mod by name, so confirm before gating it.' },
  { mod: 'createbackpackupgrades', items: ['createbackpackupgrades:mixing_upgrade'], skill: 'crafting', level: 35, kind: 'craft', impact: 2, what: 'Mixing upgrades', why: 'A mixer in the backpack with no rotation or basin. The owner asked for this mod by name, so confirm before gating it.' },

  // ------------------------------------------------------------------ Sophisticated Backpacks (a ladder)
  { mod: 'sophisticatedbackpacks', items: sb('copper_backpack'), skill: 'crafting', level: 10, kind: 'craft', impact: 3, what: 'Copper backpacks', why: 'The backpack ladder (leather stays free): each tier adds rows and upgrade slots.' },
  { mod: 'sophisticatedbackpacks', items: sb('iron_backpack'), skill: 'crafting', level: 20, kind: 'craft', impact: 3, what: 'Iron backpacks', why: 'Backpack ladder, Andesite age.' },
  { mod: 'sophisticatedbackpacks', items: sb('gold_backpack'), skill: 'crafting', level: 35, kind: 'craft', impact: 4, what: 'Gold backpacks', why: 'Backpack ladder, Brass age (brass casings in the recipe).' },
  { mod: 'sophisticatedbackpacks', items: sb('diamond_backpack'), skill: 'crafting', level: 50, kind: 'craft', impact: 4, what: 'Diamond backpacks', why: 'Backpack ladder: with the ender chest (50).' },
  { mod: 'sophisticatedbackpacks', items: sb('netherite_backpack'), skill: 'smithing', level: 55, kind: 'craft', impact: 4, what: 'Netherite backpacks (smithing table)', why: 'Backpack ladder: a netherite upgrade at the smithing table, after netherite gear (50).' },
  { mod: 'sophisticatedbackpacks', items: sb('pickup_upgrade', 'filter_upgrade'), skill: 'crafting', level: 5, kind: 'craft', impact: 1, what: 'Pickup and filter upgrades', why: 'The first upgrades: small conveniences.' },
  { mod: 'sophisticatedbackpacks', items: sb('crafting_upgrade', 'stack_upgrade_starter_tier'), skill: 'crafting', level: 15, kind: 'craft', impact: 2, what: 'Crafting upgrade and the starter stack upgrade', why: 'A crafting grid on your back (its results still obey the making gates) and the first stack bonus.' },
  { mod: 'sophisticatedbackpacks', items: sb('restock_upgrade', 'deposit_upgrade', 'refill_upgrade'), skill: 'crafting', level: 20, kind: 'craft', impact: 2, what: 'Restock, deposit and refill upgrades', why: 'Empty into or fill from any container with a sneak-click, and keep a hotbar stack topped up.' },
  { mod: 'sophisticatedbackpacks', items: sb('void_upgrade', 'tool_swapper_upgrade', 'tank_upgrade', 'stack_upgrade_tier_1', 'stack_upgrade_starter_tier_to_tier_1_conversion'), skill: 'crafting', level: 25, kind: 'craft', impact: 2, what: 'Void, tool swapper, tank and stack tier 1 upgrades', why: 'Mid-tier conveniences: delete junk, pick the right tool by itself, carry fluids, 2x stacks.' },
  { mod: 'sophisticatedbackpacks', items: sb('magnet_upgrade', 'compacting_upgrade', 'advanced_pickup_upgrade', 'advanced_filter_upgrade'), skill: 'crafting', level: 30, kind: 'craft', impact: 4, what: 'Magnet, compacting and advanced pickup/filter upgrades', why: 'Pulls in drops from a distance and packs ores and crops into blocks as you go: big quality-of-life, Brass age.' },
  { mod: 'sophisticatedbackpacks', items: sb('advanced_restock_upgrade', 'advanced_deposit_upgrade', 'advanced_refill_upgrade', 'advanced_void_upgrade', 'advanced_tool_swapper_upgrade', 'stack_upgrade_tier_2', 'stack_upgrade_starter_tier_to_tier_2_conversion', 'stack_upgrade_tier_1_to_tier_2_conversion'), skill: 'crafting', level: 40, kind: 'craft', impact: 3, what: 'Advanced restock, deposit, refill, void and tool swapper upgrades, and stack tier 2', why: 'The advanced versions add filters and remote picking; stack tier 2 (4x, the pack\'s cap) already needs brass casings.' },
  { mod: 'sophisticatedbackpacks', items: sb('advanced_magnet_upgrade', 'advanced_compacting_upgrade'), skill: 'crafting', level: 45, kind: 'craft', impact: 3, what: 'Advanced magnet and advanced compacting upgrades', why: 'Wider pull with filters, and 3x3 compacting: the strongest everyday upgrades.' },
  { mod: 'sophisticatedbackpacks', items: sb('stonecutter_upgrade'), skill: 'construction', level: 10, kind: 'craft', impact: 1, what: 'Stonecutter upgrade', why: 'A stonecutter on your back for builders.' },
  { mod: 'sophisticatedbackpacks', items: sb('smelting_upgrade'), skill: 'smithing', level: 15, kind: 'craft', impact: 2, what: 'Smelting upgrade', why: 'A furnace on your back, with iron (15).' },
  { mod: 'sophisticatedbackpacks', items: sb('blasting_upgrade', 'anvil_upgrade'), skill: 'smithing', level: 25, kind: 'craft', impact: 2, what: 'Blasting and anvil upgrades', why: 'A blast furnace and an anvil on your back; the anvil block itself is Smithing 20.' },
  { mod: 'sophisticatedbackpacks', items: sb('auto_smelting_upgrade'), skill: 'smithing', level: 40, kind: 'craft', impact: 3, what: 'Auto-smelting upgrade', why: 'Smelts what you pick up with no menu at all. Note: with a pickup upgrade it can turn raw ores into free ingots past the Hardness use-gate (see the skips list).' },
  { mod: 'sophisticatedbackpacks', items: sb('auto_blasting_upgrade'), skill: 'smithing', level: 45, kind: 'craft', impact: 2, what: 'Auto-blasting upgrade', why: 'The faster ore version of auto-smelting.' },
  { mod: 'sophisticatedbackpacks', items: sb('smithing_upgrade'), skill: 'smithing', level: 50, kind: 'craft', impact: 2, what: 'Smithing upgrade', why: 'A smithing table on your back, for netherite upgrades in the field (netherite gear is Smithing 50). Check its result slot obeys the smithing gate.' },
  { mod: 'sophisticatedbackpacks', items: sb('smoking_upgrade'), skill: 'cooking', level: 15, kind: 'craft', impact: 1, what: 'Smoking upgrade', why: 'A smoker on your back.' },
  { mod: 'sophisticatedbackpacks', items: sb('feeding_upgrade'), skill: 'cooking', level: 25, kind: 'craft', impact: 2, what: 'Feeding upgrade', why: 'Eats for you from the backpack.' },
  { mod: 'sophisticatedbackpacks', items: sb('auto_smoking_upgrade', 'advanced_feeding_upgrade'), skill: 'cooking', level: 40, kind: 'craft', impact: 2, what: 'Auto-smoking and advanced feeding upgrades', why: 'Cooks what you pick up; eats by your own rules.' },
  { mod: 'sophisticatedbackpacks', items: sb('alchemy_upgrade'), skill: 'brewing', level: 45, kind: 'craft', impact: 3, what: 'Alchemy upgrade', why: 'Drinks potions and effect foods for you, the moment they help: strong in PvP.' },
  { mod: 'sophisticatedbackpacks', items: sb('advanced_alchemy_upgrade'), skill: 'brewing', level: 60, kind: 'craft', impact: 2, what: 'Advanced alchemy upgrade', why: 'Alchemy with effect filters: with the stronger (glowstone) potions at Brewing 60.' },
  { mod: 'sophisticatedcore', items: ['sophisticatedcore:ender_linker'], skill: 'crafting', level: 50, kind: 'craft', impact: 3, what: 'Ender linkers', why: 'Links storages into one shared group, ender-chest style: with the ender chest (50).' },

  // ------------------------------------------------------------------ Waystones
  { mod: 'waystones', items: ['/^waystones:([a-z_]+_)?waystone$/'], skill: 'agility', level: 45, kind: 'place', impact: 5, what: 'Waystones (all ten styles)', why: 'Your own fast-travel point. They come only from mechanical crafters (and found ones are taken home), so the gate is on placing one; the city\'s global waystone stays usable for everyone.' },
  { mod: 'waystones', items: ['/^waystones:[a-z_]+_sharestone$/'], skill: 'agility', level: 55, kind: 'place', impact: 4, what: 'Sharestones', why: 'Every sharestone of a colour links for everyone: a public network.' },
  { mod: 'waystones', items: ['/^waystones:[a-z_]+_portstone$/'], skill: 'agility', level: 35, kind: 'place', impact: 3, what: 'Portstones', why: 'Send-only stones (nothing can warp to them): cheaper and weaker than a waystone.' },
  { mod: 'waystones', items: ['waystones:warp_plate'], skill: 'agility', level: 40, kind: 'place', impact: 3, what: 'Warp plates', why: 'Paired teleport pads.' },
  { mod: 'waystones', items: ['waystones:warp_stone'], skill: 'agility', level: 50, kind: 'use', impact: 5, what: 'The warp stone', why: 'A reusable teleport to any waystone you have found, from anywhere: the strongest travel item.' },
  { mod: 'waystones', items: ['waystones:return_scroll'], skill: 'agility', level: 20, kind: 'craft', impact: 2, what: 'Return scrolls', why: 'One-use teleports, made at a crafting table.' },
  { mod: 'waystones', items: ['waystones:warp_scroll'], skill: 'agility', level: 30, kind: 'craft', impact: 2, what: 'Warp scrolls', why: 'A one-use teleport to any waystone you have found.' },
  { mod: 'waystones', items: ['waystones:portal_scroll'], skill: 'agility', level: 40, kind: 'craft', impact: 1, what: 'Portal scrolls', why: 'The costliest scroll (an ender eye in the recipe).' },

  // ------------------------------------------------------------------ Relics (wear, like the Climbing Boots: RELIC_WEAR)
  { mod: 'relics', items: ['relics:springy_boot'], skill: 'agility', level: 20, kind: 'wear', impact: 2, what: 'Springy Boot', why: 'Bounces you on landing and launches a crouch-jump.' },
  { mod: 'relics', items: ['relics:rider_flute'], skill: 'agility', level: 25, kind: 'use', impact: 2, what: 'Rider Flute', why: 'Stores a tamed mount and calls it back anywhere.' },
  { mod: 'relics', items: ['relics:cut_glass_boot'], skill: 'agility', level: 30, kind: 'wear', impact: 2, what: 'Cut Glass Boot', why: 'Walks on liquids and carries fluids like a bucket.' },
  { mod: 'relics', items: ['relics:roller_skate'], skill: 'agility', level: 35, kind: 'wear', impact: 3, what: 'Roller Skate', why: 'Builds up speed while you run.' },
  { mod: 'relics', items: ['relics:kinetic_belt'], skill: 'agility', level: 45, kind: 'wear', impact: 3, what: 'Kinetic Belt', why: 'Glides and keeps momentum (the Aeronaut set synergy, whose set needs Agility 40).' },
  { mod: 'relics', items: ['relics:chorus_staff'], skill: 'agility', level: 55, kind: 'use', impact: 4, what: 'Chorus Staff', why: 'Blink-teleports you forward on use: a PvP chase and escape tool.' },
  { mod: 'relics', items: ['relics:clot_of_time'], skill: 'agility', level: 60, kind: 'use', impact: 4, what: 'Clot of Time', why: 'Rewinds you along your recent path: an escape button (and the Prospector set synergy).' },
  { mod: 'relics', items: ['relics:glitchy_mantle'], skill: 'agility', level: 65, kind: 'wear', impact: 4, what: 'Glitchy Mantle', why: 'Attacks sometimes miss you, it leaves decoys, and you can walk on air.' },
  { mod: 'relics', items: ['relics:chef_hat'], skill: 'cooking', level: 20, kind: 'wear', impact: 1, what: "Chef's Hat", why: 'Kills drop meatballs.' },
  { mod: 'relics', items: ['relics:experience_disperser'], skill: 'enchanting', level: 25, kind: 'wear', impact: 1, what: 'Experience Disperser', why: 'Shares relic experience between your relics.' },
  { mod: 'relics', items: ['relics:piglin_mask'], skill: 'defence', level: 25, kind: 'wear', impact: 2, what: 'Piglin Mask', why: 'Piglins leave you alone and barter more generously.' },
  { mod: 'relics', items: ['relics:reflective_necklace'], skill: 'defence', level: 45, kind: 'wear', impact: 3, what: 'Reflective Necklace', why: 'Stores part of the damage you take and throws it back.' },
  { mod: 'relics', items: ['relics:shield_of_retaliation'], skill: 'defence', level: 50, kind: 'use', impact: 3, what: 'Shield of Retaliation', why: 'A timed parry that blocks a hit outright.' },
  { mod: 'relics', items: ['relics:jellyfish_necklace'], skill: 'hitpoints', level: 35, kind: 'wear', impact: 2, what: 'Jellyfish Necklace', why: 'More max health and regeneration in water or rain, plus a shock.' },
  { mod: 'relics', items: ['relics:sphere_of_self_sacrifice'], skill: 'hitpoints', level: 45, kind: 'use', impact: 3, what: 'Sphere of Self-Sacrifice', why: 'Spend a third of your health to heal twice that back.' },
  { mod: 'relics', items: ['relics:ghostly_mantle'], skill: 'hitpoints', level: 70, kind: 'wear', impact: 5, what: 'Ghostly Mantle', why: 'Every so often it cancels a killing blow and makes you immortal for a few seconds: a free death save on a lifesteal server.' },
  { mod: 'relics', items: ['relics:hunting_belt'], skill: 'strength', level: 30, kind: 'wear', impact: 2, what: 'Hunting Belt', why: 'Your pets hit harder, and it adds charm slots. (Strength unlocks nothing yet.)' },
  { mod: 'relics', items: ['relics:ring_of_the_seven_deadly_sins'], skill: 'strength', level: 55, kind: 'wear', impact: 4, what: 'Ring of the Seven Deadly Sins', why: 'Big damage modifiers (height, wrath, envy) plus luck (the Brass Duelist synergy).' },
  { mod: 'relics', items: ['relics:midnight_mantle'], skill: 'strength', level: 60, kind: 'wear', impact: 4, what: 'Midnight Mantle', why: 'Moon-phase damage and attack speed, invisibility in the dark, falling stars.' },
  { mod: 'relics', items: ['relics:leafy_mantle'], skill: 'woodcutting', level: 50, kind: 'wear', impact: 3, what: 'Leafy Mantle', why: 'Walk through leaves, heal among them, and cheat death with nearby foliage: a forester\'s relic.' },

  // ------------------------------------------------------------------ Ice and Fire
  { mod: 'iceandfire', items: iaf('silver_sword', 'silver_pickaxe', 'silver_axe', 'silver_shovel', 'silver_hoe', 'armor_silver_metal_helmet', 'armor_silver_metal_chestplate', 'armor_silver_metal_leggings', 'armor_silver_metal_boots'), skill: 'smithing', level: 20, kind: 'craft', impact: 2, what: 'Silver tools, weapons and armour', why: 'Silver is iron-plus (bonus against undead) and only comes from ice dragon dens: one step past iron (15).' },
  { mod: 'iceandfire', items: iaf('silver_sword', 'silver_axe'), skill: 'attack', level: 20, kind: 'hold', impact: 2, what: 'Silver sword and axe (to hit with)', why: 'Weapon tier between iron (15) and diamond (30), as vanilla tiers do (Project MMO WEAPON).' },
  { mod: 'iceandfire', items: iaf('silver_pickaxe', 'silver_shovel'), skill: 'mining', level: 20, kind: 'use', impact: 1, what: 'Silver pickaxe and shovel', why: 'Tool tier like the vanilla ones (Project MMO TOOL).' },
  { mod: 'iceandfire', items: iaf('silver_axe'), skill: 'woodcutting', level: 20, kind: 'use', impact: 1, what: 'Silver axe (to chop with)', why: 'Tool tier like the vanilla ones.' },
  { mod: 'iceandfire', items: iaf('silver_hoe'), skill: 'farming', level: 20, kind: 'use', impact: 1, what: 'Silver hoe', why: 'Tool tier like the vanilla ones.' },
  { mod: 'iceandfire', items: iaf('armor_silver_metal_helmet', 'armor_silver_metal_chestplate', 'armor_silver_metal_leggings', 'armor_silver_metal_boots'), skill: 'defence', level: 20, kind: 'wear', impact: 2, what: 'Silver armour', why: 'Armour tier between iron (15) and diamond (30).' },
  { mod: 'iceandfire', items: iaf('copper_sword', 'copper_axe'), skill: 'attack', level: 5, kind: 'hold', impact: 1, what: 'Copper sword and axe (to hit with)', why: 'Stone-tier weapons: the stone tier is 5.' },
  { mod: 'iceandfire', items: iaf('copper_pickaxe', 'copper_shovel'), skill: 'mining', level: 5, kind: 'use', impact: 1, what: 'Copper pickaxe and shovel', why: 'Stone-tier tools.' },
  { mod: 'iceandfire', items: iaf('copper_axe'), skill: 'woodcutting', level: 5, kind: 'use', impact: 1, what: 'Copper axe (to chop with)', why: 'Stone-tier tools.' },
  { mod: 'iceandfire', items: iaf('copper_hoe'), skill: 'farming', level: 5, kind: 'use', impact: 1, what: 'Copper hoe', why: 'Stone-tier tools.' },
  { mod: 'iceandfire', items: iaf('armor_copper_metal_helmet', 'armor_copper_metal_chestplate', 'armor_copper_metal_leggings', 'armor_copper_metal_boots'), skill: 'defence', level: 5, kind: 'wear', impact: 1, what: 'Copper armour', why: 'Between leather and chainmail, like Create\'s copper diving gear (Defence 5).' },
  { mod: 'iceandfire', items: iaf('dragonbone_sword', 'dragonbone_pickaxe', 'dragonbone_axe', 'dragonbone_shovel', 'dragonbone_hoe', 'dragonbone_bow'), skill: 'crafting', level: 55, kind: 'craft', impact: 3, what: 'Dragonbone tools, sword and bow', why: 'Dragon bones and wither bones: past diamond, before netherite-plus.' },
  { mod: 'iceandfire', items: iaf('dragonbone_sword', 'dragonbone_axe'), skill: 'attack', level: 55, kind: 'hold', impact: 3, what: 'Dragonbone sword and axe (to hit with)', why: 'Between netherite (50) and the elemental swords (60).' },
  { mod: 'iceandfire', items: iaf('dragonbone_pickaxe', 'dragonbone_shovel'), skill: 'mining', level: 55, kind: 'use', impact: 2, what: 'Dragonbone pickaxe and shovel', why: 'Past netherite (50).' },
  { mod: 'iceandfire', items: iaf('dragonbone_axe'), skill: 'woodcutting', level: 55, kind: 'use', impact: 1, what: 'Dragonbone axe (to chop with)', why: 'Past netherite (50).' },
  { mod: 'iceandfire', items: iaf('dragonbone_hoe'), skill: 'farming', level: 55, kind: 'use', impact: 1, what: 'Dragonbone hoe', why: 'Past netherite (50).' },
  { mod: 'iceandfire', items: iaf('dragonbone_bow'), skill: 'ranged', level: 55, kind: 'use', impact: 3, what: 'Dragonbone bow', why: 'A bow of dragon bone: past the trident (40).' },
  { mod: 'iceandfire', items: iaf('dragonbone_sword_fire', 'dragonbone_sword_ice', 'dragonbone_sword_lightning'), skill: 'crafting', level: 60, kind: 'craft', impact: 3, what: 'Flamed, iced and lightning dragonbone swords', why: 'A dragonbone sword soaked in dragon blood: burns, freezes or shocks on hit.' },
  { mod: 'iceandfire', items: iaf('dragonbone_sword_fire', 'dragonbone_sword_ice', 'dragonbone_sword_lightning'), skill: 'attack', level: 60, kind: 'hold', impact: 3, what: 'Elemental dragonbone swords (to hit with)', why: 'Elemental damage on top of dragonbone.' },
  { mod: 'iceandfire', items: [...dsTools('sword'), ...dsTools('pickaxe'), ...dsTools('axe'), ...dsTools('shovel'), ...dsTools('hoe'), ...['fire', 'ice', 'lightning'].flatMap((e) => ['helmet', 'chestplate', 'leggings', 'boots'].map((p) => `iceandfire:dragonsteel_${e}_${p}`))], skill: 'smithing', level: 80, kind: 'craft', impact: 5, what: 'Dragonsteel tools, weapons and armour', why: 'The best gear in the pack, from ingots forged in a dragon\'s breath. Ingots stay free (the rule for ingots); making the gear is master smithing, past the mace (70).' },
  { mod: 'iceandfire', items: [...dsTools('sword'), ...dsTools('axe')], skill: 'attack', level: 75, kind: 'hold', impact: 5, what: 'Dragonsteel swords and axes (to hit with)', why: 'Stronger than netherite (50) and the Stormcaller\'s Sabre (50): only armour is quest-gated today, so the weapons have no gate at all.' },
  { mod: 'iceandfire', items: [...dsTools('pickaxe'), ...dsTools('shovel')], skill: 'mining', level: 75, kind: 'use', impact: 3, what: 'Dragonsteel pickaxes and shovels', why: 'The fastest picks in the pack.' },
  { mod: 'iceandfire', items: dsTools('axe'), skill: 'woodcutting', level: 75, kind: 'use', impact: 2, what: 'Dragonsteel axes (to chop with)', why: 'The fastest axes in the pack.' },
  { mod: 'iceandfire', items: dsTools('hoe'), skill: 'farming', level: 75, kind: 'use', impact: 1, what: 'Dragonsteel hoes', why: 'The best hoes in the pack.' },
  { mod: 'iceandfire', items: ['/^iceandfire:armor_(red|green|bronze|gray|blue|white|sapphire|silver|electric|amethyst|copper|black)_(helmet|chestplate|leggings|boots)$/'], skill: 'crafting', level: 60, kind: 'craft', impact: 3, what: 'Dragonscale armour (all twelve colours)', why: 'Wearing it already needs Dragon Slayer I; making it from scales becomes a Crafting feat, with the end crystal (60). (Optional, not proposed: a Defence 60 wear level on top of the quest gate.)' },
  { mod: 'iceandfire', items: iaf('dragonforge_fire_core_disabled', 'dragonforge_ice_core_disabled', 'dragonforge_lightning_core_disabled'), skill: 'smithing', level: 70, kind: 'craft', machine: true, impact: 3, what: 'Dragonforge cores', why: 'The forge that turns iron into dragonsteel with a dragon\'s breath. It runs with no player (dragonsteel is an ingot), so the gate is on building it, as with Create\'s machines.' },
  { mod: 'iceandfire', items: ['/^iceandfire:dragonegg_[a-z]+$/'], skill: 'farming', level: 70, kind: 'use', impact: 5, what: 'Dragon eggs (placing one to hatch it)', why: 'A dragon is the strongest mount, pet and forge fuel in the pack. Raising one is master husbandry; the egg can still be carried, traded and kept (a Project MMO USE rule on placing it).' },
  { mod: 'iceandfire', items: iaf('summoning_crystal_fire', 'summoning_crystal_ice', 'summoning_crystal_lightning'), skill: 'crafting', level: 65, kind: 'craft', impact: 3, what: 'Summoning crystals', why: 'Store your dragon and call it to you anywhere.' },
  { mod: 'iceandfire', items: iaf('dragon_horn'), skill: 'crafting', level: 45, kind: 'craft', impact: 2, what: 'Dragon horns', why: 'Carries a tamed dragon as an item.' },
  { mod: 'iceandfire', items: iaf('dragon_seeker'), skill: 'crafting', level: 45, kind: 'craft', impact: 2, what: 'Dragon seekers', why: 'Points at the nearest dragon: hunting roosts for scales and bones.' },
  { mod: 'iceandfire', items: iaf('epic_dragon_seeker'), skill: 'smithing', level: 55, kind: 'craft', impact: 1, what: 'Epic dragon seekers (smithing, a nether star)', why: 'Longer range seeker.' },
  { mod: 'iceandfire', items: iaf('legendary_dragon_seeker'), skill: 'smithing', level: 70, kind: 'craft', impact: 1, what: 'Legendary dragon seekers (dragonsteel)', why: 'The best seeker.' },
  { mod: 'iceandfire', items: iaf('cooked_rice_with_fire_dragon_meat', 'cooked_rice_with_ice_dragon_meat', 'cooked_rice_with_lightning_dragon_meat'), skill: 'cooking', level: 60, kind: 'craft', impact: 1, what: 'Rice with dragon meat (cooking pot)', why: 'Exotic dishes from dragon flesh, past the feasts (50).' },

  // ------------------------------------------------------------------ Farmer's Delight
  { mod: 'farmersdelight', items: ['farmersdelight:golden_knife'], skill: 'smithing', level: 10, kind: 'craft', impact: 1, what: 'Golden knives', why: 'The vanilla gold tier (Smithing 10).' },
  { mod: 'farmersdelight', items: ['farmersdelight:iron_knife', 'farmersdelight:skillet'], skill: 'smithing', level: 15, kind: 'craft', impact: 1, what: 'Iron knives and the skillet', why: 'The vanilla iron tier (Smithing 15).' },
  { mod: 'farmersdelight', items: ['farmersdelight:diamond_knife'], skill: 'crafting', level: 30, kind: 'craft', impact: 2, what: 'Diamond knives', why: 'The vanilla diamond tier (Crafting 30).' },
  { mod: 'farmersdelight', items: ['farmersdelight:netherite_knife'], skill: 'smithing', level: 50, kind: 'craft', impact: 2, what: 'Netherite knives (smithing table)', why: 'The vanilla netherite tier (Smithing 50).' },
  { mod: 'farmersdelight', items: ['farmersdelight:flint_knife'], skill: 'attack', level: 5, kind: 'hold', impact: 1, what: 'Flint knives (to hit with)', why: 'The stone tier (5).' },
  { mod: 'farmersdelight', items: ['farmersdelight:golden_knife'], skill: 'attack', level: 10, kind: 'hold', impact: 1, what: 'Golden knives (to hit with)', why: 'Knives are fast weapons with Backstabbing: same tiers as swords.' },
  { mod: 'farmersdelight', items: ['farmersdelight:iron_knife', 'farmersdelight:skillet'], skill: 'attack', level: 15, kind: 'hold', impact: 1, what: 'Iron knives and the skillet (to hit with)', why: 'Iron-tier weapons.' },
  { mod: 'farmersdelight', items: ['farmersdelight:diamond_knife'], skill: 'attack', level: 30, kind: 'hold', impact: 2, what: 'Diamond knives (to hit with)', why: 'Diamond-tier weapon.' },
  { mod: 'farmersdelight', items: ['farmersdelight:netherite_knife'], skill: 'attack', level: 50, kind: 'hold', impact: 2, what: 'Netherite knives (to hit with)', why: 'Netherite-tier weapon.' },
  { mod: 'farmersdelight', items: ['farmersdelight:melon_juice'], skill: 'cooking', level: 15, kind: 'craft', impact: 1, what: 'Melon juice', why: 'A drink with minor instant health.' },
  { mod: 'farmersdelight', items: ['farmersdelight:hot_cocoa'], skill: 'cooking', level: 25, kind: 'craft', impact: 2, what: 'Hot cocoa (cooking pot)', why: 'Clears a harmful effect: a cure in a mug.' },
  { mod: 'farmersdelight', items: ['farmersdelight:gleaming_salad_block'], skill: 'cooking', level: 50, kind: 'craft', impact: 2, what: 'Gleaming salad (a feast)', why: 'Farmer\'s Delight\'s newest feast, missing from the feasts gate (Cooking 50).' },
  { mod: 'farmersdelight', items: ['farmersdelight:organic_compost'], skill: 'farming', level: 20, kind: 'craft', impact: 2, what: 'Organic compost', why: 'Turns into rich soil, which speeds every crop planted on it.' },

  // ------------------------------------------------------------------ Friends & Foes, Illager Invasion, Piglin Proliferation
  { mod: 'friendsandfoes', items: ['friendsandfoes:totem_of_freezing'], skill: 'defence', level: 40, kind: 'wear', impact: 3, what: 'Totem of Freezing (held or in the charm slot)', why: 'Freezes everything near you when you drop below half health (works from the charm slot). Consider the vanilla Totem of Undying at Hitpoints 50 too.' },
  { mod: 'friendsandfoes', items: ['friendsandfoes:totem_of_illusion'], skill: 'agility', level: 45, kind: 'wear', impact: 3, what: 'Totem of Illusion (held or in the charm slot)', why: 'Turns you invisible and leaves decoys when you drop below half health: an escape.' },
  { mod: 'friendsandfoes', items: ['friendsandfoes:wildfire_crown'], skill: 'defence', level: 45, kind: 'wear', impact: 2, what: 'Wildfire Crown', why: 'The Nether citadel boss\'s helmet: with the loot-only Ember Crown (40).' },
  { mod: 'friendsandfoes', items: ['friendsandfoes:crab_claw'], skill: 'brewing', level: 45, kind: 'brew', impact: 2, what: 'Potion of Reaching (crab claw)', why: 'Longer block reach. With Weakness, Harming and Invisibility (45).' },
  { mod: 'illagerinvasion', items: ['illagerinvasion:imbuing_table'], skill: 'enchanting', level: 65, kind: 'craft', impact: 4, what: 'Imbuing tables', why: 'Pushes an enchantment one level past its maximum: the only way past the caps besides the skill. Check it respects the Enchanting caps.' },
  { mod: 'illagerinvasion', items: ['illagerinvasion:platinum_sheet'], skill: 'smithing', level: 45, kind: 'craft', impact: 2, what: 'Platinum sheets (trim material)', why: 'Platinum trims carry effects (agility, endurance, featherweight, insight), so trimming becomes more than cosmetic; trim copying is Smithing 40.' },
  { mod: 'illagerinvasion', items: ['illagerinvasion:horn_of_sight'], skill: 'crafting', level: 45, kind: 'craft', impact: 2, what: 'Horn of Sight', why: 'Reveals the creatures around you: scouting.' },
  { mod: 'illagerinvasion', items: ['illagerinvasion:lost_candle'], skill: 'mining', level: 40, kind: 'use', impact: 2, what: 'Lost Candle', why: 'Tells you which ores are nearby: prospecting. Loot-only, so the gate is on using it.' },
  { mod: 'illagerinvasion', items: ['illagerinvasion:platinum_infused_hatchet'], skill: 'strength', level: 40, kind: 'hold', impact: 2, what: 'Platinum Infused Hatchet', why: 'A heavy illager weapon. (Strength unlocks nothing yet.)' },
  { mod: 'illagerinvasion', items: ['minecraft:goat_horn'], skill: 'brewing', level: 40, kind: 'brew', impact: 2, what: 'Potion of Berserking (goat horn)', why: 'Illager Invasion\'s potion, brewed from an awkward potion and a goat horn; with Regeneration (40).' },
  { mod: 'piglinproliferation', items: ['piglinproliferation:buckler'], skill: 'defence', level: 45, kind: 'hold', impact: 3, what: 'Buckler', why: 'A shield with a charge: bash through, explode, and a guaranteed critical after.' },
  { mod: 'piglinproliferation', items: ['/^piglinproliferation:[a-z_]+fire_ring$/'], skill: 'brewing', level: 40, kind: 'craft', impact: 2, what: 'Alchemical fire pits (fire rings)', why: 'A campfire you infuse with a potion so it gives the effect to everyone nearby.' },

  // ------------------------------------------------------------------ Vanilla Backport
  { mod: 'vanillabackport', items: ['/^minecraft:[a-z_]+_harness$/'], skill: 'agility', level: 40, kind: 'craft', impact: 4, what: 'Harnesses (to ride a happy ghast)', why: 'A happy ghast is a flying mount for four, reachable in the Nether before the elytra (Agility 30 to wear); the harness is what lets you ride it.' },
  { mod: 'vanillabackport', items: ['/^minecraft:([a-z_]+_)?bundle$/'], skill: 'crafting', level: 10, kind: 'craft', impact: 1, what: 'Bundles', why: 'Many kinds of item in one slot; Vanilla Backport turns their recipe on.' },
  { mod: 'vanillabackport', items: ['minecraft:pale_oak_log', 'minecraft:pale_oak_wood', 'minecraft:stripped_pale_oak_log', 'minecraft:stripped_pale_oak_wood'], skill: 'woodcutting', level: 40, kind: 'chop', impact: 1, what: 'Pale oaks', why: 'The creaking\'s eerie forest: with the dark oaks (35) of the CHOP ladder.' },

  // ------------------------------------------------------------------ Regions Unexplored: the CHOP ladder (RuneScape trees)
  { mod: 'regions_unexplored', items: ruWood('pine'), skill: 'woodcutting', level: 10, kind: 'chop', impact: 2, what: 'Pine trees', why: 'Common taiga trees: a first step.' },
  { mod: 'regions_unexplored', items: [...ruWood('palm'), 'regions_unexplored:bamboo_log', 'regions_unexplored:stripped_bamboo_log'], skill: 'woodcutting', level: 15, kind: 'chop', impact: 1, what: 'Palms and giant bamboo', why: 'Tropical trees, with jungle trees (15).' },
  { mod: 'regions_unexplored', items: ruWood('joshua', 'larch'), skill: 'woodcutting', level: 20, kind: 'chop', impact: 1, what: 'Joshua trees and larches', why: 'Desert and golden-taiga trees.' },
  { mod: 'regions_unexplored', items: [...ruWood('cypress'), 'regions_unexplored:ashen_log', 'regions_unexplored:ashen_wood', ...ruStem('blue', 'green', 'pink', 'yellow')], skill: 'woodcutting', level: 25, kind: 'chop', impact: 1, what: 'Cypresses, ashen trees and bioshroom stems', why: 'Bayou, burnt-forest and cave trees.' },
  { mod: 'regions_unexplored', items: ruWood('willow'), skill: 'woodcutting', level: 30, kind: 'chop', impact: 2, what: 'Willows', why: "RuneScape's willow is level 30." },
  { mod: 'regions_unexplored', items: ruWood('eucalyptus'), skill: 'woodcutting', level: 35, kind: 'chop', impact: 1, what: 'Eucalyptus', why: "With dark oak (35), like RuneScape's teak." },
  { mod: 'regions_unexplored', items: ruWood('magnolia', 'wisteria', 'baobab'), skill: 'woodcutting', level: 40, kind: 'chop', impact: 1, what: 'Magnolias, wisterias and baobabs', why: 'Flowering and savanna giants.' },
  { mod: 'regions_unexplored', items: ruWood('maple'), skill: 'woodcutting', level: 45, kind: 'chop', impact: 2, what: 'Maples', why: "RuneScape's maple is level 45." },
  { mod: 'regions_unexplored', items: ruWood('kapok'), skill: 'woodcutting', level: 50, kind: 'chop', impact: 1, what: 'Kapoks', why: "Rainforest giants, like RuneScape's mahogany (50)." },
  { mod: 'regions_unexplored', items: ruWood('socotra', 'blackwood'), skill: 'woodcutting', level: 55, kind: 'chop', impact: 1, what: 'Socotras and blackwoods', why: 'Rare dragon-blood trees and the dark blackwood taiga.' },
  { mod: 'regions_unexplored', items: [...ruWood('brimwood', 'cobalt'), 'regions_unexplored:brimwood_log_magma'], skill: 'woodcutting', level: 65, kind: 'chop', impact: 1, what: 'Brimwood and cobalt (Nether)', why: 'Nether trees past crimson and warped stems (60).' },
  { mod: 'regions_unexplored', items: ruWood('redwood'), skill: 'woodcutting', level: 70, kind: 'chop', impact: 2, what: 'Redwoods', why: "RuneScape's redwood is the top tree (90 there); these giants drop the most logs per tree." }
]

/** Hardness additions: modded ores and raw materials that should join a tier. */
export const HARDNESS_ADDITIONS = [
  { tier: 2, blocks: ['#c:ores/silver'], items: ['#c:ores/silver', '#c:raw_materials/silver', '#c:storage_blocks/raw_silver'], resolved: ['iceandfire:silver_ore', 'iceandfire:deepslate_silver_ore', 'iceandfire:raw_silver', 'iceandfire:raw_silver_block'], why: 'Ice and Fire silver: gold-rare (only in ice dragon dens, its world ore is switched off). Ingots stay free, as with every metal.' },
  { tier: 2, blocks: [], items: ['createoreexcavation:raw_redstone'], resolved: ['createoreexcavation:raw_redstone'], why: "Raw redstone from Ore Excavation's redstone veins mills and crushes into redstone (tier II). Machines feeding it stay exempt; a player hand-milling it should not be." },
  { tier: 3, blocks: ['#c:ores/sapphire'], items: ['#c:ores/sapphire', '#c:gems/sapphire', 'iceandfire:sapphire_block'], resolved: ['iceandfire:sapphire_ore', 'iceandfire:sapphire_gem', 'iceandfire:sapphire_block'], why: 'Ice and Fire sapphire is a gem from ice dragon dens, a diamond-tier find (emeralds stay free only because they are money).' },
  { tier: 3, blocks: ['regions_unexplored:cobalt_obsidian'], items: ['regions_unexplored:cobalt_obsidian'], resolved: ['regions_unexplored:cobalt_obsidian'], why: "Regions Unexplored's cobalt obsidian is tagged #c:obsidians (crying), so tag-based recipes (the wand of symmetry, the backpack void upgrade) take it in place of obsidian, and a diamond pickaxe breaks it with no Hardness." },
  { tier: 3, blocks: [], items: ['createoreexcavation:raw_diamond'], resolved: ['createoreexcavation:raw_diamond'], why: 'Raw diamond from Ore Excavation: its vein is removed, but if it ever returns it is a raw diamond. (Raw emerald stays free, like emeralds.)' }
]

/** Optional: closes a Create route past tiers I and II, at the cost of making Create's ore stones awkward to hand-process. */
export const HARDNESS_OPTIONAL = [
  { tier: 1, items: ['create:crimsite', 'create:asurine'], why: 'Crushing crimsite gives crushed raw iron and asurine crushed raw zinc with no Mining level (they mine like stone). Materials list only: the stones stay breakable and placeable, but a player could no longer hand-feed them to a millstone or crusher. Crushing wheels take items dropped on them, so this only narrows the route; machines are exempt by design.' },
  { tier: 2, items: ['create:ochrum'], why: 'Crushing ochrum gives crushed raw gold (and electrum nuggets) with no Mining level. Same caveat as above.' }
]

/** Recipes and routes that skip a gate (existing or proposed). */
export const SKIPS = [
  { gate: 'Cooking 20 (cake)', items: ['minecraft:cake'], route: 'createaddition:filling/cake: a spout fills a baked cake base with milk', fix: "The machine rule covers basins, mechanical crafters and the Crafter, not the spout. Extend it to Create's filling, deploying and sequenced assembly results, or remove the recipe in KubeJS." },
  { gate: 'Cooking 30 (chocolate pie)', items: ['farmersdelight:chocolate_pie'], route: 'farmersdelight:integration/create/filling/chocolate_pie: a spout fills a pie crust with chocolate', fix: 'Same as the cake.' },
  { gate: 'Smithing 15 (iron helmet)', items: ['minecraft:iron_helmet'], route: "simulated:sequenced_assembly/engine_assembly lists an iron helmet among its scrap results (a small chance)", fix: 'Minor (wearing still needs Defence 15); the sequenced-assembly machine rule above would cover it.' },
  { gate: 'Crafting 20 (item vaults, proposed)', items: ['createdeco:*_shipping_container', 'create_connected:item_silo'], route: 'Create Deco shipping containers (barrel, dye, iron sheet) and Create Connected item silos (iron sheet, barrel) are vaults from their own recipes', fix: 'Gate them with the vault (included in the proposals).' },
  { gate: 'Hardness III (obsidian)', items: ['regions_unexplored:cobalt_obsidian'], route: 'Cobalt obsidian is in #c:obsidians, which the wand of symmetry and the void upgrade accept, and it needs no Hardness to break', fix: 'Add it to tier III (included in the Hardness additions).' },
  { gate: 'Hardness I and II (iron, zinc, gold)', items: ['create:crimsite', 'create:asurine', 'create:ochrum', 'minecraft:tuff'], route: "Create's ore stones (and tuff) crush into crushed raw iron, zinc and gold, and nuggets, with no Mining level", fix: 'A machine route, exempt by design; see the optional Hardness additions if it should narrow.' },
  { gate: 'Hardness use-gate (raw ores)', items: ['sophisticatedbackpacks:pickup_upgrade', 'sophisticatedbackpacks:auto_smelting_upgrade', 'sophisticatedbackpacks:auto_blasting_upgrade'], route: 'A backpack with a pickup upgrade takes raw ores off the ground without a menu click, and auto-smelting/blasting turns them into ingots (which are free)', fix: "Have the use-gate also check backpack pickup (Sophisticated's pickup event) or give the auto-smelting upgrades a filter that refuses gated materials." },
  { gate: 'Enchanting caps', items: ['illagerinvasion:imbuing_table', 'create_enchantment_industry:blaze_forger'], route: 'The imbuing table raises an enchantment past its maximum; the blaze forger combines books with no player at an anvil', fix: 'Check both against the caps (the anvil and table checks do not run there). Using an over-cap item still needs the level, so this is a making gap, not a use gap.' },
  { gate: 'Smithing gates and anvil caps', items: ['sophisticatedbackpacks:smithing_upgrade', 'sophisticatedbackpacks:anvil_upgrade'], route: "The backpack's smithing and anvil tabs have their own result slots", fix: 'Test that the smithing-table gate (netherite gear, Smithing 50) and the anvil enchanting caps apply there; the crafting upgrade is known to be covered.' },
  { gate: 'Covered already (no action)', items: ['minecraft:cake', 'minecraft:pumpkin_pie'], route: "Farmer's Delight (cake from milk bottles, pies from slices or crust) and Naturalist (duck-egg cake and pumpkin pie) add crafting-grid recipes for gated vanilla foods", fix: 'The making gate checks the result, so every crafting-grid recipe for a gated item is already gated.' }
]
