package net.lemursaucepacket.fixes.compat;

/**
 * Recognises the stand-in world region Distant Horizons generates its distant land in (by class name, so the pack
 * builds and runs without Distant Horizons). Land made there only becomes scenery: Distant Horizons builds it without
 * structures, and real chunks are generated by Minecraft as usual.
 */
public final class DistantHorizonsRegion {
    private static final String REGION = "com.seibel.distanthorizons.common.wrappers.worldGeneration.mimicObject.DhLitWorldGenRegion_neoforge";
    private static volatile Class<?> known;

    private DistantHorizonsRegion() {
    }

    public static boolean is(Object level) {
        if (level == null) return false;
        Class<?> type = level.getClass();
        if (type == known) return true;
        if (!type.getName().equals(REGION)) return false;
        known = type;
        return true;
    }
}
