name = "LemurSaucePacket"
author = "LemurSaucePacket admins"
version = "1.6.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60397eeabc2e8cf4b957e67fc965410e39a1b6cf428339e54b53b45368a22ac2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
