name = "LemurSaucePacket"
author = "LemurSaucePacket admins"
version = "1.2.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c6c8df551eff03d1642a1412df8111116a099dfeb84340574693ce91edf1785e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
