name = "LemurSaucePacket"
author = "LemurSaucePacket admins"
version = "1.14.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a6276b38b9ab0d8689b6afdd86b9a0cefd5eb66c3f9156d6a6cdff03a4f978d8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
