// JEI hides what you can't get in survival: creative and operator items, spawn eggs, technical blocks, and items whose
// only source is switched off in this pack (configs, scripts). The list is from a check of every recipe, loot table,
// loot modifier and structure in the pack (421 items, 2026-10-06). Items the game hands out in code (Create's
// package styles, fluid and mob buckets, bug-net catches, feasts) stay visible: hiding a real item is worse than
// showing a creative one. Redo the check after adding or removing mods (see PACK_DESIGN.md, "JEI").
const JEI_HIDDEN = [
  "aeronautics:black_envelope_encased_shaft", "aeronautics:blue_envelope_encased_shaft",
  "aeronautics:brown_envelope_encased_shaft", "aeronautics:cyan_envelope_encased_shaft",
  "aeronautics:gray_envelope_encased_shaft", "aeronautics:green_envelope_encased_shaft",
  "aeronautics:light_blue_envelope_encased_shaft", "aeronautics:light_gray_envelope_encased_shaft",
  "aeronautics:lime_envelope_encased_shaft", "aeronautics:magenta_envelope_encased_shaft",
  "aeronautics:orange_envelope_encased_shaft", "aeronautics:pink_envelope_encased_shaft",
  "aeronautics:purple_envelope_encased_shaft", "aeronautics:red_envelope_encased_shaft",
  "aeronautics:white_envelope_encased_shaft", "aeronautics:yellow_envelope_encased_shaft",
  "create:andesite_encased_cogwheel", "create:andesite_encased_large_cogwheel", "create:andesite_encased_shaft",
  "create:brass_encased_cogwheel", "create:brass_encased_large_cogwheel", "create:brass_encased_shaft",
  "create:chromatic_compound", "create:copper_backtank_placeable", "create:creative_blaze_cake",
  "create:creative_crate", "create:creative_fluid_tank", "create:creative_motor", "create:crushed_raw_aluminum",
  "create:crushed_raw_lead", "create:crushed_raw_nickel", "create:crushed_raw_osmium", "create:crushed_raw_platinum",
  "create:crushed_raw_quicksilver", "create:crushed_raw_silver", "create:crushed_raw_tin",
  "create:crushed_raw_uranium", "create:elevator_contact", "create:handheld_worldshaper",
  "create:netherite_backtank_placeable", "create:refined_radiance", "create:refined_radiance_casing",
  "create:shadow_steel", "create:shadow_steel_casing", "create_connected:andesite_encased_cross_connector",
  "create_connected:brass_encased_cross_connector", "create_connected:copycat_beam",
  "create_connected:copycat_block", "create_connected:copycat_board", "create_connected:copycat_box",
  "create_connected:copycat_catwalk", "create_connected:copycat_fence", "create_connected:copycat_fence_gate",
  "create_connected:copycat_slab", "create_connected:copycat_stairs", "create_connected:copycat_vertical_step",
  "create_connected:copycat_wall", "create_connected:creative_fluid_vessel",
  "create_connected:fan_chocolate_coating_catalyst", "create_connected:fan_enriched_catalyst",
  "create_connected:fan_exploding_catalyst", "create_connected:fan_glooming_catalyst",
  "create_connected:fan_honey_coating_catalyst", "create_connected:fan_purifying_catalyst",
  "create_connected:fan_resonance_catalyst", "create_connected:fan_sculking_catalyst",
  "create_connected:fan_seething_catalyst", "create_connected:fan_soul_stripping_catalyst",
  "create_connected:fan_transmutation_catalyst", "create_connected:fan_withering_catalyst",
  "create_enchantment_industry:blazes_enchanting_handbook", "create_enchantment_industry:classic_blaze_enchanter",
  "create_enchantment_industry:grindstone_drain", "createaddition:creative_energy", "createaddition:digital_adapter",
  "createoreexcavation:raw_diamond", "createoreexcavation:raw_emerald", "creeperoverhaul:badlands_creeper_spawn_egg",
  "creeperoverhaul:bamboo_creeper_spawn_egg", "creeperoverhaul:beach_creeper_spawn_egg",
  "creeperoverhaul:birch_creeper_spawn_egg", "creeperoverhaul:cave_creeper_spawn_egg",
  "creeperoverhaul:dark_oak_creeper_spawn_egg", "creeperoverhaul:desert_creeper_spawn_egg",
  "creeperoverhaul:dripstone_creeper_spawn_egg", "creeperoverhaul:hills_creeper_spawn_egg",
  "creeperoverhaul:jungle_creeper_spawn_egg", "creeperoverhaul:mushroom_creeper_spawn_egg",
  "creeperoverhaul:ocean_creeper_spawn_egg", "creeperoverhaul:savannah_creeper_spawn_egg",
  "creeperoverhaul:snowy_creeper_spawn_egg", "creeperoverhaul:spruce_creeper_spawn_egg",
  "creeperoverhaul:swamp_creeper_spawn_egg", "dragonlib:dragon", "easy_npc:allay_spawn_egg", "easy_npc:boss_spawner",
  "easy_npc:bullet", "easy_npc:cat_spawn_egg", "easy_npc:cave_spider_spawn_egg", "easy_npc:chicken_spawn_egg",
  "easy_npc:creeper_spawn_egg", "easy_npc:custom_data_test", "easy_npc:default_spawner",
  "easy_npc:doppler_spawn_egg", "easy_npc:drowned_spawn_egg", "easy_npc:easy_npc_preset",
  "easy_npc:easy_npc_preset_empty", "easy_npc:enderman_spawn_egg", "easy_npc:evoker_spawn_egg",
  "easy_npc:fairy_spawn_egg", "easy_npc:fox_spawn_egg", "easy_npc:ghast_spawn_egg", "easy_npc:group_spawner",
  "easy_npc:horse_spawn_egg", "easy_npc:humanoid_slim_spawn_egg", "easy_npc:humanoid_spawn_egg",
  "easy_npc:husk_spawn_egg", "easy_npc:illusioner_spawn_egg", "easy_npc:iron_golem_spawn_egg",
  "easy_npc:move_easy_npc", "easy_npc:npc_coin", "easy_npc:npc_key", "easy_npc:npc_red_token",
  "easy_npc:orc_spawn_egg", "easy_npc:orc_warrior_spawn_egg", "easy_npc:pig_spawn_egg",
  "easy_npc:piglin_brute_spawn_egg", "easy_npc:piglin_spawn_egg", "easy_npc:pillager_spawn_egg",
  "easy_npc:single_spawner", "easy_npc:bogged_spawn_egg", "easy_npc:skeleton_horse_spawn_egg",
  "easy_npc:skeleton_spawn_egg", "easy_npc:slime_spawn_egg", "easy_npc:spider_spawn_egg", "easy_npc:stray_spawn_egg",
  "easy_npc:vex_spawn_egg", "easy_npc:villager_spawn_egg", "easy_npc:vindicator_spawn_egg",
  "easy_npc:wandering_trader_spawn_egg", "easy_npc:witch_spawn_egg", "easy_npc:wither_skeleton_spawn_egg",
  "easy_npc:wolf_spawn_egg", "easy_npc:world_spawner", "easy_npc:zombie_horse_spawn_egg",
  "easy_npc:zombie_spawn_egg", "easy_npc:zombie_villager_spawn_egg", "easy_npc:zombified_piglin_spawn_egg",
  "easy_npc_config_ui:easy_npc_wand", "easy_npc_config_ui:preset_browser", "everycomp:all_woods",
  "farmersdelight:debug_pumpkin_pie", "farmersdelight:rich_soil_farmland", "friendsandfoes:copper_golem_spawn_egg",
  "friendsandfoes:crab_spawn_egg", "friendsandfoes:glare_spawn_egg", "friendsandfoes:iceologer_spawn_egg",
  "friendsandfoes:illusioner_spawn_egg", "friendsandfoes:mauler_spawn_egg", "friendsandfoes:moobloom_spawn_egg",
  "friendsandfoes:rascal_spawn_egg", "friendsandfoes:tuff_golem_spawn_egg", "friendsandfoes:wildfire_spawn_egg",
  "ftblibrary:icon_item", "ftbquests:barrier", "ftbquests:custom_icon", "ftbquests:detector", "ftbquests:lootcrate",
  "ftbquests:missing_item", "ftbquests:stage_barrier", "guardvillagers:guard_spawn_egg",
  "guardvillagers:illusioner_spawn_egg", "illagerinvasion:alchemist_spawn_egg",
  "illagerinvasion:archivist_spawn_egg", "illagerinvasion:basher_spawn_egg", "illagerinvasion:firecaller_spawn_egg",
  "illagerinvasion:illusioner_spawn_egg", "illagerinvasion:inquisitor_spawn_egg",
  "illagerinvasion:invoker_spawn_egg", "illagerinvasion:magical_fire_charge", "illagerinvasion:marauder_spawn_egg",
  "illagerinvasion:necromancer_spawn_egg", "illagerinvasion:provoker_spawn_egg",
  "illagerinvasion:sorcerer_spawn_egg", "illagerinvasion:surrendered_spawn_egg", "lootr:decorated_pot",
  "lootr:lootr_barrel", "lootr:lootr_chest", "lootr:lootr_inventory", "lootr:lootr_shulker",
  "lootr:lootr_trapped_chest", "lootr:suspicious_gravel", "lootr:suspicious_sand", "minecraft:allay_spawn_egg",
  "minecraft:armadillo_spawn_egg", "minecraft:axolotl_spawn_egg", "minecraft:barrier", "minecraft:bat_spawn_egg",
  "minecraft:bedrock", "minecraft:bee_spawn_egg", "minecraft:blaze_spawn_egg", "minecraft:bogged_spawn_egg",
  "minecraft:breeze_spawn_egg", "minecraft:camel_spawn_egg", "minecraft:cat_spawn_egg",
  "minecraft:cave_spider_spawn_egg", "minecraft:chain_command_block", "minecraft:chicken_spawn_egg",
  "minecraft:chorus_plant", "minecraft:cod_spawn_egg", "minecraft:command_block", "minecraft:command_block_minecart",
  "minecraft:cow_spawn_egg", "minecraft:creaking_spawn_egg", "minecraft:creeper_spawn_egg", "minecraft:debug_stick",
  "minecraft:dolphin_spawn_egg", "minecraft:donkey_spawn_egg", "minecraft:drowned_spawn_egg",
  "minecraft:elder_guardian_spawn_egg", "minecraft:end_portal_frame", "minecraft:ender_dragon_spawn_egg",
  "minecraft:enderman_spawn_egg", "minecraft:endermite_spawn_egg", "minecraft:evoker_spawn_egg",
  "minecraft:farmland", "minecraft:fox_spawn_egg", "minecraft:frog_spawn_egg", "minecraft:ghast_spawn_egg",
  "minecraft:glow_squid_spawn_egg", "minecraft:goat_spawn_egg", "minecraft:guardian_spawn_egg",
  "minecraft:happy_ghast_spawn_egg", "minecraft:hoglin_spawn_egg", "minecraft:horse_spawn_egg",
  "minecraft:husk_spawn_egg", "minecraft:infested_cobblestone", "minecraft:iron_golem_spawn_egg", "minecraft:jigsaw",
  "minecraft:knowledge_book", "minecraft:light", "minecraft:llama_spawn_egg", "minecraft:magma_cube_spawn_egg",
  "minecraft:mooshroom_spawn_egg", "minecraft:mule_spawn_egg", "minecraft:ocelot_spawn_egg",
  "minecraft:panda_spawn_egg", "minecraft:parrot_spawn_egg", "minecraft:phantom_spawn_egg",
  "minecraft:pig_spawn_egg", "minecraft:piglin_brute_spawn_egg", "minecraft:piglin_spawn_egg",
  "minecraft:pillager_spawn_egg", "minecraft:polar_bear_spawn_egg", "minecraft:pufferfish_spawn_egg",
  "minecraft:rabbit_spawn_egg", "minecraft:ravager_spawn_egg", "minecraft:repeating_command_block",
  "minecraft:salmon_spawn_egg", "minecraft:sheep_spawn_egg", "minecraft:shulker_spawn_egg",
  "minecraft:silverfish_spawn_egg", "minecraft:skeleton_horse_spawn_egg", "minecraft:skeleton_spawn_egg",
  "minecraft:slime_spawn_egg", "minecraft:sniffer_spawn_egg", "minecraft:snow_golem_spawn_egg",
  "minecraft:spider_spawn_egg", "minecraft:squid_spawn_egg", "minecraft:stray_spawn_egg",
  "minecraft:strider_spawn_egg", "minecraft:structure_block", "minecraft:structure_void",
  "minecraft:sulfur_cube_spawn_egg", "minecraft:suspicious_gravel", "minecraft:suspicious_sand",
  "minecraft:tadpole_spawn_egg", "minecraft:trader_llama_spawn_egg", "minecraft:trial_spawner",
  "minecraft:tropical_fish_spawn_egg", "minecraft:turtle_spawn_egg", "minecraft:vault", "minecraft:vex_spawn_egg",
  "minecraft:villager_spawn_egg", "minecraft:vindicator_spawn_egg", "minecraft:wandering_trader_spawn_egg",
  "minecraft:warden_spawn_egg", "minecraft:witch_spawn_egg", "minecraft:wither_skeleton_spawn_egg",
  "minecraft:wither_spawn_egg", "minecraft:wolf_spawn_egg", "minecraft:zoglin_spawn_egg",
  "minecraft:zombie_horse_spawn_egg", "minecraft:zombie_spawn_egg", "minecraft:zombie_villager_spawn_egg",
  "minecraft:zombified_piglin_spawn_egg", "moonlight:placeable_item", "moonlight:spawn_box",
  "naturalist:alligator_spawn_egg", "naturalist:anglerfish_spawn_egg", "naturalist:ant_spawn_egg",
  "naturalist:bass_spawn_egg", "naturalist:bear_spawn_egg", "naturalist:bird_spawn_egg",
  "naturalist:black_bear_spawn_egg", "naturalist:blobfish_spawn_egg", "naturalist:boar_spawn_egg",
  "naturalist:butterfly_spawn_egg", "naturalist:capybara_spawn_egg", "naturalist:caterpillar_spawn_egg",
  "naturalist:catfish_spawn_egg", "naturalist:clam_spawn_egg", "naturalist:crab_spawn_egg",
  "naturalist:deer_spawn_egg", "naturalist:desert_scorpion_spawn_egg", "naturalist:dragonfly_spawn_egg",
  "naturalist:duck_spawn_egg", "naturalist:elephant_spawn_egg", "naturalist:firefly_spawn_egg",
  "naturalist:giant_isopod_spawn_egg", "naturalist:giraffe_spawn_egg", "naturalist:great_white_shark_spawn_egg",
  "naturalist:hedgehog_spawn_egg", "naturalist:hippo_spawn_egg", "naturalist:jellyfish_spawn_egg",
  "naturalist:jungle_scorpion_spawn_egg", "naturalist:komodo_dragon_spawn_egg", "naturalist:lion_spawn_egg",
  "naturalist:lizard_spawn_egg", "naturalist:mammoth_spawn_egg", "naturalist:mole_spawn_egg",
  "naturalist:ostrich_spawn_egg", "naturalist:piranha_spawn_egg", "naturalist:rat_spawn_egg",
  "naturalist:ray_spawn_egg", "naturalist:rhino_spawn_egg", "naturalist:snail_spawn_egg",
  "naturalist:snake_spawn_egg", "naturalist:starfish_spawn_egg", "naturalist:tiger_spawn_egg",
  "naturalist:tortoise_spawn_egg", "naturalist:turkey_spawn_egg", "naturalist:vulture_spawn_egg",
  "naturalist:whale_spawn_egg", "naturalist:zebra_spawn_egg", "piglinproliferation:piglin_alchemist_spawn_egg",
  "piglinproliferation:piglin_traveler_spawn_egg", "regions_unexplored:black_painted_planks",
  "regions_unexplored:black_painted_slab", "regions_unexplored:black_painted_stairs",
  "regions_unexplored:bladed_tall_grass", "regions_unexplored:blue_painted_planks",
  "regions_unexplored:blue_painted_slab", "regions_unexplored:blue_painted_stairs",
  "regions_unexplored:brown_painted_planks", "regions_unexplored:brown_painted_slab",
  "regions_unexplored:brown_painted_stairs", "regions_unexplored:cyan_painted_planks",
  "regions_unexplored:cyan_painted_slab", "regions_unexplored:cyan_painted_stairs",
  "regions_unexplored:gray_painted_planks", "regions_unexplored:gray_painted_slab",
  "regions_unexplored:gray_painted_stairs", "regions_unexplored:green_painted_planks",
  "regions_unexplored:green_painted_slab", "regions_unexplored:green_painted_stairs",
  "regions_unexplored:light_blue_painted_planks", "regions_unexplored:light_blue_painted_slab",
  "regions_unexplored:light_blue_painted_stairs", "regions_unexplored:light_gray_painted_planks",
  "regions_unexplored:light_gray_painted_slab", "regions_unexplored:light_gray_painted_stairs",
  "regions_unexplored:lime_painted_planks", "regions_unexplored:lime_painted_slab",
  "regions_unexplored:lime_painted_stairs", "regions_unexplored:magenta_painted_planks",
  "regions_unexplored:magenta_painted_slab", "regions_unexplored:magenta_painted_stairs",
  "regions_unexplored:orange_painted_planks", "regions_unexplored:orange_painted_slab",
  "regions_unexplored:orange_painted_stairs", "regions_unexplored:pink_painted_planks",
  "regions_unexplored:pink_painted_slab", "regions_unexplored:pink_painted_stairs",
  "regions_unexplored:purple_painted_planks", "regions_unexplored:purple_painted_slab",
  "regions_unexplored:purple_painted_stairs", "regions_unexplored:red_painted_planks",
  "regions_unexplored:red_painted_slab", "regions_unexplored:red_painted_stairs",
  "regions_unexplored:sandy_tall_grass", "regions_unexplored:steppe_tall_grass",
  "regions_unexplored:white_painted_planks", "regions_unexplored:white_painted_slab",
  "regions_unexplored:white_painted_stairs", "regions_unexplored:yellow_painted_planks",
  "regions_unexplored:yellow_painted_slab", "regions_unexplored:yellow_painted_stairs",
  "simulated:creative_physics_staff", "sophisticatedbackpacks:advanced_mob_catcher_upgrade",
  "sophisticatedbackpacks:advanced_pump_upgrade", "sophisticatedbackpacks:battery_upgrade",
  "sophisticatedbackpacks:inception_upgrade", "sophisticatedbackpacks:infinity_upgrade",
  "sophisticatedbackpacks:mob_catcher_upgrade", "sophisticatedbackpacks:pump_upgrade",
  "sophisticatedbackpacks:stack_upgrade_omega_tier",
  "sophisticatedbackpacks:stack_upgrade_starter_tier_to_tier_3_conversion",
  "sophisticatedbackpacks:stack_upgrade_starter_tier_to_tier_4_conversion",
  "sophisticatedbackpacks:stack_upgrade_tier_1_to_tier_3_conversion",
  "sophisticatedbackpacks:stack_upgrade_tier_1_to_tier_4_conversion",
  "sophisticatedbackpacks:stack_upgrade_tier_2_to_tier_3_conversion",
  "sophisticatedbackpacks:stack_upgrade_tier_2_to_tier_4_conversion", "sophisticatedbackpacks:stack_upgrade_tier_3",
  "sophisticatedbackpacks:stack_upgrade_tier_3_to_tier_4_conversion", "sophisticatedbackpacks:stack_upgrade_tier_4",
  "sophisticatedbackpacks:survival_infinity_upgrade", "variantsandventures:gelid_spawn_egg",
  "variantsandventures:murk_spawn_egg", "variantsandventures:thicket_spawn_egg",
  "variantsandventures:verdant_spawn_egg"
]

// KubeJS 7 (this pack); JEIEvents is the KubeJS 6 name, kept as a fallback.
if (typeof RecipeViewerEvents !== 'undefined') {
  RecipeViewerEvents.removeEntries('item', (event) => {
    // One at a time: an id this pack doesn't have (a mod removed or renamed) mustn't stop the rest.
    let missing = []
    JEI_HIDDEN.forEach((id) => {
      try {
        event.remove(id)
      } catch (e) {
        missing.push(id)
      }
    })
    if (missing.length) console.info(`[jei_hidden] ${missing.length} ids not in this pack: ${missing.join(' ')}`)
  })
} else if (typeof JEIEvents !== 'undefined') {
  JEIEvents.hideItems((event) =>
    JEI_HIDDEN.forEach((id) => {
      try {
        event.hide(id)
      } catch (e) {}
    })
  )
}
