// GENERATED by publish/sources.mjs — do not edit.
// Where loot-only modded items come from, for the JEI info tab: chests and mobs from
// every mod jar's loot tables and loot modifiers, the Relics from their code.
const JEI_SOURCES = {
  "relics:chef_hat": [
    "Found in: village and pillager chests (Pillager Outpost, Village (16 houses),",
    "Dungeons and Taverns (3 structures), When Dungeons Arise: Bandit village,",
    "and 1 more).",
    "Relics rolls these into matching chests at random."
  ],
  "relics:chorus_staff": [
    "Found in: any loot chest in the End; End and stronghold chests (End City,",
    "Stronghold (3 rooms), Dungeons and Taverns: End castle,",
    "Dungeons and Taverns: End lighthouse).",
    "Relics rolls these into matching chests at random."
  ],
  "relics:clot_of_time": [
    "Found in: any loot chest in the End; End and stronghold chests (End City,",
    "Stronghold (3 rooms), Dungeons and Taverns: End castle,",
    "Dungeons and Taverns: End lighthouse).",
    "Relics rolls these into matching chests at random."
  ],
  "relics:cut_glass_boot": [
    "Found in: loot chests in ocean, beach and river biomes.",
    "Relics rolls these into matching chests at random."
  ],
  "relics:experience_disperser": [
    "Found in: any loot chest.",
    "Relics rolls these into matching chests at random."
  ],
  "relics:ghostly_mantle": [
    "Found in: any loot chest in the Nether; nether-themed chests (Nether Fortress,",
    "Ruined Portal, Dungeons and Taverns (5 structures), When Dungeons Arise: Foundry).",
    "Relics rolls these into matching chests at random."
  ],
  "relics:glitchy_mantle": [
    "Found in: any loot chest in the End; End and stronghold chests (End City,",
    "Stronghold (3 rooms), Dungeons and Taverns: End castle,",
    "Dungeons and Taverns: End lighthouse).",
    "Relics rolls these into matching chests at random."
  ],
  "relics:hunting_belt": [
    "Found in: village and pillager chests (Pillager Outpost, Village (16 houses),",
    "Dungeons and Taverns (3 structures), When Dungeons Arise: Bandit village,",
    "and 1 more).",
    "Relics rolls these into matching chests at random."
  ],
  "relics:jellyfish_necklace": [
    "Found in: loot chests in ocean, beach and river biomes.",
    "Relics rolls these into matching chests at random."
  ],
  "relics:kinetic_belt": [
    "Found in: any loot chest in the End; End and stronghold chests (End City,",
    "Stronghold (3 rooms), Dungeons and Taverns: End castle,",
    "Dungeons and Taverns: End lighthouse).",
    "Relics rolls these into matching chests at random."
  ],
  "relics:leafy_mantle": [
    "Found in: loot chests in forest biomes; loot chests in jungle biomes.",
    "Relics rolls these into matching chests at random."
  ],
  "relics:midnight_mantle": [
    "Found in: any loot chest in the End; End and stronghold chests (End City,",
    "Stronghold (3 rooms), Dungeons and Taverns: End castle,",
    "Dungeons and Taverns: End lighthouse).",
    "Relics rolls these into matching chests at random."
  ],
  "relics:piglin_mask": [
    "Found in: bastion and piglin chests (Bastion Remnant (4 rooms),",
    "Dungeons and Taverns (3 structures)).",
    "Relics rolls these into matching chests at random."
  ],
  "relics:reflective_necklace": [
    "Found in: any loot chest in the Nether; nether-themed chests (Nether Fortress,",
    "Ruined Portal, Dungeons and Taverns (5 structures), When Dungeons Arise: Foundry).",
    "Relics rolls these into matching chests at random."
  ],
  "relics:rider_flute": [
    "Found in: loot chests in cave biomes;",
    "village and pillager chests (Pillager Outpost, Village (16 houses),",
    "Dungeons and Taverns (3 structures), When Dungeons Arise: Bandit village,",
    "and 1 more).",
    "Relics rolls these into matching chests at random."
  ],
  "relics:ring_of_the_seven_deadly_sins": [
    "Found in: any loot chest in the Nether; nether-themed chests (Nether Fortress,",
    "Ruined Portal, Dungeons and Taverns (5 structures), When Dungeons Arise: Foundry).",
    "Relics rolls these into matching chests at random."
  ],
  "relics:roller_skate": [
    "Found in: any Overworld loot chest.",
    "Relics rolls these into matching chests at random."
  ],
  "relics:shield_of_retaliation": [
    "Found in: any loot chest in the Nether; nether-themed chests (Nether Fortress,",
    "Ruined Portal, Dungeons and Taverns (5 structures), When Dungeons Arise: Foundry).",
    "Relics rolls these into matching chests at random."
  ],
  "relics:sphere_of_self_sacrifice": [
    "Found in: any loot chest in the Nether; nether-themed chests (Nether Fortress,",
    "Ruined Portal, Dungeons and Taverns (5 structures), When Dungeons Arise: Foundry).",
    "Relics rolls these into matching chests at random."
  ],
  "relics:springy_boot": [
    "Found in: loot chests in mountain and hill biomes.",
    "Relics rolls these into matching chests at random."
  ],
  "create:andesite_alloy": [
    "Also found in: Create Let The Adventure Begin loot (5 structures)."
  ],
  "create:andesite_casing": [
    "Also found in: Create: Rustic Structures: Loot chests."
  ],
  "create:brass_block": [
    "Also found in: Create Let The Adventure Begin: Evoker trigger loot,",
    "Create Let The Adventure Begin: Normal loot."
  ],
  "create:brass_ingot": [
    "Also found in: Create Let The Adventure Begin loot (3 structures)."
  ],
  "create:cogwheel": [
    "Also found in: Create: Rustic Structures: Loot chests."
  ],
  "create:dough": [
    "Also found in: Create: Rustic Structures: Loot chests."
  ],
  "create:empty_blaze_burner": [
    "Also found in: Create Let The Adventure Begin: Evoker trigger loot,",
    "Create Let The Adventure Begin: Normal loot."
  ],
  "create:gearbox": [
    "Also found in: Create: Rustic Structures: Loot chests."
  ],
  "create:goggles": [
    "Also found in: Create Let The Adventure Begin: Evoker kill loot."
  ],
  "create:golden_sheet": [
    "Also found in: Create Let The Adventure Begin: Core loot."
  ],
  "create:honeyed_apple": [
    "Also found in: Create Let The Adventure Begin: Core loot."
  ],
  "create:iron_sheet": [
    "Also found in: Create Let The Adventure Begin: Core loot."
  ],
  "create:large_cogwheel": [
    "Also found in: Create: Rustic Structures: Loot chests."
  ],
  "create:polished_rose_quartz": [
    "Also found in: Create Let The Adventure Begin: Evoker trigger loot,",
    "Create Let The Adventure Begin: Normal loot."
  ],
  "create:rose_quartz": [
    "Also found in: Create Let The Adventure Begin: Core loot."
  ],
  "create:shaft": [
    "Also found in: Create: Rustic Structures: Loot chests."
  ],
  "create:wheat_flour": [
    "Also found in: Create: Rustic Structures: Loot chests."
  ],
  "create:zinc_ingot": [
    "Also found in: Create Let The Adventure Begin: Normal loot."
  ],
  "create:zinc_nugget": [
    "Also found in: Create: Rustic Structures: Loot chests."
  ],
  "farmersdelight:bacon": [
    "Also found in: Village butcher."
  ],
  "farmersdelight:cabbage_seeds": [
    "Also found in: Abandoned Mineshaft, Dungeon, Shipwreck (supply), and 1 more."
  ],
  "farmersdelight:cooking_pot": [
    "Also found in: Abandoned Mineshaft."
  ],
  "farmersdelight:diamond_knife": [
    "Also found in: Bastion Remnant (hoglin stable), Bastion Remnant (treasure),",
    "End City."
  ],
  "farmersdelight:flint_knife": [
    "Also found in: Village butcher."
  ],
  "farmersdelight:golden_knife": [
    "Also found in: Bastion Remnant (hoglin stable), Ruined Portal."
  ],
  "farmersdelight:ham": [
    "Found in: Bastion Remnant (hoglin stable), Village butcher.",
    "Dropped by: Hoglins, Pigs."
  ],
  "farmersdelight:iron_knife": [
    "Also found in: End City, Village butcher."
  ],
  "farmersdelight:minced_beef": [
    "Also found in: Village butcher."
  ],
  "farmersdelight:mutton_chops": [
    "Also found in: Village butcher."
  ],
  "farmersdelight:onion": [
    "Also found in: Pillager Outpost, Shipwreck (supply), Village plains house,",
    "and 7 more."
  ],
  "farmersdelight:onion_crate": [
    "Also found in: Pillager Outpost."
  ],
  "farmersdelight:rice": [
    "Also found in: Abandoned Mineshaft, Shipwreck (supply), Village desert house,",
    "and 1 more."
  ],
  "farmersdelight:rope": [
    "Also found in: Abandoned Mineshaft, Dungeon, Shipwreck (supply)."
  ],
  "farmersdelight:skillet": [
    "Also found in: Abandoned Mineshaft."
  ],
  "farmersdelight:smoked_ham": [
    "Also found in: Bastion Remnant (hoglin stable).",
    "Dropped by: Hoglins, Pigs."
  ],
  "farmersdelight:tomato_seeds": [
    "Also found in: Abandoned Mineshaft, Dungeon, Shipwreck (supply), and 1 more."
  ],
  "friendsandfoes:crab_claw": [
    "Dropped by: Crabs (Friends&Foes)."
  ],
  "friendsandfoes:music_disc_around_the_corner": [
    "Found in: Abandoned Mineshaft."
  ],
  "friendsandfoes:totem_of_freezing": [
    "Dropped by: Iceologers (Friends&Foes)."
  ],
  "friendsandfoes:totem_of_illusion": [
    "Dropped by: Illusioners (Friends&Foes)."
  ],
  "friendsandfoes:wildfire_crown_fragment": [
    "Dropped by: Wildfires (Friends&Foes)."
  ],
  "illagerinvasion:illusionary_dust": [
    "Found in: Illager Invasion: Illusioner tower chests.",
    "Dropped by: Illusioners."
  ],
  "illagerinvasion:lost_candle": [
    "Found in: Illager Invasion: Labyrinth chests."
  ],
  "illagerinvasion:platinum_chunk": [
    "Dropped by: Pillagers, Ravagers, Inquisitors (Illager Invasion)."
  ],
  "illagerinvasion:primal_essence": [
    "Dropped by: Invokers (Illager Invasion)."
  ],
  "illagerinvasion:unusual_dust": [
    "Found in: Illager Invasion: Sorcerer hut chests.",
    "Dropped by: Sorcerers (Illager Invasion)."
  ],
  "lemursaucepacket:duelists_pattern": [
    "Found in: Ancient City, Stronghold (library),",
    "When Dungeons Arise chests (38 structures)."
  ],
  "lemursaucepacket:ember_crown": [
    "Found in: Bastion Remnant (treasure), Nether Fortress."
  ],
  "lemursaucepacket:stormcallers_sabre": [
    "Found in: Pillager Outpost, When Dungeons Arise chests (38 structures)."
  ],
  "lootr:trophy": [
    "Found in: Lootr: Trophy reward."
  ],
  "naturalist:anglerfish": [
    "Dropped by: Anglerfish (Naturalist)."
  ],
  "naturalist:antler": [
    "Dropped by: Deer (Naturalist)."
  ],
  "naturalist:azure_froglass": [
    "Dropped by: Dragonflies (Naturalist)."
  ],
  "naturalist:bass": [
    "Found in: Fishing (Naturalist).",
    "Dropped by: Bass (Naturalist)."
  ],
  "naturalist:blobfish": [
    "Dropped by: Blobfish (Naturalist)."
  ],
  "naturalist:bushmeat": [
    "Dropped by: Capybaras, Elephants, Giraffes, Komodo Dragons, Rhinos,",
    "Zebras (Naturalist)."
  ],
  "naturalist:catfish": [
    "Dropped by: Catfish (Naturalist)."
  ],
  "naturalist:clam_meat": [
    "Dropped by: Clams (Naturalist)."
  ],
  "naturalist:crab_meat": [
    "Dropped by: Crabs, Rays (Naturalist)."
  ],
  "naturalist:crimson_froglass": [
    "Dropped by: Dragonflies (Naturalist)."
  ],
  "naturalist:drumstick": [
    "Dropped by: Ostriches, Turkeys (Naturalist)."
  ],
  "naturalist:duck": [
    "Dropped by: Ducks (Naturalist)."
  ],
  "naturalist:fat": [
    "Dropped by: Boars, Mammoths, Whales (Naturalist)."
  ],
  "naturalist:fur": [
    "Dropped by: Bears, Black Bears, Capybaras, Lions, Mammoths, Moles,",
    "and 2 more (Naturalist)."
  ],
  "naturalist:hide": [
    "Dropped by: Boars, Elephants, Komodo Dragons, Rhinos (Naturalist)."
  ],
  "naturalist:lizard_tail": [
    "Dropped by: Lizard Tails (Naturalist)."
  ],
  "naturalist:mammoth_meat": [
    "Dropped by: Mammoths (Naturalist)."
  ],
  "naturalist:morsel": [
    "Dropped by: Hedgehogs, Lizards, Rats, Snakes, Vultures (Naturalist)."
  ],
  "naturalist:piranha": [
    "Dropped by: Piranhas (Naturalist)."
  ],
  "naturalist:scorpion_poison_gland": [
    "Dropped by: Desert Scorpions, Jungle Scorpions (Naturalist)."
  ],
  "naturalist:tooth": [
    "Dropped by: Alligators, Great White Sharks, Lions, Snakes, Tigers (Naturalist)."
  ],
  "naturalist:venison": [
    "Dropped by: Deer (Naturalist)."
  ],
  "naturalist:verdant_froglass": [
    "Dropped by: Dragonflies (Naturalist)."
  ],
  "piglinproliferation:travelers_compass": [
    "Found in: Piglin Proliferation: Traveler bartering."
  ],
  "sophisticatedbackpacks:advanced_magnet_upgrade": [
    "Also found in: End City, Shipwreck (treasure), Woodland Mansion."
  ],
  "sophisticatedbackpacks:backpack": [
    "Also found in: Abandoned Mineshaft, Dungeon, Spawn bonus chest."
  ],
  "sophisticatedbackpacks:copper_backpack": [
    "Also found in: Abandoned Mineshaft, Desert Pyramid, Dungeon."
  ],
  "sophisticatedbackpacks:diamond_backpack": [
    "Also found in: End City."
  ],
  "sophisticatedbackpacks:feeding_upgrade": [
    "Also found in: Bastion Remnant (treasure), Nether Fortress."
  ],
  "sophisticatedbackpacks:gold_backpack": [
    "Also found in: Abandoned Mineshaft, Bastion Remnant (treasure), Desert Pyramid,",
    "and 4 more."
  ],
  "sophisticatedbackpacks:iron_backpack": [
    "Also found in: Abandoned Mineshaft, Bastion Remnant (treasure), Desert Pyramid,",
    "and 3 more."
  ],
  "sophisticatedbackpacks:magnet_upgrade": [
    "Also found in: Abandoned Mineshaft, Desert Pyramid."
  ],
  "sophisticatedbackpacks:pickup_upgrade": [
    "Also found in: Dungeon."
  ]
}

const registerSources = (event) => {
  Object.keys(JEI_SOURCES).forEach((id) => {
    try {
      event.add(id, JEI_SOURCES[id])
    } catch (e) {}
  })
}
// KubeJS 7 (this pack); JEIEvents is the KubeJS 6 name, kept as a fallback.
if (typeof RecipeViewerEvents !== 'undefined') {
  RecipeViewerEvents.addInformation('item', registerSources)
} else if (typeof JEIEvents !== 'undefined') {
  JEIEvents.information(registerSources)
}

const SOURCE_TIPS = {
  "relics:chef_hat": "Found in: village and pillager chests (Pillager Outpost, Village (16 h…",
  "relics:chorus_staff": "Found in: any loot chest in the End; End and stronghold chests (End Ci…",
  "relics:clot_of_time": "Found in: any loot chest in the End; End and stronghold chests (End Ci…",
  "relics:cut_glass_boot": "Found in: loot chests in ocean, beach and river biomes",
  "relics:experience_disperser": "Found in: any loot chest",
  "relics:ghostly_mantle": "Found in: any loot chest in the Nether; nether-themed chests (Nether F…",
  "relics:glitchy_mantle": "Found in: any loot chest in the End; End and stronghold chests (End Ci…",
  "relics:hunting_belt": "Found in: village and pillager chests (Pillager Outpost, Village (16 h…",
  "relics:jellyfish_necklace": "Found in: loot chests in ocean, beach and river biomes",
  "relics:kinetic_belt": "Found in: any loot chest in the End; End and stronghold chests (End Ci…",
  "relics:leafy_mantle": "Found in: loot chests in forest biomes; loot chests in jungle biomes",
  "relics:midnight_mantle": "Found in: any loot chest in the End; End and stronghold chests (End Ci…",
  "relics:piglin_mask": "Found in: bastion and piglin chests (Bastion Remnant (4 rooms), Dungeo…",
  "relics:reflective_necklace": "Found in: any loot chest in the Nether; nether-themed chests (Nether F…",
  "relics:rider_flute": "Found in: loot chests in cave biomes; village and pillager chests (Pil…",
  "relics:ring_of_the_seven_deadly_sins": "Found in: any loot chest in the Nether; nether-themed chests (Nether F…",
  "relics:roller_skate": "Found in: any Overworld loot chest",
  "relics:shield_of_retaliation": "Found in: any loot chest in the Nether; nether-themed chests (Nether F…",
  "relics:sphere_of_self_sacrifice": "Found in: any loot chest in the Nether; nether-themed chests (Nether F…",
  "relics:springy_boot": "Found in: loot chests in mountain and hill biomes",
  "create:andesite_alloy": "Also found in: Create Let The Adventure Begin loot (5 structures)",
  "create:andesite_casing": "Also found in: Create: Rustic Structures: Loot chests",
  "create:brass_block": "Also found in: Create Let The Adventure Begin: Evoker trigger loot, Cr…",
  "create:brass_ingot": "Also found in: Create Let The Adventure Begin loot (3 structures)",
  "create:cogwheel": "Also found in: Create: Rustic Structures: Loot chests",
  "create:dough": "Also found in: Create: Rustic Structures: Loot chests",
  "create:empty_blaze_burner": "Also found in: Create Let The Adventure Begin: Evoker trigger loot, Cr…",
  "create:gearbox": "Also found in: Create: Rustic Structures: Loot chests",
  "create:goggles": "Also found in: Create Let The Adventure Begin: Evoker kill loot",
  "create:golden_sheet": "Also found in: Create Let The Adventure Begin: Core loot",
  "create:honeyed_apple": "Also found in: Create Let The Adventure Begin: Core loot",
  "create:iron_sheet": "Also found in: Create Let The Adventure Begin: Core loot",
  "create:large_cogwheel": "Also found in: Create: Rustic Structures: Loot chests",
  "create:polished_rose_quartz": "Also found in: Create Let The Adventure Begin: Evoker trigger loot, Cr…",
  "create:rose_quartz": "Also found in: Create Let The Adventure Begin: Core loot",
  "create:shaft": "Also found in: Create: Rustic Structures: Loot chests",
  "create:wheat_flour": "Also found in: Create: Rustic Structures: Loot chests",
  "create:zinc_ingot": "Also found in: Create Let The Adventure Begin: Normal loot",
  "create:zinc_nugget": "Also found in: Create: Rustic Structures: Loot chests",
  "farmersdelight:bacon": "Also found in: Village butcher",
  "farmersdelight:cabbage_seeds": "Also found in: Abandoned Mineshaft, Dungeon, Shipwreck (supply), and 1…",
  "farmersdelight:cooking_pot": "Also found in: Abandoned Mineshaft",
  "farmersdelight:diamond_knife": "Also found in: Bastion Remnant (hoglin stable), Bastion Remnant (treas…",
  "farmersdelight:flint_knife": "Also found in: Village butcher",
  "farmersdelight:golden_knife": "Also found in: Bastion Remnant (hoglin stable), Ruined Portal",
  "farmersdelight:ham": "Found in: Bastion Remnant (hoglin stable), Village butcher",
  "farmersdelight:iron_knife": "Also found in: End City, Village butcher",
  "farmersdelight:minced_beef": "Also found in: Village butcher",
  "farmersdelight:mutton_chops": "Also found in: Village butcher",
  "farmersdelight:onion": "Also found in: Pillager Outpost, Shipwreck (supply), Village plains ho…",
  "farmersdelight:onion_crate": "Also found in: Pillager Outpost",
  "farmersdelight:rice": "Also found in: Abandoned Mineshaft, Shipwreck (supply), Village desert…",
  "farmersdelight:rope": "Also found in: Abandoned Mineshaft, Dungeon, Shipwreck (supply)",
  "farmersdelight:skillet": "Also found in: Abandoned Mineshaft",
  "farmersdelight:smoked_ham": "Also found in: Bastion Remnant (hoglin stable)",
  "farmersdelight:tomato_seeds": "Also found in: Abandoned Mineshaft, Dungeon, Shipwreck (supply), and 1…",
  "friendsandfoes:crab_claw": "Dropped by: Crabs (Friends&Foes)",
  "friendsandfoes:music_disc_around_the_corner": "Found in: Abandoned Mineshaft",
  "friendsandfoes:totem_of_freezing": "Dropped by: Iceologers (Friends&Foes)",
  "friendsandfoes:totem_of_illusion": "Dropped by: Illusioners (Friends&Foes)",
  "friendsandfoes:wildfire_crown_fragment": "Dropped by: Wildfires (Friends&Foes)",
  "illagerinvasion:illusionary_dust": "Found in: Illager Invasion: Illusioner tower chests",
  "illagerinvasion:lost_candle": "Found in: Illager Invasion: Labyrinth chests",
  "illagerinvasion:platinum_chunk": "Dropped by: Pillagers, Ravagers, Inquisitors (Illager Invasion)",
  "illagerinvasion:primal_essence": "Dropped by: Invokers (Illager Invasion)",
  "illagerinvasion:unusual_dust": "Found in: Illager Invasion: Sorcerer hut chests",
  "lemursaucepacket:duelists_pattern": "Found in: Ancient City, Stronghold (library), When Dungeons Arise ches…",
  "lemursaucepacket:ember_crown": "Found in: Bastion Remnant (treasure), Nether Fortress",
  "lemursaucepacket:stormcallers_sabre": "Found in: Pillager Outpost, When Dungeons Arise chests (38 structures)",
  "lootr:trophy": "Found in: Lootr: Trophy reward",
  "naturalist:anglerfish": "Dropped by: Anglerfish (Naturalist)",
  "naturalist:antler": "Dropped by: Deer (Naturalist)",
  "naturalist:azure_froglass": "Dropped by: Dragonflies (Naturalist)",
  "naturalist:bass": "Found in: Fishing (Naturalist)",
  "naturalist:blobfish": "Dropped by: Blobfish (Naturalist)",
  "naturalist:bushmeat": "Dropped by: Capybaras, Elephants, Giraffes, Komodo Dragons, Rhinos, Ze…",
  "naturalist:catfish": "Dropped by: Catfish (Naturalist)",
  "naturalist:clam_meat": "Dropped by: Clams (Naturalist)",
  "naturalist:crab_meat": "Dropped by: Crabs, Rays (Naturalist)",
  "naturalist:crimson_froglass": "Dropped by: Dragonflies (Naturalist)",
  "naturalist:drumstick": "Dropped by: Ostriches, Turkeys (Naturalist)",
  "naturalist:duck": "Dropped by: Ducks (Naturalist)",
  "naturalist:fat": "Dropped by: Boars, Mammoths, Whales (Naturalist)",
  "naturalist:fur": "Dropped by: Bears, Black Bears, Capybaras, Lions, Mammoths, Moles, and…",
  "naturalist:hide": "Dropped by: Boars, Elephants, Komodo Dragons, Rhinos (Naturalist)",
  "naturalist:lizard_tail": "Dropped by: Lizard Tails (Naturalist)",
  "naturalist:mammoth_meat": "Dropped by: Mammoths (Naturalist)",
  "naturalist:morsel": "Dropped by: Hedgehogs, Lizards, Rats, Snakes, Vultures (Naturalist)",
  "naturalist:piranha": "Dropped by: Piranhas (Naturalist)",
  "naturalist:scorpion_poison_gland": "Dropped by: Desert Scorpions, Jungle Scorpions (Naturalist)",
  "naturalist:tooth": "Dropped by: Alligators, Great White Sharks, Lions, Snakes, Tigers (Nat…",
  "naturalist:venison": "Dropped by: Deer (Naturalist)",
  "naturalist:verdant_froglass": "Dropped by: Dragonflies (Naturalist)",
  "piglinproliferation:travelers_compass": "Found in: Piglin Proliferation: Traveler bartering",
  "sophisticatedbackpacks:advanced_magnet_upgrade": "Also found in: End City, Shipwreck (treasure), Woodland Mansion",
  "sophisticatedbackpacks:backpack": "Also found in: Abandoned Mineshaft, Dungeon, Spawn bonus chest",
  "sophisticatedbackpacks:copper_backpack": "Also found in: Abandoned Mineshaft, Desert Pyramid, Dungeon",
  "sophisticatedbackpacks:diamond_backpack": "Also found in: End City",
  "sophisticatedbackpacks:feeding_upgrade": "Also found in: Bastion Remnant (treasure), Nether Fortress",
  "sophisticatedbackpacks:gold_backpack": "Also found in: Abandoned Mineshaft, Bastion Remnant (treasure), Desert…",
  "sophisticatedbackpacks:iron_backpack": "Also found in: Abandoned Mineshaft, Bastion Remnant (treasure), Desert…",
  "sophisticatedbackpacks:magnet_upgrade": "Also found in: Abandoned Mineshaft, Desert Pyramid",
  "sophisticatedbackpacks:pickup_upgrade": "Also found in: Dungeon"
}
ItemEvents.modifyTooltips((event) => {
  Object.keys(SOURCE_TIPS).forEach((id) => {
    try {
      event.modify(id, (tooltip) => tooltip.add(Text.of('\u00a78\u00a7o' + SOURCE_TIPS[id])))
    } catch (e) {}
  })
})
